### PR TITLE
[vulkan] Use TI_VISIBLE_DEVICE to select vulkan device

### PR DESCRIPTION
**Pull request by qiao-bo**
Add an env var option `TI_VISIBLE_DEVICE` to enable user selected vulkan device. The identifier is device id, can be obtained by querying `vulkaninfo`.

### CODE REVIEW

**Review by ailzhang — COMMENTED** [review]
sorry this might be a dumb question, how do I list all my vulkan devices before setting? ;)

**Comment by qiao-bo** [comment]
> sorry this might be a dumb question, how do I list all my vulkan devices before setting? ;)

legitimate question! `vulkaninfo` can be used. similar to clinfo or devicequery for cuda. The idea is to have a unique identifier rather than 0, 1 ,2...  Please suggest if there are better options~

**Comment by bobcao3** [comment]
Should probably rename to `TI_USE_VULKAN_DEVICE` since "visible device" is quite confusing.

**Comment by k-ye** [comment]
> Should probably rename to `TI_USE_VULKAN_DEVICE` since "visible device" is quite confusing.

I suggest to remove the specific mentioning of `VULKAN_`, since many other APIs support GPU selection as well.

**Comment by qiao-bo** [comment]
> > Should probably rename to `TI_USE_VULKAN_DEVICE` since "visible device" is quite confusing.
> 
> I suggest to remove the specific mentioning of `VULKAN_`, since many other APIs support GPU selection as well.

this is the intention, same switch could be used for other APIs.

**Review by bobcao3 — APPROVED** [review]
LGTM

**Pull request merged**
