### PR TITLE
[ci] [build] Containerize Windows CPU build and test

### PR DESCRIPTION
**Pull request by qiao-bo**
Let's add a job in our CI workflow to enable the Windows CPU build and test. This job is (a) Docker containerized and (b) Employs Github hosted runner.

The added `win_build_test_script` has overlap with the existing windows script. Let's keep the merge task in a follow-up PR.

### CODE REVIEW

**Comment by qiao-bo** [comment]
```
[482/510] Building CXX object external/SPIRV-Tools/source/reduce/CMakeFiles/SPIRV-Tools-reduce.dir/reduction_opportunity.cpp.obj
[483/510] Linking CXX shared module taichi_core.pyd
FAILED: taichi_core.pyd 
cmd.exe /C "cd . && C:\PROGRA~2\MICROS~1\2019\BUILDT~1\vc\Tools\Llvm\x64\bin\CLANG_~1.EXE -fuse-ld=lld-link -nostartfiles -nostdlib -DTI_ISE_NONE -flto=thin -std=c++17 -fsized-deallocation -target x86_64-pc-windows-msvc -march=nehalem -DTI_ARCH_x64 -DTI_PASS_EXCEPTION_TO_PYTHON -DTI_INCLUDED -DTI_WITH_LLVM -DTI_WITH_METAL -O3 -DNDEBUG -D_DLL -D_MT -Xclang --dependent-lib=msvcrt  -flto -shared -o taichi_core.pyd  -Xlinker /MANIFEST:EMBED -Xlinker /implib:taichi_core.lib -Xlinker /pdb:taichi_core.pdb -Xlinker /version:0.0 @CMakeFiles\taichi_core.rsp  && cmd.exe /C "cd /D C:\taichi\_skbuild\win-amd64-3.7\cmake-build && "C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\Llvm\x64\bin\llvm-strip.exe" C:/taichi/_skbuild/win-amd64-3.7/cmake-build/taichi_core.pyd""
LLVM ERROR: Associative COMDAT symbol '??0cast_error@pybind11@@QEAA@PEBD@Z' does not exist.
PLEASE submit a bug report to https://bugs.llvm.org/ and include the crash backtrace.
Stack dump:
0.	Program arguments: C:\\PROGRA~2\\MICROS~1\\2019\\BUILDT~1\\vc\\Tools\\Llvm\\x64\\bin\\lld-link -out:taichi_core.pyd -libpath:C:\\PROGRA~2\\MICROS~1\\2019\\BUILDT~1\\vc\\Tools\\Llvm\\x64\\lib\\clang\\12.0.0\\lib\\windows -libpath:C:/taichi/external/lib -nologo -dll -implib:taichi_core.lib /MANIFEST:EMBED /implib:taichi_core.lib /pdb:taichi_core.pdb /version:0.0 CMakeFiles/taichi_isolated_core.dir/taichi/analysis/alias_analysis.cpp.obj CMakeFiles/taichi_isolated_core.dir/taichi/analysis/arithmetic_interpretor.cpp.obj CMakeFiles/taichi_isolated_core.dir/taichi/analysis/bls_analyzer.cpp.obj 
```

**Comment by frostming** [comment]
Can we change it to `container` setting for this specific job?
https://docs.github.com/en/actions/using-jobs/running-jobs-in-a-container

**Comment by qiao-bo** [comment]
> Can we change it to `container` setting for this specific job? https://docs.github.com/en/actions/using-jobs/running-jobs-in-a-container

Sounds like a good idea, we can do that. But does it relate to that error that skbuild generate?

**Comment by qiao-bo** [comment]
Update: The above error is caused by `pybind11_add_module`. Switch back to `add_library` temporally skip the llvm issue.

**Comment by qiao-bo** [comment]
> Can we change it to `container` setting for this specific job? https://docs.github.com/en/actions/using-jobs/running-jobs-in-a-container

I just tried this and got `Error: Container operations are only supported on Linux runners` ;/. Unfortunately. 
I really like this since it is much concise. Maybe we can refactor the Linux CPU job using this container setting.

**Review by frostming — APPROVED** [review]

**Pull request merged**
