### PR TITLE
[lang] Add a name parameter to fields

### LINKED ISSUE #2006: [lang] Add a "name" parameter to fields
**Concisely describe the proposed feature**
Currently, if we write something like
```python
a = ti.field(ti.i32)
ti.root.dense(ti.i, 8).place(a)
```
, Taichi doesn't know that the field's name is `a`, and doesn't know that the `place` SNode's name is `a`.

So when users encounter some compilation error or developers want to print out some field's name, the Taichi compiler can only print out something like `S2place_i32`, which is not intuitive for debugging.

**Describe the solution you'd like (if any)**
We can add a `name` parameter to fields (including `ti.field, ti.Vector.field, ti.Matrix.field`), and pass it into `SNode`s. Then we can acquire the field's name through a `SNode *` in the codebase. The code above can be modified into
```python
a = ti.field(ti.i32, name='a')
ti.root.dense(ti.i, 8).place(a)
```
for printing out the field's name.

**Additional comments**
This feature is especially useful when a Taichi program has too many fields and a developer wants to locate a specific one.

### PR DESCRIPTION
**Pull request by beginlner**
Related issue = close #2006

### CODE REVIEW

**Comment by ljcc0930** [comment]
Good work!

**Comment by beginlner** [comment]
API: `<field>.name` or <field>.snode.name`

**Comment by ljcc0930** [comment]
LGTM & thanks for your contribution! It would be great if you can add some tests for the new feature!

**Review by ljcc0930 — APPROVED** [review]

**Review by ljcc0930 — APPROVED** [review]
LGTM!

**Pull request merged**
