### PR TITLE
[refactor] [ir] Remove legacy ElementShuffleStmt

### PR DESCRIPTION
**Pull request by strongoier**
Related issue = #4096

In this PR, `lower_vector_ptr()` is rewritten and renamed to `lower_ptr()` so that the legacy `ElementShuffleStmt` can be fully removed.

### CODE REVIEW

**Review by ailzhang — APPROVED** [review]
Nice! 
OOC: what was ElementShuffleStmt used for? :P

**Review by jim19930609 — APPROVED** [review]
Thanks! 

Btw, just asking: is "LaneAttribute" also removable?

**Comment by strongoier** [comment]
> Nice! OOC: what was ElementShuffleStmt used for? :P

For legacy vectorization.

**Comment by strongoier** [comment]
> Btw, just asking: is "LaneAttribute" also removable?

Yep. I intend to remove these one by one otherwise a single PR will be too large.

**Pull request merged**
