### PR TITLE
[cc] Set up the experimental C language backend

### PR DESCRIPTION
**Pull request by archibate**
Related issue = #1332

[[Click here for the format server]](http://kun.csail.mit.edu:31415/)

----

### CODE REVIEW

**Comment by archibate** [comment]
Hello? I managed to make `taichi/backends/cc/*` not compiled when `TI_WITH_CC=OFF` as #529 want.

**Comment by archibate** [comment]
cc = C compiler.
How about to use captalized `C` as namespace & arch name?

**Comment by archibate** [comment]
So, may I merge this for now? I'm afraid renaming here will cause conflicts in #1354, I will do the name nits in #1354 after this is merged.

**Comment by yuanming-hu** [comment]
> cc = C compiler.
> How about to use captalized `C` as namespace & arch name? i.e. `C::compile_kernel`.

Yeah capitalized `C` sounds good! `cc` for `C compiler` maybe slightly confusing, given it's actually a `C backend` instead of `C compiler`.

@k-ye what do you think?

Please feel free to merge. Thanks!

**Comment by k-ye** [comment]
Sorry I probably won't have much time for this these days.

While I wanted to say that Google's coding style [requires all lower-case namespace names](https://google.github.io/styleguide/cppguide.html#Namespace_Names), I think we already have one exception, `Tlang` (or was it `tlang`)?

**Comment by yuanming-hu** [comment]
> Sorry I probably won't have much time for this these days.

No worries at all :-)

> While I wanted to say that Google's coding style [requires all lower-case namespace names](https://google.github.io/styleguide/cppguide.html#Namespace_Names), I think we already have one exception, `Tlang` (or was it `tlang`)?

Thanks for the reply! `Tlang` has been replaced with `taichi::lang`. 

> Google's coding style [requires all lower-case namespace names](https://google.github.io/styleguide/cppguide.html#Namespace_Names)

Yeah, that's a good point. I think we can stick to `ti.c` - we already have `ti.i, ti.j, ...` anyway... Upper-cased identifiers should be left for classes.

I don't think using a lower-case single-letter identifier will lead to problems as long as we keep it in namespaces, i.e., `taichi::lang::c`.

(Of course if someone does `#define c(x) ...` then we get a conflict, but I believe our dependency don't do that...)

**Pull request merged**
