### PR TITLE
[SIMT] Add uni_sync warp intrinsics

### PR DESCRIPTION
**Pull request by 0xzhang**
Related issue = #4631

### CODE REVIEW

**Comment by 0xzhang** [comment]
I couldn't find any accurate information about `__uni_sync`. And I misunderstood the meaning of `unique` to Equal. I'll try to fix it.

https://docs.nvidia.com/cuda/nvvm-ir-spec/index.html#nvvm-intrin-warp-level-vote

**Comment by 0xzhang** [comment]
- GeForce GTX 1650
- CUDA 11.4

It seems `test_simt.py` not testable on my PC.
I use command below.
```shell
python tests/run_tests.py -t1 -k test_simt
```

image

**Comment by 0xzhang** [comment]
I only find one description about `__uni_sync()` on whole Internet.
If and only if the `predicate` of all threads which specified by `mask` are all non-zero or all zero, return 1, else return 0.

https://www.cnblogs.com/cuancuancuanhao/p/7841512.html

**Comment by GaleSeLee** [comment]
> * GeForce GTX 1650
> * CUDA 11.4
> 
> It seems `test_simt.py` not testable on my PC. I use command below.
> 
> ```shell
> python tests/run_tests.py -t1 -k test_simt
> ```
> 
> image
> 
> Warp functions have requirements to compute capability of device. Maybe my card doesn't have enough compute capability according the [list](https://developer.nvidia.com/cuda-gpus). Or maybe the WSL environment limits the compute capability.

Do you solve this problem? I have a similar problem when I write `match_all` warp intrinsic

**Comment by 0xzhang** [comment]
@GaleSeLee No, I'm not sure the cause of problem. I can only use CI to verify that my test passed.

**Review by turbo0628 — APPROVED** [review]
LGTM!

**Comment by turbo0628** [comment]
@GaleSeLee Can you try on that Linux RTX3080 machine?

**Comment by GaleSeLee** [comment]
> No, I'm not sure the cause of problem. I can only use CI to verify that my test passed.

yeah, I'll come back later with the results

**Comment by GaleSeLee** [comment]
> 

It occurs the same error on RTX3080 machine.

**Comment by turbo0628** [comment]
> It occurs the same error on RTX3080 machine.

Could you update more information about the crash in tests? Mine works fine. I think we are using the identical environments.

**Comment by GaleSeLee** [comment]
> > yeah, I'll come back later with the results
> 
> It occurs the same error on RTX3080 machine.

I'm wrong. And there is no error occured on RTX3080 machine.

**Comment by turbo0628** [comment]
@0xzhang I think your guess is right, some legacy GPUs cannot support SIMT instructions. 

However, Taichi should speak out loudly when the GPU cannot run warp-level primitives. Could you file an issue to track this problem?

**Comment by 0xzhang** [comment]
> ```shell
> python tests/run_tests.py -t1 -k test_simt
> ```

OK, I create a [gist](https://gist.github.com/0xzhang/1929ad8d044671d05a3fac717c703843).

**Comment by 0xzhang** [comment]
> @0xzhang I think your guess is right, some legacy GPUs cannot support SIMT instructions.
> 
> However, Taichi should speak out loudly when the GPU cannot run warp-level primitives. Could you file an issue to track this problem?

Yes, I create a [gist](https://gist.github.com/0xzhang/1929ad8d044671d05a3fac717c703843).

**Comment by 0xzhang** [comment]
@turbo0628 I create a gist file [here](https://gist.github.com/0xzhang/1929ad8d044671d05a3fac717c703843).

**Comment by turbo0628** [comment]
Thanks!

**Pull request merged**
