### PR TITLE
[build] Delete all llvm10 code and TI_LLVM_15 macro

### PR DESCRIPTION
**Pull request by ailzhang**
Issue: #6447

### Brief Summary
LLVM10 is dead in taichi codebase, long live LLVM15!

I wanna mention that a lot of hard work in this upgrade was done by our OSS contributor @python3kgae , thanks a ton!!!

### CODE REVIEW

**Review by strongoier — APPROVED** [review]
Great!!

**Review by jim19930609 — APPROVED** [review]
image

**Pull request merged**
