### PR TITLE
[vulkan] Force the link path of MoltenVK to be relative

### PR DESCRIPTION
**Pull request by bobcao3**
Related: #3787

After this change the path of MoltenVK is now `@rpath/libMoltenVK.dylib`, however I'm not sure whether `python/taichi/_lib/runtime` is in the `@rpath` or not. If it is not in there, maybe we need to put libMoltenVK.dylib along side `libtaichi_core.so`

### CODE REVIEW

**Review by ailzhang — COMMENTED** [review]
IIRC we haven't enabled vulkan test on m1 yet? shall we do it in/before this PR? ;) 
Looks like we no longer copy libMoltenVK.dylib to our python package after this PR, is this intended?

**Review by lin-hitonami — CHANGES_REQUESTED** [review]
This doesn't seem to work...
First, `libMoltenVK.dylib` is not copied to the package.
Second, the path of `libMoltenVK.dylib` is still absolute. Here is the output of otool.
```
(test38) lin@LindeMacBook-Pro core % otool -L taichi_core.so 
taichi_core.so:
	@rpath/libtaichi_core.dylib (compatibility version 0.0.0, current version 0.0.0)
	/System/Library/Frameworks/Cocoa.framework/Versions/A/Cocoa (compatibility version 1.0.0, current version 23.0.0)
	/System/Library/Frameworks/IOKit.framework/Versions/A/IOKit (compatibility version 1.0.0, current version 275.0.0)
	/System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation (compatibility version 150.0.0, current version 1775.118.101)
	/usr/lib/libz.1.dylib (compatibility version 1.0.0, current version 1.2.11)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1292.100.5)
	/opt/homebrew/opt/molten-vk/lib/libMoltenVK.dylib (compatibility version 1.0.0, current version 1.0.0)
	/System/Library/Frameworks/Metal.framework/Versions/A/Metal (compatibility version 1.0.0, current version 244.119.0)
	/usr/lib/libc++.1.dylib (compatibility version 1.0.0, current version 905.6.0)
	/System/Library/Frameworks/AppKit.framework/Versions/C/AppKit (compatibility version 45.0.0, current version 2022.44.149)
	/System/Library/Frameworks/CoreGraphics.framework/Versions/A/CoreGraphics (compatibility version 64.0.0, current version 1463.4.2)
	/System/Library/Frameworks/CoreServices.framework/Versions/A/CoreServices (compatibility version 1.0.0, current version 1122.33.0)
	/System/Library/Frameworks/Foundation.framework/Versions/C/Foundation (compatibility version 300.0.0, current version 1775.118.101)
	/usr/lib/libobjc.A.dylib (compatibility version 1.0.0, current version 228.0.0)
```

**Comment by bobcao3** [comment]
> This doesn't seem to work... First, `libMoltenVK.dylib` is not copied to the package. Second, the path of `libMoltenVK.dylib` is still absolute. Here is the output of otool.
> 
> ```
> (test38) lin@LindeMacBook-Pro core % otool -L taichi_core.so 
> taichi_core.so:
> 	@rpath/libtaichi_core.dylib (compatibility version 0.0.0, current version 0.0.0)
> 	/System/Library/Frameworks/Cocoa.framework/Versions/A/Cocoa (compatibility version 1.0.0, current version 23.0.0)
> 	/System/Library/Frameworks/IOKit.framework/Versions/A/IOKit (compatibility version 1.0.0, current version 275.0.0)
> 	/System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation (compatibility version 150.0.0, current version 1775.118.101)
> 	/usr/lib/libz.1.dylib (compatibility version 1.0.0, current version 1.2.11)
> 	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1292.100.5)
> 	/opt/homebrew/opt/molten-vk/lib/libMoltenVK.dylib (compatibility version 1.0.0, current version 1.0.0)
> 	/System/Library/Frameworks/Metal.framework/Versions/A/Metal (compatibility version 1.0.0, current version 244.119.0)
> 	/usr/lib/libc++.1.dylib (compatibility version 1.0.0, current version 905.6.0)
> 	/System/Library/Frameworks/AppKit.framework/Versions/C/AppKit (compatibility version 45.0.0, current version 2022.44.149)
> 	/System/Library/Frameworks/CoreGraphics.framework/Versions/A/CoreGraphics (compatibility version 64.0.0, current version 1463.4.2)
> 	/System/Library/Frameworks/CoreServices.framework/Versions/A/CoreServices (compatibility version 1.0.0, current version 1122.33.0)
> 	/System/Library/Frameworks/Foundation.framework/Versions/C/Foundation (compatibility version 300.0.0, current version 1775.118.101)
> 	/usr/lib/libobjc.A.dylib (compatibility version 1.0.0, current version 228.0.0)
> ```

This is weird, on my side it is using relative. Which C++ compiler is this?

**Comment by lin-hitonami** [comment]
> > This doesn't seem to work... First, `libMoltenVK.dylib` is not copied to the package. Second, the path of `libMoltenVK.dylib` is still absolute. Here is the output of otool.
> > ```
> > (test38) lin@LindeMacBook-Pro core % otool -L taichi_core.so 
> > taichi_core.so:
> > 	@rpath/libtaichi_core.dylib (compatibility version 0.0.0, current version 0.0.0)
> > 	/System/Library/Frameworks/Cocoa.framework/Versions/A/Cocoa (compatibility version 1.0.0, current version 23.0.0)
> > 	/System/Library/Frameworks/IOKit.framework/Versions/A/IOKit (compatibility version 1.0.0, current version 275.0.0)
> > 	/System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation (compatibility version 150.0.0, current version 1775.118.101)
> > 	/usr/lib/libz.1.dylib (compatibility version 1.0.0, current version 1.2.11)
> > 	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1292.100.5)
> > 	/opt/homebrew/opt/molten-vk/lib/libMoltenVK.dylib (compatibility version 1.0.0, current version 1.0.0)
> > 	/System/Library/Frameworks/Metal.framework/Versions/A/Metal (compatibility version 1.0.0, current version 244.119.0)
> > 	/usr/lib/libc++.1.dylib (compatibility version 1.0.0, current version 905.6.0)
> > 	/System/Library/Frameworks/AppKit.framework/Versions/C/AppKit (compatibility version 45.0.0, current version 2022.44.149)
> > 	/System/Library/Frameworks/CoreGraphics.framework/Versions/A/CoreGraphics (compatibility version 64.0.0, current version 1463.4.2)
> > 	/System/Library/Frameworks/CoreServices.framework/Versions/A/CoreServices (compatibility version 1.0.0, current version 1122.33.0)
> > 	/System/Library/Frameworks/Foundation.framework/Versions/C/Foundation (compatibility version 300.0.0, current version 1775.118.101)
> > 	/usr/lib/libobjc.A.dylib (compatibility version 1.0.0, current version 228.0.0)
> > ```
> 
> This is weird, on my side it is using relative. Which C++ compiler is this?

I'm using clang++-11.

**Comment by bobcao3** [comment]
@lin-hitonami Can you try to use Clang++12 / 13 (the builtin compiler), so instead of setting CXX to clang++11, set -DCLANG_EXECUTABLE=clang++11

**Comment by lin-hitonami** [comment]
> @lin-hitonami Can you try to use Clang++12 / 13 (the builtin compiler), so instead of setting CXX to clang++11, set -DCLANG_EXECUTABLE=clang++11

It does not work either when I use the builtin clang++12...

**Comment by bobcao3** [comment]
Does not work

**Pull request closed without merging**
