### PR TITLE
Draft: [lang] Add reversed range for of taich kernel

### PR DESCRIPTION
**Pull request by weiyunfei**
Related issue = #4379

### CODE REVIEW

**Comment by strongoier** [comment]
Hi @weiyunfei. Thanks for contributing! Could you fix the compilation errors first?

**Comment by weiyunfei** [comment]
> Hi @weiyunfei. Thanks for contributing! Could you fix the compilation errors first?

Sorry for late reply, I fixed the compilation error in the statements test caused by my PR. If it does not work, I'll fix it this weekend.

**Comment by weiyunfei** [comment]
I've fixed the compilation errors in this PR, while I have no idea why the tests are not passed. Some of the cpp tests are failed with `subprocess.CalledProcessError` and some python tests are failed.
Meanwhile, I've checked other in-progressing pull requests, it seems that the number of python tests is not equal between my branch and theirs. Is it influenced by the python version?
Your kind help with this will be much appreciated.

**Comment by strongoier** [comment]
1. For those cpp tests, you may need to rebase from master.
2. The Python tests failed with the following message, which was caused by your modification:
```
2022-07-02T12:08:18.4787213Z E           Traceback (most recent call last):
2022-07-02T12:08:18.4787574Z E             File "C:\actions-runner\_work\taichi\taichi\venv\lib\site-packages\taichi-1.0.4-py3.7-win-amd64.egg\taichi\lang\ast\ast_transformer_utils.py", line 24, in __call__
2022-07-02T12:08:18.4787646Z E               return method(ctx, node)
2022-07-02T12:08:18.4788017Z E             File "C:\actions-runner\_work\taichi\taichi\venv\lib\site-packages\taichi-1.0.4-py3.7-win-amd64.egg\taichi\lang\ast\ast_transformer.py", line 1023, in build_For
2022-07-02T12:08:18.4788121Z E               return ASTTransformer.build_ndrange_for(ctx, node)
2022-07-02T12:08:18.4788479Z E             File "C:\actions-runner\_work\taichi\taichi\venv\lib\site-packages\taichi-1.0.4-py3.7-win-amd64.egg\taichi\lang\ast\ast_transformer.py", line 835, in build_ndrange_for
2022-07-02T12:08:18.4788542Z E               if begin > end:
2022-07-02T12:08:18.4788737Z E           UnboundLocalError: local variable 'begin' referenced before assignment
```
3. The number of Python tests can vary because a PR can add/remove some Python tests.

BTW I find that supporting reversed range for seems problematic - you cannot know whether `begin` is larger than `end` at compile time, and Python doesn't support it either. Sorry about my premature thoughts. Are you interested solely in solving this issue, or do you think contributing to other issues is also fine?

**Comment by weiyunfei** [comment]
Sorry for the late reply.  I'll keep track of this problem, perhaps I could solve it solely when I become more familar with taichi. Moreover, I'm going to contribute to taichi in the future.

**Pull request closed without merging**
