### PR TITLE
[gui] Move all ggui kernels to python by using taichi fields as staging buffers

### PR DESCRIPTION
**Pull request by AmesingFlank**
This PR moves all ggui kernels to python by using taichi fields as staging buffers. This removes the need for `ui_kernels.cpp/.ll/.bc` and allows the logic for future ggui backends to be less graphics-api-specific. 

On the C++ side, no more kernels needs to launched, only `memcpy` and `cuda_memcpy` are needed. In the future, these should be replaced by `device.memcpy()`.

The PR also fixed the bug where `set_image` behaves incorrectly when packed mode is enabled.

### CODE REVIEW

**Comment by bobcao3** [comment]
In theory, going from here, for backends without known interop or without an implemented interop, we can direct the taichi kernel outputs to an extarr and use host device copy like the old GUI, right?

**Review by bobcao3 — APPROVED** [review]
Clean and clear, looks great!

**Comment by AmesingFlank** [comment]
> In theory, going from here, for backends without known interop or without an implemented interop, we can direct the taichi kernel outputs to an extarr and use host device copy like the old GUI, right?

Yep. It should be quite straightforward to implement  [user input] -> [staging buffer] -> [np array] -> [actual gpu buffers].

**Review by k-ye — COMMENTED** [review]
Thank you! Random nit: could you help add the docstrings for the public APIs like `Canvas`, `Scene` and `Window`? :-)

**Pull request merged**
