### PR TITLE
[Doc] Fix example link in README.

### PR DESCRIPTION
**Pull request by egolearner**

### CODE REVIEW

**Review by ailzhang — APPROVED** [review]
Thanks a lot for the quick fix! 
Btw would you mind also help fixing the links in docs folder?

**Comment by ailzhang** [comment]
Hey @egolearner, would you mind signing the CLA above so that we can merge this? :D Thanks!

**Comment by ailzhang** [comment]
FYI other links have been fixed in https://github.com/taichi-dev/taichi/pull/3587 so this PR is ready to merge once CLA is signed :D

**Comment by yolo2themoon** [comment]
Could you please fix these lines by the way?

https://github.com/taichi-dev/taichi/blob/master/README.md?plain=1#L27
https://github.com/taichi-dev/taichi/blob/master/README.md?plain=1#L29
https://github.com/taichi-dev/taichi/blob/master/README.md?plain=1#L30

**Comment by egolearner** [comment]
> By the way, could you please fix these lines in README.md? ;)
> 
> https://github.com/taichi-dev/taichi/blob/master/README.md?plain=1#L27 https://github.com/taichi-dev/taichi/blob/master/README.md?plain=1#L29 https://github.com/taichi-dev/taichi/blob/master/README.md?plain=1#L30

Sure.

**Comment by egolearner** [comment]
> 

CLA assigned. :-)

**Comment by egolearner** [comment]
@ailzhang thanks

**Pull request merged**
