### PR TITLE
[Lang] Fix `ti.static(ti.grouped(ti.ndrange(...)))` syntax checker false positive

### PR DESCRIPTION
**Pull request by yuanming-hu**
This is a special case that we should let pass. A more systematic solution is to defer the checking to the stage when the AST generating script is executed.

Related issue = #https://github.com/taichi-dev/taichi_elements/issues/13

[[Click here for the format server]](http://kun.csail.mit.edu:31415/)

### CODE REVIEW

**Comment by yuanming-hu** [comment]
@xumingkuan Sorry for the brute-force treatment here. No rush to review it during the weekend.

Forgive me if I bypass your review - I'm just trying to have this in v0.5.10 releasing tonight so that people won't get a syntax error. We can have more discussions for a more systematic solution after this urgent issue is resolved.

**Comment by yuanming-hu** [comment]
I see. Thanks for understanding. I didn't realize this use case could be an issue during code review either. I'll merge this in once CI passed.

**Comment by xumingkuan** [comment]
Did it work in previous versions? I don't think I changed the behavior of `ti.static` for loops...

**Comment by yuanming-hu** [comment]
> Did it work in previous versions? I don't think I changed the behavior of `ti.static` for loops...

You mean the test I skipped? It's now throwing an `AssertionError` instead of `TaichiSyntaxError` after this PR. That's why I skip it.

**Comment by xumingkuan** [comment]
Oh I mean did `ti.static(ti.grouped(x))` work correctly in previous versions. I'm wondering why it gives `AssertionError` now.

**Comment by yuanming-hu** [comment]
> Oh I mean did `ti.static(ti.grouped(x))` work correctly in previous versions.

It doesn't work should not work. Taichi will throw an `AssertionError` before your refactoring, which is not as informative as your `TaichiSyntaxError`. I just changed it back to the old behavior.

I'm just letting `ti.static(ti.groupd(ti.ndrange()))` pass here.

**Comment by xumingkuan** [comment]
@yuanming-hu Shall we have a Skype chat about how to fix this now?

**Comment by yuanming-hu** [comment]
Sure!

**Comment by xumingkuan** [comment]
How to raise `TaichiSyntaxError` in the emitted code of transformer.py? It looks like `ti.TaichiSyntaxError` is defined in transformer.py and I cannot use it in the emitted code.

**Comment by yuanming-hu** [comment]
Oh please move `TaichiSyntaxError` outside and export it, so that you can use `ti.TaichiSyntaxError`.

**Comment by xumingkuan** [comment]
Which file should `TaichiSyntaxError` belong to?

**Comment by yuanming-hu** [comment]
> Which file should `TaichiSyntaxError` belong to?

Good question - let's create `taichi/python/taichi/lang/exception.py` to hold these.

**Pull request merged**
