### PR TITLE
Add position base fluid 2D to examples

### PR DESCRIPTION
**Pull request by k-ye**
A gif is worth a thousands words ;)
output

### CODE REVIEW

**Comment by yuanming-hu** [comment]
amazing!

**Comment by yuanming-hu** [comment]
I had a lot of fun playing with it and made subtle improvements:
https://github.com/taichi-dev/taichi/blob/7a6d076ece11e3fae9b50dd3dd098ad6dd735bee/examples/pbf2d.py#L127
https://github.com/taichi-dev/taichi/blob/7a6d076ece11e3fae9b50dd3dd098ad6dd735bee/examples/pbf2d.py#L176
https://github.com/taichi-dev/taichi/blob/7a6d076ece11e3fae9b50dd3dd098ad6dd735bee/examples/pbf2d.py#L187

**Comment by k-ye** [comment]
Thank you!!

**Comment by masahi** [comment]
hi @k-ye @yuanming-hu, is this example supposed to work with the latest master? I got mpm88.py and other examples working on cuda, but for pbf2d.py I get segfault below. 

My gpu is GTX 1070ti. I confirmed that `ti test` works with cuda enabled except test_svd.py. Also tried on cpu, but got different error.

```
[I 02/08/20 07:28:11.378] [taichi_llvm_context.cpp:TaichiLLVMContext@57] Creating llvm context for arch: cuda
[T 02/08/20 07:28:11.424] [taichi_llvm_context.cpp:compile_runtime_bitcode@110] Compiling runtime module bitcode...
[I 02/08/20 07:28:11.750] [/home/masa/projects/graphics/taichi/python/taichi/lang/kernel.py:materialize@180] Compiling kernel init_c24_0_...
[W 02/08/20 07:28:11.753] [type_check.cpp:visit@131] Global store may lose precision: float32x1 <- float64x1, at
[W 02/08/20 07:28:11.753] [type_check.cpp:visit@131] Global store may lose precision: float32x1 <- float64x1, at
[W 02/08/20 07:28:11.753] [type_check.cpp:visit@131] Global store may lose precision: float32x1 <- float64x1, at
[W 02/08/20 07:28:11.753] [type_check.cpp:visit@131] Global store may lose precision: float32x1 <- float64x1, at
[I 02/08/20 07:28:11.819] [llvm_jit_ptx.cpp:compile@174] PTX size: 2.17KB
[I 02/08/20 07:28:11.821] [/home/masa/projects/graphics/taichi/python/taichi/lang/kernel.py:materialize@180] Compiling kernel init2_c26_0_...
[I 02/08/20 07:28:11.880] [llvm_jit_ptx.cpp:compile@174] PTX size: 0.76KB
boundary=(80.0, 40.0) grid=(32, 16) cell_size=2.51
[I 02/08/20 07:28:11.882] [/home/masa/projects/graphics/taichi/python/taichi/lang/kernel.py:materialize@180] Compiling kernel move_board_c6_0_...
[I 02/08/20 07:28:11.958] [llvm_jit_ptx.cpp:compile@174] PTX size: 5.05KB
[I 02/08/20 07:28:11.959] [/home/masa/projects/graphics/taichi/python/taichi/lang/kernel.py:materialize@180] Compiling kernel blit_buffers_c4_0_...
[I 02/08/20 07:28:12.026] [llvm_jit_ptx.cpp:compile@174] PTX size: 1.71KB
[I 02/08/20 07:28:12.027] [/home/masa/projects/graphics/taichi/python/taichi/lang/kernel.py:materialize@180] Compiling kernel apply_gravity_within_boundary_c8_0_...
[I 02/08/20 07:28:12.114] [llvm_jit_ptx.cpp:compile@174] PTX size: 6.78KB
[I 02/08/20 07:28:12.115] [/home/masa/projects/graphics/taichi/python/taichi/lang/kernel.py:materialize@180] Compiling kernel fill_tensor_c28_0_...
[I 02/08/20 07:28:12.181] [llvm_jit_ptx.cpp:compile@174] PTX size: 1.35KB
[I 02/08/20 07:28:12.182] [/home/masa/projects/graphics/taichi/python/taichi/lang/kernel.py:materialize@180] Compiling kernel fill_tensor_c28_1_...
[I 02/08/20 07:28:12.248] [llvm_jit_ptx.cpp:compile@174] PTX size: 1.83KB
[I 02/08/20 07:28:12.249] [/home/masa/projects/graphics/taichi/python/taichi/lang/kernel.py:materialize@180] Compiling kernel update_grid_c12_0_...
[I 02/08/20 07:28:12.320] [llvm_jit_ptx.cpp:compile@174] PTX size: 2.20KB
[I 02/08/20 07:28:12.321] [/home/masa/projects/graphics/taichi/python/taichi/lang/kernel.py:materialize@180] Compiling kernel find_particle_neighbors_c14_0_...
[I 02/08/20 07:28:12.527] [llvm_jit_ptx.cpp:compile@174] PTX size: 27.42KB
[I 02/08/20 07:28:12.528] [/home/masa/projects/graphics/taichi/python/taichi/lang/kernel.py:materialize@180] Compiling kernel compute_lambdas_c16_0_...
[I 02/08/20 07:28:12.614] [llvm_jit_ptx.cpp:compile@174] PTX size: 4.82KB
[I 02/08/20 07:28:12.615] [/home/masa/projects/graphics/taichi/python/taichi/lang/kernel.py:materialize@180] Compiling kernel compute_position_deltas_c18_0_...
[I 02/08/20 07:28:12.704] [llvm_jit_ptx.cpp:compile@174] PTX size: 4.53KB
[I 02/08/20 07:28:12.706] [/home/masa/projects/graphics/taichi/python/taichi/lang/kernel.py:materialize@180] Compiling kernel apply_position_deltas_c20_0_...
[I 02/08/20 07:28:12.771] [llvm_jit_ptx.cpp:compile@174] PTX size: 1.90KB
[I 02/08/20 07:28:12.772] [/home/masa/projects/graphics/taichi/python/taichi/lang/kernel.py:materialize@180] Compiling kernel confine_to_boundary_c10_0_...
[I 02/08/20 07:28:12.853] [llvm_jit_ptx.cpp:compile@174] PTX size: 6.53KB
[I 02/08/20 07:28:12.854] [/home/masa/projects/graphics/taichi/python/taichi/lang/kernel.py:materialize@180] Compiling kernel update_velocities_c22_0_...
[I 02/08/20 07:28:12.921] [llvm_jit_ptx.cpp:compile@174] PTX size: 1.94KB
[I 02/08/20 07:28:12.923] [/home/masa/projects/graphics/taichi/python/taichi/lang/kernel.py:materialize@180] Compiling kernel matrix_to_ext_arr_c34_0_...
[I 02/08/20 07:28:12.992] [llvm_jit_ptx.cpp:compile@174] PTX size: 2.14KB
[E 02/08/20 07:28:13.031] Received signal 11 (Segmentation fault)
```

**Comment by yuanming-hu** [comment]
It also fails stochastically on CUDA on my end.  I spent some time debugging yet found no clear clue. Not sure if it is a bug in the script or Taichi. Will take a look next week, after the debug mode (which checks invalid memory accesses in taichi kernels) is fully done.

**Comment by masahi** [comment]
indeed, I tried multiple times and also got random failures. I got different message below.

```
...
corrupted double-linked list
[E 02/08/20 09:11:26.431] Received signal 6 (Aborted)
```

**Comment by k-ye** [comment]
hmm, sorry i actually don't have a CUD environment. The script only used `dense` nodes so it should not involve any memory allocation after init... One thing I can try is to merge all those small `ti.kernel`s into a big one.

**Comment by k-ye** [comment]
So one index-out-of-range bug I found:

https://github.com/taichi-dev/taichi/blob/9bbc28db802d6eb90250d83016525d3244e41e75/examples/pbf2d.py#L178-L179

And `grid2particles` can hold a maximum of 100 particles, see

https://github.com/taichi-dev/taichi/blob/9bbc28db802d6eb90250d83016525d3244e41e75/examples/pbf2d.py#L72

However, i wonder if this is the culprit for two things

* the PBF script prints out the maximum number of particles per grid as it runs, and i always see that number to be around 30, which is far from reaching 100.
* As I searched `corrupted double-linked list`, it seems to point to `malloc` issues [example SO post](https://stackoverflow.com/questions/14897157/what-does-corrupted-double-linked-list-mean)

**Comment by yuanming-hu** [comment]
Yeah, I don't think it's going out of bound. Sometimes it crashes at the very beginning. It might be a bug in Taichi. Let's see what happens after I implement debug mode, where every tensor access will be guarded by a range check.

**Pull request merged**
