### PR TITLE
[bug] Fix postsubmit

### PR DESCRIPTION
**Pull request by lin-hitonami**
Related issue = #

### CODE REVIEW

**Review by ailzhang — COMMENTED** [review]
Commit is messed up with dev_install ;P

**Comment by lin-hitonami** [comment]
Seems that misc/code_format.py auto-formatted the docs...

**Review by ailzhang — APPROVED** [review]

**Comment by ailzhang** [comment]
Hmmm then it might indicate that our dev_install does need a format... weird... let me try this...

**Comment by ailzhang** [comment]
Alright, let's just include the format changes here. Something must be wrong with the doc-only presubmit workflow...

**Review by strongoier — APPROVED** [review]
Thanks!

**Comment by ailzhang** [comment]
One CPU test passed, merging to unblock master,

**Pull request merged**
