### PR TITLE
[ir] Let GetElementExpression&Statement support index list

### PR DESCRIPTION
**Pull request by lin-hitonami**
Issue: #6983

### CODE REVIEW

**Comment by bobcao3** [comment]
IIRC there was a ExpressionStatement wrapper or something (turns a rvalue into a lvalue), should we use that instead of duplicating the statements?

**Comment by lin-hitonami** [comment]
> IIRC there was a ExpressionStatement wrapper or something (turns a rvalue into a lvalue), should we use that instead of duplicating the statements?

I've never heard of it. Where is it?

**Comment by bobcao3** [comment]
There's a FrontendExprStmt. Is the expression used only in frontend? (I would assume so)

**Comment by lin-hitonami** [comment]
> There's a FrontendExprStmt. Is the expression used only in frontend? (I would assume so)

The `Frontend***Stmt`s are frontend statements that receive `Expr`s as arguments while other statements that do not start with `Frontend` receive `Stmt`s as arguments. The `Frontend***Stmt`s are replaced by other statements in the `lower_ast` pass, and they do no reach the codegen.

`FrontendExprStmt` adds an `Expr` to the IR without needing a `Stmt` containing it. The `FrontendExprStmt` is replaced by the lowered `Stmt` of the `Expr` in the `lower_ast` pass. I don't think this can solve the problem that we must have an `***Expr` or an `Frontend***Stmt` for frontend and a `***Stmt` for backend...

**Comment by lin-hitonami** [comment]
Reopened with ghstack. Closing this one. Let's discuss in https://github.com/taichi-dev/taichi/pull/7026

**Pull request closed without merging**
