### PR TITLE
[example] Add real func ver of taichi_ngp

### PR DESCRIPTION
**Pull request by lin-hitonami**
### Walkthrough

Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #8221
* #8220

### CODE REVIEW

**Review by neozhaoliang — APPROVED** [review]
LGTM!

**Comment by taichi-gardener** [comment]
ghstack bot failed: PR #8221 check-run `Build and Test (Apple M1) (macos-latest, 3.8)`'s status `None` is not success!

**Pull request closed without merging**
