### PR TITLE
Fix __rpow__ and related tests

### PR DESCRIPTION
**Pull request by archibate**

### CODE REVIEW

**Comment by yuanming-hu** [comment]
According to Travis it seems to me that Taichi is computing `0.234 ** 0.4 = 0.5593534781830355` instead of `0.4 ** 0.234=0.807015800773769`?

**Comment by archibate** [comment]
`ti test pow` passed. Problem in `make_adjoint.cpp`. grad intergration wrong(?)

**Comment by yuanming-hu** [comment]
It seems that `Expr.__rpow__` should be
```python3
  def __rpow__(self, power, modulo=None):
    return Expr(power).__pow__(self, modulo)
```

instead of 

```python3
  def __rpow__(self, power, modulo=None):
    return self.__pow__(Expr(power), self)
```

:-) Let's fix this in this PR as well. I just now changed the title of this PR.

**Comment by yuanming-hu** [comment]
Awesome!!!

**Pull request merged**
