### PR TITLE
[misc] add game_of_life example

### PR DESCRIPTION
**Pull request by archibate**
Related issue = #... (if any)

[[Click here for the format server]](http://kun.csail.mit.edu:31415/)

### CODE REVIEW

**Comment by yuanming-hu** [comment]
It's sad that John Conway, the mathematician who invented the *Game of Life*, died of COVID-19 yesterday :-( @archibate @k-ye @xumingkuan

**Comment by k-ye** [comment]
That's so sad.. I saw the news but didn't know that game of life was part of his works ☹️

**Comment by archibate** [comment]
I see, it sad to know the brilliant brain was gone from the world... Be careful, the situation in China is getting much better now, and I really wish you guy's could survive this hard time before dawn!

**Comment by xumingkuan** [comment]
It's so sad... I didn't notice this PR before seeing the news, and I thought this was for a memorial of the genius.

**Pull request merged**
