### PR TITLE
[Lang] Fix pylint rule W0621

### PR DESCRIPTION
**Pull request by ZonePG**
Related issue = #3151

### CODE REVIEW

**Comment by ZonePG** [comment]
In most cases, I modify the parameter and add an underscore as a prefix(`func`->`_func`), I am not sure whether it meets the naming convention. Or add `pylint: disable=W0621` comments directly

**Comment by ZonePG** [comment]
@sjwsl  Sorry that I did not compile and test on my m1 machine before, so I revised the compilation problem through repeated commits. 
Now I have set up a development environment on my m1 mac, and there is no problem with the compilation and testing. Please check my pr, thx.
I will learn and use taichi in the future and contribute to taichi in the future.

**Comment by ZonePG** [comment]
hoping that be able to contribute to taichi in the future~.

**Comment by sjwsl** [comment]
> @sjwsl Sorry that I did not compile and test on my m1 machine before, so I revised the compilation problem through repeated commits. Now I have set up a development environment on my m1 mac, and there is no problem with the compilation and testing. Please check my pr, thx. I will learn and use taichi in the future and contribute to taichi in the future.

Never mind~ We'll review and review your pr after passing CI. Thanks for your contribution!

**Review by sjwsl — COMMENTED** [review]
LGTM! Thanks :)

**Review by sjwsl — APPROVED** [review]

**Pull request merged**
