### PR TITLE
[cc] [refactor] Re-open automatically detect available compiler (clang or gcc)

### PR DESCRIPTION
**Pull request by archibate**
Related issue = reopen #2037

[[Click here for the format server]](http://kun.csail.mit.edu:31415/)

----
The option `-Wc11-c2x-compat`, seems not supported on old version of gcc, making Jenkins. Let's remove `-Wc90-c99-compat` too for compatibility. It also remind you to upgrade the gcc on Jenkins, if possible.

### CODE REVIEW

**Review by k-ye — COMMENTED** [review]
Sorry, what is being fixed here?

**Comment by archibate** [comment]
> Sorry, what is being fixed here?

The changed part is:
```diff
- gcc -Wc90-c99-compat -Wc11-c2x-compat
+ gcc
```

The option `-Wc11-c2x-compat` is not supported by the `gcc` verion on Jenkins that caused the error. So I removed both `-Wc90-c99-compat` and `-Wc11-c2x-compat` for best compatibility, leaving only `gcc` as `cc_compile_cmd`.

**Review by k-ye — COMMENTED** [review]
LGTM, but CI is broken?

**Comment by archibate** [comment]
```
 /home/runner/work/taichi/taichi/taichi/backends/cc/codegen_cc.cpp:339:28: error: use of undeclared identifier 'data_type_short_name'; did you mean 'data_type_name'?
        auto lhs_dt_name = data_type_short_name(bin->lhs->element_type());
```

However the C backend has been long using `Ti_i32` in it's runtime C code so it would be hard to switch all of them to `Ti_int32` in this PR. I added `data_type_short_name` to `namespace cccp` to make it work for now.

**Comment by archibate** [comment]
Also, I got this error while importing Taichi:
```
Traceback (most recent call last):
  File "/home/bate/Develop/taichi/bin/ti", line 3, in <module>
    import taichi
  File "/home/bate/Develop/taichi/python/taichi/__init__.py", line 1, in <module>
    from .core import *
  File "/home/bate/Develop/taichi/python/taichi/core/__init__.py", line 1, in <module>
    from .util import *
  File "/home/bate/Develop/taichi/python/taichi/core/util.py", line 218, in <module>
    raise e from None
  File "/home/bate/Develop/taichi/python/taichi/core/util.py", line 209, in <module>
    import_ti_core(tmp_dir)
  File "/home/bate/Develop/taichi/python/taichi/core/util.py", line 46, in import_ti_core
    raise e from None
  File "/home/bate/Develop/taichi/python/taichi/core/util.py", line 34, in import_ti_core
    import taichi_core as core
ImportError: /tmp/taichi-4f5nou_x/taichi_core.so: undefined symbol: _ZN6taichi4lang11CodeGenLLVM5visitEPNS0_18BitStructStoreStmtE
```

**Comment by TH3CHARLie** [comment]
> Also, I got this error while importing Taichi:
> 
> ```
> Traceback (most recent call last):
>   File "/home/bate/Develop/taichi/bin/ti", line 3, in <module>
>     import taichi
>   File "/home/bate/Develop/taichi/python/taichi/__init__.py", line 1, in <module>
>     from .core import *
>   File "/home/bate/Develop/taichi/python/taichi/core/__init__.py", line 1, in <module>
>     from .util import *
>   File "/home/bate/Develop/taichi/python/taichi/core/util.py", line 218, in <module>
>     raise e from None
>   File "/home/bate/Develop/taichi/python/taichi/core/util.py", line 209, in <module>
>     import_ti_core(tmp_dir)
>   File "/home/bate/Develop/taichi/python/taichi/core/util.py", line 46, in import_ti_core
>     raise e from None
>   File "/home/bate/Develop/taichi/python/taichi/core/util.py", line 34, in import_ti_core
>     import taichi_core as core
> ImportError: /tmp/taichi-4f5nou_x/taichi_core.so: undefined symbol: _ZN6taichi4lang11CodeGenLLVM5visitEPNS0_18BitStructStoreStmtE
> ```

Try rerun CMake? As BitStructStoreStmt was added recently with some new files.

**Comment by feisuzhu** [comment]
Closing ancient PR

**Pull request closed without merging**
