### PR TITLE
[refactor] Removed all occurrences of print_preprocessed and print_ast, which is no longer used. #3748

### LINKED ISSUE #3748: Remove `print_preprocessed` which is no longer used.
After the ast generator refactor `print_preprocessed` is no longer used(replaced by `print_preprocessed_ir`). We should remove it as well as `print_ast` here. https://github.com/taichi-dev/taichi/blob/master/python/taichi/lang/ast/ast_transformer_utils.py#L199-L204 
This task should be as simple as removing all of `print_preprocessed` and `print_ast`s. 
cc: @lin-hitonami

### PR DESCRIPTION
**Pull request by JawadurRahman**
Related issue = close #3748 
[Refactor]

### CODE REVIEW

**Comment by ailzhang** [comment]
Hey @JawadurRahman would you mind also fixing the the pylint errors? Thanks!
```
python/taichi/lang/ast/ast_transformer_utils.py:6:0: W0611: Unused import astor (unused-import)
python/taichi/lang/ast/ast_transformer_utils.py:7:0: W0611: Unused info imported from taichi._logging (unused-import)
python/taichi/lang/ast/ast_transformer_utils.py:8:0: W0611: Unused impl imported from taichi.lang (unused-import)
```
GPU test failure is network related so don't worry about it (rerunning should be fine ;)

**Comment by strongoier** [comment]
Hi @JawadurRahman. Thanks for your contribution! Please let us know if you are still interested in finishing this. If not, we can give this chance to other contributors :-)

**Comment by JawadurRahman** [comment]
You can give this issue to someone else.

**Pull request closed without merging**
