### PR TITLE
[Lang] Add data_handle property to Ndarray

### LINKED ISSUE #2942: `ti.get_addr` is not working for `ti.ndarray`
```py
a = ti.ndarray(dtype=ti.f32, shape=(3, 3))
ti.get_addr(a, [0, 0]) # error
```
Traceback:
```
Traceback (most recent call last):
  File "utils.py", line 95, in <module>
    get_field_info(a)
  File "utils.py", line 82, in get_field_info
    info.data = get_field_addr(field)
  File "utils.py", line 40, in get_field_addr
    addr = get_field_addr_ND(x)
  File "/home/ljcc/.local/lib/python3.8/site-packages/taichi/lang/kernel_impl.py", line 671, in wrapped
    return primal(*args, **kwargs)
  File "/home/ljcc/.local/lib/python3.8/site-packages/taichi/lang/kernel_impl.py", line 598, in __call__
    key = self.ensure_compiled(*args)
  File "/home/ljcc/.local/lib/python3.8/site-packages/taichi/lang/kernel_impl.py", line 589, in ensure_compiled
    self.materialize(key=key, args=args, arg_features=arg_features)
  File "/home/ljcc/.local/lib/python3.8/site-packages/taichi/lang/kernel_impl.py", line 455, in materialize
    taichi_kernel = taichi_kernel.define(taichi_ast_generator)
  File "/home/ljcc/.local/lib/python3.8/site-packages/taichi/lang/kernel_impl.py", line 450, in taichi_ast_generator
    compiled()
  File "utils.py", line 31, in get_field_addr_ND
    return ti.get_addr(x,[0 for _ in x.shape])
  File "/home/ljcc/.local/lib/python3.8/site-packages/taichi/lang/ops.py", line 962, in get_addr
    return Expr(_ti_core.expr_get_addr(f.snode.ptr, make_expr_group(indices)))
AttributeError: 'ScalarNdarray' object has no attribute 'snode'
```

### PR DESCRIPTION
**Pull request by strongoier**
Related issue = close #2942

### CODE REVIEW

**Review by ailzhang — APPROVED** [review]
LGTM!

**Review by k-ye — APPROVED** [review]
My bad. Better call it `data_handle`, given that we might need to expose https://github.com/taichi-dev/taichi/blob/fab7c281401f2e6316dc68a53eaa2702b249ecdc/taichi/backends/device.h#L42-L55 in the future

**Comment by strongoier** [comment]
> My bad. Better call it `data_handle`, given that we might need to expose
> 
> https://github.com/taichi-dev/taichi/blob/fab7c281401f2e6316dc68a53eaa2702b249ecdc/taichi/backends/device.h#L42-L55
> in the future

I'll change the name but keep the docstring unchanged for now because it currently returns simply a pointer.

**Review by ljcc0930 — APPROVED** [review]
LGTM!

**Pull request merged**
