### PR TITLE
[metal] Pass back return values via result_buffer

### PR DESCRIPTION
**Pull request by k-ye**
This allows us to decouple the return value from `Context`.

Related issue = #N/A

[[Click here for the format server]](http://kun.csail.mit.edu:31415/)

----

### CODE REVIEW

**Comment by yuanming-hu** [comment]
> The code LGTM but I don't feel like the `result_buffer`.. What's the downside of reusing `args[0]` as return value? We can 8 return value as well as 8 arguments by simply reuse the `ctx->args`, which sounds symmetric to me.

We are on our way to make `Context` read-only and remove its coupling with `Program`. This is decided design.

**Comment by archibate** [comment]
So we need two buffer `rets` and `args`, one write-only and one read-only?

**Comment by yuanming-hu** [comment]
> So we need two buffer `rets` and `args`, one write-only and one read-only?

Yes, `Context` stores the arguments, and we are working on a standardized `result_buffer` across all backends that stores return values, error code, error messages, and print information.

**Comment by archibate** [comment]
> print

I immediately approved your idea after hearing this word, SGTM now!

**Pull request merged**
