### PR TITLE
[Lang] Add W0101 rule for pylint

### PR DESCRIPTION
**Pull request by Lyken17**
Related issue  #3151. This is a PR to add W0101 rule for the pylint.

### CODE REVIEW

**Review by sjwsl — APPROVED** [review]
LGTM, thanks!

**Comment by Lyken17** [comment]
Glad to be a taichi contributor 🎉!

**Comment by Lyken17** [comment]
One more question, the `/format` command in issue looks magic. Where can I find related examples / referneces if I want to intergrate an similar one as this?

**Comment by strongoier** [comment]
> One more question, the `/format` command in issue looks magic. Where can I find related examples / referneces if I want to intergrate an similar one as this?

@Leonz5288 Could you provide some guidance?

**Comment by sjwsl** [comment]
> One more question, the `/format` command in issue looks magic. Where can I find related examples / referneces if I want to intergrate an similar one as this?

As you can see here

https://github.com/taichi-dev/taichi/blob/00b66a8c633cb2e71e7c76ed0473c9cfb5dc90a5/.github/workflows/issue_comment.yml#L15

The real process is defined in another private repository. FYI [This](https://github.com/peter-evans/slash-command-dispatc) is the utility we use to define slash commands. And [This](https://github.com/davidtvs/pytorch-lr-finder/tree/acc5e7ee7711a460bf3e1cc5c5f05575ba1e1b4b/.github/workflows) may serve as a reference for you.

**Pull request merged**
