### PR TITLE
[bug] Fix name collision in ti.dataclass

### LINKED ISSUE #6652: Two`ti.dataclass` member/method name collision
```python
import taichi as ti

@ti.dataclass
class foo:
    zoo: ti.f32

@ti.dataclass
class bar:
    @ti.func
    def zoo(self):
        return 0

ti.init()
foo() # instantiate struct with zoo as member first
bar() # then instantiate struct with zoo as method
```
```
[Taichi] version 1.2.1, llvm 10.0.0, commit 12ab828a, win, python 3.10.6
[Taichi] Starting on arch=x64
[W 11/18/22 02:45:47.215 7540] [C:/Users/Administrator/actions-runner/_work/taichi/taichi/taichi/runtime/llvm/llvm_offline_cache.cpp:load_meta_data@138] Lock C:/taichi_cache/ticache/llvm/metadata.lock failed
Traceback (most recent call last):
  File "C:\Users\...\code\ray_tracing\test.py", line 15, in <module>
    bar() # then instantiate struct with method
  File "C:\Users\...\mamba\envs\taichi\lib\site-packages\taichi\lang\struct.py", line 682, in __call__
    struct = self.cast(entries)
  File "C:\Users\...\mamba\envs\taichi\lib\site-packages\taichi\lang\struct.py", line 703, in cast
    return Struct(entries)
  File "C:\Users\...\mamba\envs\taichi\lib\site-packages\taichi\lang\struct.py", line 57, in __init__
    self._register_methods()
  File "C:\Users\...\mamba\envs\taichi\lib\site-packages\taichi\lang\struct.py", line 108, in _register_methods
  File "C:\Users\...\mamba\envs\taichi\lib\site-packages\taichi\lang\struct.py", line 57, in __init__
    self._register_methods()
  File "C:\Users\...\mamba\envs\taichi\lib\site-packages\taichi\lang\struct.py", line 108, in _register_methods
    setattr(self, name, MethodType(method, self))
  File "C:\Users\...\mamba\envs\taichi\lib\site-packages\taichi\lang\util.py", line 297, in wrapped
    return func(*args, **kwargs)
  File "C:\Users\...\mamba\envs\taichi\lib\site-packages\taichi\lang\struct.py", line 152, in setter
    self[key] = value
  File "C:\Users\...\mamba\envs\taichi\lib\site-packages\taichi\lang\struct.py", line 117, in __setitem__
    if isinstance(self.entries[key], SNodeHostAccess):
KeyError: 'zoo'
[W 11/18/22 02:49:30.911 18576] [taichi/util/offline_cache.h:run@185] Lock C:/taichi_cache/ticache/llvm/metadata.lock failed
```

### PR DESCRIPTION
**Pull request by strongoier**
Issue: fix #6652

### Brief Summary

Properties should be added to a certain `Struct` instance instead of the `Struct` class itself.

### CODE REVIEW

**Review by ailzhang — APPROVED** [review]
Thanks!

**Comment by YouJiacheng** [comment]
Use `__getattr__` and `__setattr__` might be a better choice than create a new class for each instance.
And that will break user's code like (fortunately, taichi use `isinstance` internally)
```python
foo = ti.Struct(...)
if type(foo) is ti.Struct:
    # do something
    pass
```
Use `__getattr__` and `__setattr__` can remove boilerplates `_make_getter` and `_make_setter` as well. (BTW, why setter requires python scope while `__setitem__` doesn't?)

**Comment by strongoier** [comment]
Sounds good! @YouJiacheng Are you interested in sending a PR for this?

> (BTW, why setter requires python scope while __setitem__ doesn't?)

Because in taichi scope `__setitem__` will never be called. The assignment will be handled by the AST transformer.

**Comment by YouJiacheng** [comment]
Hmmm, IIUC attribute assignment will be handled by the AST transformer as well. I will send a PR for this after my final exam(2023.1.4).

**Pull request merged**
