### PR TITLE
[GUI] Use native resolution (client scaling) on WIN32

### PR DESCRIPTION
**Pull request by bobcao3**
Related issue = #2316

### CODE REVIEW

**Comment by bobcao3** [comment]
Two of the commits are included accidentally. The actual change is the one-liner in commit 23efb42. This PR probably needs some sanitation.

**Comment by k-ye** [comment]
Thank you for improving the GUI! As you've pointed out, this PR has a large overlap with #2315, could you separate the two pls :-) ?

**Review by k-ye — APPROVED** [review]
LGTM, thanks!

**Comment by k-ye** [comment]
Some user reported that Taichi no longer worked on their Win7 since https://github.com/taichi-dev/taichi/releases/tag/v0.7.19. 

```
ImportError: DLL load failed while importing taichi_core
```

I took a look and this PR seems to be the most suspicious one. Could you help take a look whether this change has introduced  some new DLL dependency? Thanks!

**Comment by bobcao3** [comment]
I just checked and it seems that this DPI awareness mode only exists post windows 8.1. This might need some detection scheme, but I'm not sure whether this can be a runtime variant or it must be compile time.

**Comment by bobcao3** [comment]
Ref https://docs.microsoft.com/en-us/windows/win32/hidpi/high-dpi-desktop-application-development-on-windows

**Comment by k-ye** [comment]
Thanks. Can we use https://docs.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-setprocessdpiaware?redirectedfrom=MSDN for Win7 compatibility?

**Comment by bobcao3** [comment]
#2450

**Pull request merged**
