### PR TITLE
[lang] [test] Fixed logical operation on numeric values and vectors

### PR DESCRIPTION
**Pull request by listerily**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #8034
* #8026
* #8021
* #8029
* #8019
* #8018
* #8008

### CODE REVIEW

**Review by lin-hitonami — CHANGES_REQUESTED** [review]
We shouldn't support logical operations on real types.

**Comment by listerily** [comment]
> We shouldn't support logical operations on real types.

Updated

**Review by lin-hitonami — APPROVED** [review]
LGTM

**Pull request merged**
