### PR TITLE
[Example] Add mgpcg and reflection ehanced stable fluid

### PR DESCRIPTION
**Pull request by erizmr**
Related issue = #
Update the current naive Jacobi based stable fluid with MGPCG and reflection, GGUI is also an option for visualization.

### CODE REVIEW

**Comment by k-ye** [comment]
Awesome! but this is probably too huge to serve as a basic example. It would be better to place this in https://github.com/taichi-dev/advanced_examples :-)

**Comment by erizmr** [comment]
I think maybe I can try to reuse the `mgpcg_advanced.py` in the `examples/algorithm` to make a minimal version for this file (limit the number of lines comparable to the original `stable_fluid.py`). How does this sound to you? :)

**Comment by k-ye** [comment]
> I think maybe I can try to reuse the `mgpcg_advanced.py` in the `examples/algorithm` to make a minimal version for this file (limit the number of lines comparable to the original `stable_fluid.py`). How does this sound to you? :)

We likely will move `mgpcg_advanced.py` to advanced_examples as well :rofl:

**Comment by erizmr** [comment]
Good to know that.🤣 Then let's put them in the advanced_examples.

**Pull request closed without merging**
