### PR TITLE
[lang] [bug] Add @ti.pyfunc for functions that work in both Taichi and Python-scope, fix matrix methods

### LINKED ISSUE #1329: [Bug] [IR] random() is not an idempotent stmt and cannot be assigned multiple times.
**Describe the bug**

I found this when debugging https://github.com/taichi-dev/taichi/pull/1188#issuecomment-649510574

It basically boils down to this:

```py
import taichi as ti

ti.init(arch=ti.x64, print_ir=True)

@ti.kernel
def foo():
  a = ti.Vector([ti.random(), 2.3]).normalized()
  print(a)

foo()
```

Here's the generated IR:

```
    <f32 x1> $1 = const [1.0]
    <f32 x1> $2 = rand()  <-- !
    <f32 x1> $3 = mul $2 $2
    <f32 x1> $4 = const [2.3]
    <f32 x1> $5 = const [5.29]
    <f32 x1> $6 = add $3 $5
    <f32 x1> $7 = sqrt $6
    <f32 x1> $8 = div $1 $7
    <f32 x1> $9 = rand()  <-- !
    <f32 x1> $10 = mul $8 $9
    <f32 x1> $11 = rand()  <-- !
    <f32 x1> $12 = mul $11 $11
    <f32 x1> $13 = add $12 $5
    <f32 x1> $14 = sqrt $13
    <f32 x1> $15 = div $1 $14
    <f32 x1> $16 = mul $15 $4
    print "[", $10, ", ", $16, "]"
```

As we can see, `rand()` appeared three times in the IR. The correct way will be to assign `$2` to `$9` and `$11`.

### PR DESCRIPTION
**Pull request by archibate**
Related issue = close #1329

[[Click here for the format server]](http://kun.csail.mit.edu:31415/)

----
Btw, I found a bug in ti.static... the contents inside is still translated as Taichi-scope.

### CODE REVIEW

**Comment by archibate** [comment]
Hello? If no reaction, I can easily make this PR a large changeset.

**Comment by k-ye** [comment]
Thanks. This PR does make `cornell_box` and `mpm_lagrangian_forces` work again since #1188. IIUC, this PR turns several Matrix operations into a `ti.func`, so that the variables on the caller and the callee sides cannot be shared --> no SSA violation.

According to https://github.com/taichi-dev/taichi/issues/1329#issuecomment-649898062

> I think we should use @ti.func for Matrix.normalized instead of @taichi_scope.

I wonder all of this time, were we just lucky to have these matrix operations working in an SSA-compliant way (or at least we bear SSA in mind so as not to violate it), until #1188 ?

If the answer is yes, then this is an actual fix of #1329 , and we should probably decorate all these matrix ops with `@ti.func`? But otherwise, the SSA violation problem still exists. So there's still a possibility for the codegen to produce a non-SSA-compliant AST...

---

Another thing is that, I don't think we should add `@ti.pyfunc`. We spent some efforts converging `ti.classfunc` and `ti.func` into one to keep the API simple. Adding a new keyword just defeats the purpose. A slightly more cumbersome way is to write

```py
@ti.python_callable
@ti.func
def foo():
  ...
```

But then it really starts to look like `@python_scope`...

**Comment by yuanming-hu** [comment]
> I wonder all of this time, were we just lucky to have these matrix operations working in an SSA-compliant way (or at least we bear SSA in mind so as not to violate it), until #1188 ?

If I understand correctly, your question is "why don't we need an AST transform on the matrix functions"? The answer is that in the past we have been constructing `Expr`s (instead of statements) in these matrix member functions. This leads to certain recomputation (which are mostly eliminated via optimization passes). There are exceptions, e.g. https://github.com/taichi-dev/taichi/blob/cc0a6ca55528684ba88d32d684b4f3e5256f85a5/python/taichi/lang/matrix.py#L410 where we use a local variable (which means a alloca plus some load/stores) to cache the intermediate result.

**Comment by archibate** [comment]
So, is my attempt of translating matrix ops into funcs correct?

> I don't think we should add `@ti.pyfunc`

I understand you are concern about introducing complicity to API design, but we have to, for now, to distinguish what func can be called from Python-scope. We may merge `pyfunc` with `func` when the base is more complete, like `classfunc` was, iapr.

**Comment by k-ye** [comment]
> but we have to, for now, to distinguish what func can be called from Python-scope.

Yeah I agree. Can we at least rename it to indicate that it's not meant to be a public API yet? E.g. `@ti._pyfunc`. @yuanming-hu any thoughts?

**Comment by archibate** [comment]
You may want me to use `@ti.func` to fix the target bug, but it will break Python-scope matrix operation test... That's why I add `@ti.pyfunc` itpr...

**Comment by archibate** [comment]
> PythonTransformer

This idea sounds too smart for me, I don't think users need Taichi syntax in Python-scope anyway.. So I'm merging this now once CI pass.

**Comment by yuanming-hu** [comment]
> This idea sounds too smart for me, I don't think users need Taichi syntax in Python-scope anyway.. So I'm merging this now once CI pass.

It doesn't mean we are using Taichi syntax in Python-scope. Instead, we are just making `@ti.func` directly callable in Python-scope. Of course, I don't think that belongs to this PR :-)

**Pull request merged**
