### PR TITLE
[type] Support atomic add on CustomFloatType

### PR DESCRIPTION
**Pull request by Hanke98**
Related issue = #1905 #2078

We try to support atomic add on `CustomFloatType` following the implementation of `CustomIntType` in this pr. 

[[Click here for the format server]](http://kun.csail.mit.edu:31415/)

----

### CODE REVIEW

**Comment by Hanke98** [comment]
It seems that something went wrong on CUDA. I only tested it on my Mac. Sorry about that and let me find out why.

**Review by TH3CHARLie — APPROVED** [review]
Nice and clean! Thanks!

**Review by taichi-gardener — APPROVED** [review]
LGTM, thanks!

**Comment by taichi-gardener** [comment]
(Sorry I forgot to logout @taichi-gardener...)

**Pull request merged**
