### PR TITLE
[refactor] Renamed ti.Index to ti.Axis

### LINKED ISSUE #2516: Rename `ti.Index` to `ti.Axis`
Index is a slightly oversubscribed terminology, let's switch to "Axis" to denote things like `ti.ijk`.

https://github.com/taichi-dev/taichi/blob/f276de47518d900282ccaede5c1fe0a6f6170087/taichi/ir/snode.h#L13-L30

https://github.com/taichi-dev/taichi/blob/cd96133e9e45df588c53042099a0b8b37b6c75e1/python/taichi/lang/impl.py#L592-L593

### PR DESCRIPTION
**Pull request by Patil2099**
Fixes #2516

### CODE REVIEW

**Comment by k-ye** [comment]
Thanks @Patil2099 ! You would also need to replace all the places where `Index` class is used :-)

**Comment by ljcc0930** [comment]
Thanks so much for contributing @Patil2099! Still, it's necessary to pass the compile process and tests after editing : )

There are still some places that are using `Index()` now, like:
https://github.com/taichi-dev/taichi/blob/6235a5243afe5e63650b21b0a8597e2adb9bf9d4/taichi/ir/frontend.h#L89-L97

https://github.com/taichi-dev/taichi/blob/6235a5243afe5e63650b21b0a8597e2adb9bf9d4/taichi/python/export_lang.cpp#L247-L267

It would be great if you can solve out all of these `Index()` es~

**Review by ljcc0930 — CHANGES_REQUESTED** [review]
https://github.com/taichi-dev/taichi/pull/2517#issuecomment-878713678

**Comment by ljcc0930** [comment]
Hi, @Patil2099, I am so sorry that I have to close this PR because there has been no response for a long time. Still, please feel free to open a new pull request if you finished this work~

**Pull request closed without merging**
