### PR TITLE
[Doc] Update dev install about m1 prebuilt llvm.

### PR DESCRIPTION
**Pull request by ailzhang**
Related issue = #

### CODE REVIEW

**Comment by ailzhang** [comment]
cc: @Vissidarte-Herman

**Review by qiao-bo — APPROVED** [review]
Thanks! Looks great!

**Comment by Vissidarte-Herman** [comment]
If you *encounter* "" on macOS, there are two ways to work around *this*: 
- (One-off) `System configurations` > `xxx` > `yyy`.
- (Permanent) Run `sudo spctl --master-disable` in your terminal to allow your MacBook to download apps from anywhere by default.

**Review by Vissidarte-Herman — CHANGES_REQUESTED** [review]
If you encounter `llvm-as can’t be opened because Apple cannot check it for malicious software` on macOS, you have two options to work around this:

(One-off) `System configurations` > `Security & Privacy` > `General` > `Allow anyway`.
(Permanent) Run sudo spctl --master-disable` in your terminal to allow your MacBook to download apps from anywhere by default.

**Pull request merged**
