### PR TITLE
[ir] SNodeOpStmt use GlobalPtrStmt for all SNodeOpTypes

### PR DESCRIPTION
**Pull request by xumingkuan**
Related issue = #742 

This PR removes the `indices` field from `SNodeOpStmt`.

I have a question in `lower_access`: what if a global pointer is lowered with `activate == false` by a `SNodeOpStmt` or a `GlobalLoadStmt`, but later we need to activate that pointer? 

[[Click here for the format server]](http://kun.csail.mit.edu:31415/)

----

### CODE REVIEW

**Review by yuanming-hu — APPROVED** [review]
Awesome! LGTM, and welcome back!

**Comment by xumingkuan** [comment]
> Awesome! LGTM, and welcome back!
> 
> > I have a question in lower_access: what if a global pointer is lowered with activate == false by a SNodeOpStmt or a GlobalLoadStmt, but later we need to activate that pointer?
> 
> I'm not exactly sure what "later we need to activate that pointer" refers to, but here's what I remember about the `activate` flag:
> 
> * When created, each `GlobalPtrStmt` has `activate=true`
> * In `flag_access` (before `lower_access`), for read-only pointers we mark `activate=false`
> 
> (There doesn't seem to be a place where we mark a pointer with `activate=false` as `activate=true`? :-) Correct me if I'm wrong.)

IIUC, `flag_access` in fact does the following:

* Mark each `GlobalPtrStmt` as `activate=false`
* For global stores and atomic ops, mark the pointers as `activate=true`
* For global pointers with `activate=true` inside struct fors, mark them as `activate=false` if they share sparsity with the loop indices

**Comment by yuanming-hu** [comment]
> > Awesome! LGTM, and welcome back!
> > > I have a question in lower_access: what if a global pointer is lowered with activate == false by a SNodeOpStmt or a GlobalLoadStmt, but later we need to activate that pointer?
> > 
> > 
> > I'm not exactly sure what "later we need to activate that pointer" refers to, but here's what I remember about the `activate` flag:
> > 
> > * When created, each `GlobalPtrStmt` has `activate=true`
> > * In `flag_access` (before `lower_access`), for read-only pointers we mark `activate=false`
> > 
> > (There doesn't seem to be a place where we mark a pointer with `activate=false` as `activate=true`? :-) Correct me if I'm wrong.)
> 
> IIUC, `flag_access` in fact does the following:
> 
> * Mark each `GlobalPtrStmt` as `activate=false`
> * For global stores and atomic ops, mark the pointers as `activate=true`
> * For global pointers with `activate=true` inside struct fors, mark them as `activate=false` if they share sparsity with the loop indices

This sounds reasonable to me - maybe you can show a specific case where "activate that pointer" becomes problematic?

**Comment by xumingkuan** [comment]
> > 
> > 
> > IIUC, `flag_access` in fact does the following:
> > 
> > * Mark each `GlobalPtrStmt` as `activate=false`
> > * For global stores and atomic ops, mark the pointers as `activate=true`
> > * For global pointers with `activate=true` inside struct fors, mark them as `activate=false` if they share sparsity with the loop indices
> 
> This sounds reasonable to me - maybe you can show a specific case where "activate that pointer" becomes problematic?

I see... I thought each pointer should be lowered only once, but I re-read `lower_access` and found that it is the operation (global load/store, atomic op, snode op) rather than the pointer that gets replaced (with lowered statements). There should be no problem here.

**Pull request merged**
