### PR TITLE
[Metal] Silence compile warning with [[maybe_unused]]

### PR DESCRIPTION
**Pull request by k-ye**
Related issue id = #593 

[[Click here for the format server]](http://kun.csail.mit.edu:31415/)

### CODE REVIEW

**Comment by yuanming-hu** [comment]
Does requesting a review from @taichi-gardener (which is a robot) means a request to auto-format your code (which sounds like a great idea)? Or should I review it instead?

**Comment by k-ye** [comment]
> Does requesting a review from @taichi-gardener (which is a robot) means a request to auto-format your code (which sounds like a great idea), or should I review it instead?

The former :) I will ping you directly if i think a PR is worth a review... BTW, I found that clicking the format server sometimes didn't generate a reformat commit. Does that mean that there is no change after the server formats the PR?

**Comment by yuanming-hu** [comment]
> The former :)

This sounds like a great feature to implement. Much better than the current format server approach.

> BTW, I found that clicking the format server sometimes didn't generate a reformat commit. Does that mean that there is no change after the server formats the PR?

Right, there's no way to commit without a changeset.

**Comment by k-ye** [comment]
> This sounds like a great feature to implement. Much better than the current format server approach.

I should probably clarify 😂 I added @taichi-gardener *in the hope* that it will do an automatic reformat for me on this PR. Not sure if this actually works...

**Comment by yuanming-hu** [comment]
> > This sounds like a great feature to implement. Much better than the current format server approach.
> 
> I should probably clarify  I added @taichi-gardener _in the hope_ that it will do an automatic reformat for me on this PR. Not sure if this actually works...

No, currently this won't work. But I think this is a great idea. Someone needs to implement this using github API.

**Comment by k-ye** [comment]
Hmm, guess this will be one of those "nuance differences" between my local `clang-format` (`9.0` IIRC) and `clang-format-6.0`... Seems like `6.0` couldn't handle the code nested inside the `STR` macro very well. I would probably just force repush..

**Comment by yuanming-hu** [comment]
Sounds good. Another option is to install `clang-format-9.0` when the format server is easy enough to use.

**Comment by k-ye** [comment]
I guess one of those clang-format options probably controls this behavior, but i'm too lazy to figure that out... Anyway, I've reformatted locally and disabled `clang-format` around this piece of code

**Pull request merged**
