### PR TITLE
[aot] CI for taichi-aot-demo PR90

### PR DESCRIPTION
**Pull request by PENGUINLIONG**
Ref: https://github.com/taichi-dev/taichi-aot-demo/pull/90

### CODE REVIEW

**Comment by PENGUINLIONG** [comment]
btw I just came up with an idea to sync CI for the aot demo repo. we can just open a PR and stamp & close it after the CI passes. Then we don't have to revert the changes in taichi's aot demo CI script. cc @ailzhang  @feisuzhu wdyt

**Comment by ailzhang** [comment]
@PENGUINLIONG hmmm I didn't quite follow, could you elaborate? ;)

**Comment by PENGUINLIONG** [comment]
> @PENGUINLIONG hmmm I didn't quite follow, could you elaborate? ;)

1. PR in `taichi-aot-demo`
2. PR in `taichi` and ref to the PR branch in `taichi-aot-demo` in `.github/workflows/scripts/aot-demo.sh`
3. After all CI passed, **approve & close** (instead of merge) the PR in `taichi` and **merge** the PR in `taichi-aot-demo`

Then we don't have to worry about tracking `taichi-aot-demo` for the latest master (maybe with some automated checker workflows in the future)

**Comment by ailzhang** [comment]
@PENGUINLIONG Aha sure! @jim19930609 and I already did these testing PRs in the past, with a minor difference in the last step: we just paste the link to taichi PR in taichi-aot-demo and then request a review so that we can get a stamp there;)

**Pull request closed without merging**
