### PR TITLE
[Bug] [opengl] Fix AMD+OpenGL to_numpy behavior (thank @Eydcao for testing!)

### LINKED ISSUE #1125: [Bug][opengl] mpm99.py rendering failed
**Describe the bug**
Hi,
The mpm99.py can show FPS and background, but failed to completely render jelly, liquid and snow.
My computer using an Intel HD 4400 chip(integrated graphics). CPU is i3-4160 and OpenGL version is 4.3.

**Log/Screenshots**
GIF 2020-6-3 19-33-56
[debug.log](https://github.com/taichi-dev/taichi/files/4723140/debug.log)

**To Reproduce**
`python examples\mpm99.py`

**If you have local commits (e.g. compile fixes before you reproduce the bug), please make sure you first make a PR to fix the build errors and then report the bug.**

### PR DESCRIPTION
**Pull request by archibate**
Related issue = close #1125

[[Click here for the format server]](http://kun.csail.mit.edu:31415/)

I found the reason: https://www.khronos.org/opengl/wiki/Interface_Block_(GLSL)

> std430: This layout works like std140, except with a few optimizations in the alignment and strides for arrays and structs of scalars and vector elements. Specifically, they are no longer rounded up to a multiple of 16 bytes. So an array of `float`s will match with a C++ array of `float`s.

So, specifying `std140` layout will make arrays aligned to 16 bytes?
We should use `std430` to match those of C++ float arrays.

> packed: This layout type means that the implementation determines everything about how the fields are laid out in the block.

1. `packed` work well on mesa & NVIDIA OpenGL since they consider `packed` as `std430`.
2. And AMD OpenGL happened to consider `packed` as `std140`, which will align to 16 bytes.

@Eydcao Would you mind to test the sample codes against this PR? It should works well now, thank for your patient!
```py
import taichi as ti
ti.init(arch=ti.opengl)

x = ti.var(ti.f64, 512)

@ti.kernel
def func():
  for i in x:
    x[i] = i + 1

print(x.to_numpy())
```

### CODE REVIEW

**Comment by Eydcao** [comment]
Great fix! My pleasure, please allow some time because its my first time for dev-installing on windows.

**Comment by Eydcao** [comment]
Hi Yubin sorry for the delay because of poor internet, I assume that I have successfully built it on Windows as shown below

bin

I have also add the path(s)

path

But when I run fractal.py it still says [mode=release] and says ` taichi_core import failed`. Any suggestions?

image

**Comment by Eydcao** [comment]
To be noted that the `taichi_core import failed` happened after I added the `PYTHONPATH`. Without it being added, the program uses the normal taichi I installed from pip without error.

**Comment by archibate** [comment]
Did you add `TAICHI_REPO_DIR`? Taichi needs this environment var to became development mode.

**Comment by Eydcao** [comment]
No.
Should I add this as a new var in windows environment var list (just the same place of `path` and `pythonpath`?

**Comment by archibate** [comment]
No, `TAICHI_REPO_DIR=C:/CYD/Desktop/taichi_related/taichi`, please see https://taichi.readthedocs.io/en/latest/dev_install.html.

**Comment by Eydcao** [comment]
> No, `TAICHI_REPO_DIR=C:/CYD/Desktop/taichi_related/taichi`, please see https://taichi.readthedocs.io/en/latest/dev_install.html.

got it, it is what I meant (in the same window for environment vars as in screenshot) :> Thanks a lot for clarifying. I will give a try in a min

**Comment by Eydcao** [comment]
Now it has problem related to unique `dll_path` as shown below

assertError

**Comment by archibate** [comment]
Did you build `libtaichi_core.so` in `build/`?

**Comment by Eydcao** [comment]
No, btw there is any `.so` on windows? Here is what looks like in build. Since I did not have a vs2017 I used vs2019 and cmake gui to build the project, since the flag is very different from this two version.

image

**Comment by archibate** [comment]
Did you run:
```bash
cd build && msbuild /p:Configuration=RelWithDebInfo /p:Platform=x64 /m taichi.sln
```

**Comment by Eydcao** [comment]
Yes but it gives error like below. I used to use Visual Studio GUI to build all stuff but the result is what we saw. Just find a [post](https://stackoverflow.com/questions/13819294/msbuild-command-not-found-but-msbuild-exe-works-fine) to fix the `msbuild` not found problem.

image

**Comment by Eydcao** [comment]
> Did you run:
> 
> ```shell
> cd build && msbuild /p:Configuration=RelWithDebInfo /p:Platform=x64 /m taichi.sln
> ```

Hi Yubin,

I am afraid I will be unable to solve this building issue on my own. In the latest trial I used cmake to make the vs project and use visual studio to build the whole taichi.sln. Nonetheless, in error message it showed some file missing which does not even exist (`spdlog/fmt/bundled/color.h`) in our repo. I became totally confused and would appreciate a lot if you can help with this building  process with i.e. teamviewer or a more detailed building procedure for windows developers when you are available.

image

BTW I also tried msbuild.exe the error msg also plot here.

image

**Comment by archibate** [comment]
`git submodule update --init`.

**Comment by archibate** [comment]
Hello? Does the `git submodule update` command work for you?

**Comment by Eydcao** [comment]
> Hello? Does the `git submodule update` command work for you?

Hi Yubin, the git init doesnot help but I removed the whole repo and redo all the stuff. Now the files in submodule are okay. Nonetheless, compiling using the command `msbuild /p:Configuration=RelWithDebInfo /p:Platform=x64 /m taichi.sln` still yeilds some strange errors that I am working on. Thanks for all the following up~

Best,

image

**Comment by Eydcao** [comment]
> > Hello? Does the `git submodule update` command work for you?
> 
> Hi Yubin, the git init doesnot help but I removed the whole repo and redo all the stuff. Now the files in submodule are okay. Nonetheless, compiling using the command `msbuild /p:Configuration=RelWithDebInfo /p:Platform=x64 /m taichi.sln` still yeilds some strange errors that I am working on. Thanks for all the following up~
> 
> Best,
> 
> image

I am posting the log for both cmake generate and compiling here~ hope it will help :> I never really do any project on windows so please accept my apology and appreciation.

```
PS C:\Users\CYD\Desktop\taichi_related\taichi\build> cmake .. -G"Visual Studio 15 2017 Win64" -DPYTHON_EXECUTABLE=C:\Users\CYD\AppData\Local\Microsoft\WindowsApps\python.exe -DLLVM_DIR="C:\Users\CYD\Desktop\taichi_related\taichi_llvm\lib\cmake\llvm"
-- Selecting Windows SDK version 10.0.18362.0 to target Windows 10.0.18363.
-- The C compiler identification is MSVC 19.16.27040.0
-- The CXX compiler identification is MSVC 19.16.27040.0
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.16.27023/bin/Hostx86/x64/cl.exe
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.16.27023/bin/Hostx86/x64/cl.exe - works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.16.27023/bin/Hostx86/x64/cl.exe
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.16.27023/bin/Hostx86/x64/cl.exe - works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
Taichi Version 0.6.7
       Commit 765131c5a323f9acbfef80d648836abf3b5a2a67
Using C:\Users\CYD\AppData\Local\Microsoft\WindowsApps\python.exe as python executable.
错误: "path:pattern" 中指定了无效的模式。
Python 3.8.3
    version: 3.8
    include: C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.1008.0_x64__qbz5n2kfra8p0\include
    library: C:/Program Files/WindowsApps/PythonSoftwareFoundation.Python.3.8_3.8.1008.0_x64__qbz5n2kfra8p0/Lib/site-packages/../../libs/python38.lib
    numpy include: C:\Users\CYD\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\numpy\core\include
    pybind11 include: C:\Users\CYD\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\pybind11\include;C:\Users\CYD\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\pybind11\include
Using C++ compiler: C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.16.27023/bin/Hostx86/x64/cl.exe
Building for processor AMD64
Using float32 (single) precision as real
Building with GLFW
-- Looking for pthread.h
-- Looking for pthread.h - not found
-- Using Win32 for window creation
-- Found LLVM 8.0.1
-- Using LLVMConfig.cmake in: C:\Users\CYD\Desktop\taichi_related\taichi_llvm\lib\cmake\llvm
llvm include dirs C:/Users/CYD/Desktop/taichi_related/taichi_llvm/include
PYTHON_LIBRARIESC:/Program Files/WindowsApps/PythonSoftwareFoundation.Python.3.8_3.8.1008.0_x64__qbz5n2kfra8p0/Lib/site-packages/../../libs/python38.lib       
Added executable 'ti' for Windows
C++ Flags: /DWIN32 /D_WINDOWS /W3 /GR /EHsc -DTI_ISE_NONE /Zc:__cplusplus /std:c++17 /MP /Z7 /D "_CRT_SECURE_NO_WARNINGS" /D "_ENABLE_EXTENDED_ALIGNED_STORAGE" /D "TI_ARCH_x64" -DTI_PASS_EXCEPTION_TO_PYTHON -DTI_INCLUDED -DTI_WITH_CUDA -DTI_WITH_OPENGL
Build type: Release
python=C:\Users\CYD\AppData\Local\Microsoft\WindowsApps\python.exe
-- Configuring done
-- Generating done
-- Build files have been written to: C:/Users/CYD/Desktop/taichi_related/taichi/build
```

Then the compiling log

```
PS C:\Users\CYD\Desktop\taichi_related\taichi\build> msbuild /p:Configuration=RelWithDebInfo /p:Platform=x64 /m taichi.sln
Microsoft(R) 生成引擎版本 4.8.3752.0
[Microsoft .NET Framework 版本 4.0.30319.42000]
版权所有 (C) Microsoft Corporation。保留所有权利。

生成启动时间为 2020/6/7 15:07:05。
     1>节点 1 上的项目“C:\Users\CYD\Desktop\taichi_related\taichi\build\taichi.sln”(默认目标)。
     1>ValidateSolutionConfiguration:
         正在生成解决方案配置“RelWithDebInfo|x64”。
       ValidateProjects:
         在解决方案配置“RelWithDebInfo|x64”中未选定生成项目“INSTALL”。
         在解决方案配置“RelWithDebInfo|x64”中未选定生成项目“intrinsics_gen”。
         在解决方案配置“RelWithDebInfo|x64”中未选定生成项目“uninstall”。
     1>项目“C:\Users\CYD\Desktop\taichi_related\taichi\build\taichi.sln”(1)正在节点 1 上生成“C:\Users\CYD\Desktop\taichi_related\taichi\build\ALL_BUILD.vcxproj.metapro
       j”(2) (默认目标)。
     2>项目“C:\Users\CYD\Desktop\taichi_related\taichi\build\ALL_BUILD.vcxproj.metaproj”(2)正在节点 6 上生成“C:\Users\CYD\Desktop\taichi_related\taichi\build\ZERO_CHEC
       K.vcxproj”(7) (默认目标)。
     7>C:\Users\CYD\Desktop\taichi_related\taichi\build\ZERO_CHECK.vcxproj(29,3): error MSB4019: 未找到导入的项目“C:\Microsoft.Cpp.Default.props”。请确认 <Import> 声明中的路径正
       确，且磁盘上存在该文件。
     7>已完成生成项目“C:\Users\CYD\Desktop\taichi_related\taichi\build\ZERO_CHECK.vcxproj”(默认目标)的操作 - 失败。
     2>已完成生成项目“C:\Users\CYD\Desktop\taichi_related\taichi\build\ALL_BUILD.vcxproj.metaproj”(默认目标)的操作 - 失败。
     1>已完成生成项目“C:\Users\CYD\Desktop\taichi_related\taichi\build\taichi.sln”(默认目标)的操作 - 失败。

生成失败。

       “C:\Users\CYD\Desktop\taichi_related\taichi\build\taichi.sln”(默认目标) (1) ->
       “C:\Users\CYD\Desktop\taichi_related\taichi\build\ALL_BUILD.vcxproj.metaproj”(默认目标) (2) ->
       “C:\Users\CYD\Desktop\taichi_related\taichi\build\ZERO_CHECK.vcxproj”(默认目标) (7) ->
         C:\Users\CYD\Desktop\taichi_related\taichi\build\ZERO_CHECK.vcxproj(29,3): error MSB4019: 未找到导入的项目“C:\Microsoft.Cpp.Default.props”。请确认 <Import> 声明中的路
       径正确，且磁盘上存在该文件。

    0 个警告
    1 个错误

已用时间 00:00:00.19
```

**Comment by archibate** [comment]
> Since I did not have a vs2017 I used vs2019

You are using **vs2019**? Then you should
```
cmake .. -G"Visual Studio 15 2019 Win64"
```

**Comment by Eydcao** [comment]
> > Since I did not have a vs2017 I used vs2019
> 
> > cmake .. -G"Visual Studio 15 2017 Win64" ...
> 
> You are using **vs2019** but telling `cmake` to generate **vs2017**?
> 
> Please use
> 
> ```
> cmake .. -G"Visual Studio 15 2019 Win64" ...
> ```
> 
> instead.

Hello, it seems that cmake has many different syntax for V2019 i.e. `''Visual Studio 16 2019'' -A=Win64 ...` instead of allowing a `[option=arch]` following `''Visual Studio 15 2019''`. I used the corresponding flags but it generates more errors... I will just  remove all MSVC2019 related so only VS2017 is the compiler on my pc :> I donot  use it much anyway.

**Comment by Eydcao** [comment]
Hi Yubin I finished the dev installing and both your print test and fractal work pretty well now!

Great Fix! Given what happened to me I would like to add a note for develop install on Windows
:> thanks again!

good_fractal

good_print

**Comment by archibate** [comment]
Great! The issue is finally resolved, and will be shipped with v0.6.8 release!

> Great Fix! Given what happened to me I would like to add a note for develop install on Windows.

Thanks! Feel free to add that documentation in another PR.

**Comment by archibate** [comment]
Hello? May I merge this asap before v0.6.8 release? People including GitHub issues & forum threads are waiting for this hotfix for long.

**Pull request merged**
