### PR TITLE
[metal] Add a TI_WITH_METAL option

### PR DESCRIPTION
**Pull request by AmesingFlank**
Add a TI_WITH_METAL option, defaulted to true, so that one can optionally disable building for metal.

### CODE REVIEW

**Comment by sjwsl** [comment]
Do we also need to disable this option and raise a warning on non-macOS? Like
https://github.com/taichi-dev/taichi/blob/00b66a8c633cb2e71e7c76ed0473c9cfb5dc90a5/cmake/TaichiCore.cmake#L16-L19

**Comment by AmesingFlank** [comment]
> Do we also need to disable this option and raise a warning on non-macOS? Like
> 
> https://github.com/taichi-dev/taichi/blob/00b66a8c633cb2e71e7c76ed0473c9cfb5dc90a5/cmake/TaichiCore.cmake#L16-L19

@k-ye thoughts? I understand that metal has an AOT module so it might be useful to have the metal backend even when we're not on macOS.

**Review by ailzhang — APPROVED** [review]
LGTM!

**Comment by ailzhang** [comment]
@AmesingFlank Metal AOT isn't fully working  without a metal runtime (due to jit evaluators) yet but we plan to fix it later :P 
So yea I'm fine with either way as long as we have a note explaining its behavior :D

**Pull request merged**
