### PR TITLE
[opengl] add check_opengl_error to prevent potential segfault

### PR DESCRIPTION
**Pull request by archibate**
Related issue = #693 
Related PR = #694

[[Click here for the format server]](http://kun.csail.mit.edu:31415/)

### CODE REVIEW

**Comment by archibate** [comment]
```py
import taichi as ti
import numpy as np
import torch

ti.init(arch=ti.opengl)

def test_io():
    n = 32

    @ti.kernel
    def torch_kernel(t: ti.ext_arr(), o: ti.ext_arr()):
        for i in range(n):
            o[i] = t[i] * t[i]

    @ti.kernel
    def torch_kernel_2(t_grad: ti.ext_arr(), t: ti.ext_arr(),
                       o_grad: ti.ext_arr()):
        for i in range(n):
            t_grad[i] = 2 * t[i] * o_grad[i]

    class Sqr(torch.autograd.Function):
        @staticmethod
        def forward(ctx, inp):
            outp = torch.zeros_like(inp)
            ctx.save_for_backward(inp)
            torch_kernel(inp, outp)
            return outp

        @staticmethod
        def backward(ctx, outp_grad):
            outp_grad = outp_grad.contiguous()
            inp_grad = torch.zeros_like(outp_grad)
            inp, = ctx.saved_tensors
            torch_kernel_2(inp_grad, inp, outp_grad)
            return inp_grad

    sqr = Sqr.apply
    X = torch.tensor(2 * np.ones((n, ), dtype=np.float32), requires_grad=True)
    sqr(X).sum().backward()
    ret = X.grad.cpu()
    for i in range(n):
        assert ret[i] == 4

def my_test_io():
    ag = torch.tensor(9, dtype=torch.int32)
    bg = torch.tensor(1, dtype=torch.int32)
    cg = torch.tensor(2, dtype=torch.int32)

    @ti.kernel
    def torch_io(a: ti.ext_arr(), b: ti.ext_arr()):
        a[None] = b[None] * b[None]

    @ti.kernel
    def torch_io_2(a: ti.ext_arr(), b: ti.ext_arr(), c: ti.ext_arr()):
        a[None] = 2 * b[None] * c[None]

    torch_io(ag, bg)
    print(ag.item())
    torch_io_2(ag, bg, cg)
    print(ag.item())

my_test_io()
```
What's the difference between `my_test_io` and `test_io`? Why one pass while the latter fail?

**Comment by archibate** [comment]
`[E 04/08/20 23:55:25.289] [opengl_api.cpp:~GLSLLaunchGuard@415] glMapBuffer failed: GL_NO_ERROR`
I confused. Why it returns NULL if no error?

**Comment by archibate** [comment]
Seems if I remove first kernel call, the second passes.

**Comment by yuanming-hu** [comment]
If this one is too hard to fix then we can skip it for now - not many people will use PyTorch with OpenGL anyway. Those deep-learning people usually have access to CUDA. OpenGL will clearly be more helpful to those without CUDA :-)

**Comment by archibate** [comment]
Ok, but I'm concerning about if this is a potential bug that may accidentally occur in non-pytorch codes...

**Comment by yuanming-hu** [comment]
> Ok, but I'm concerning about if this is a potential bug that may accidentally occur in non-pytorch codes...

Oh, I see - would it be possible to create a test case without PyTorch to reproduce it in a cleaner environment?

My experience with CUDA: sometimes PyTorch's CUDA context fights against Taichi's CUDA context. Not sure about OpenGL though.

**Comment by archibate** [comment]
Sounds like torch also use GL as its backend? That might be the problem, maybe they use glut and we use glfw...anyway there shouldn't be two gl context within one program instance...

**Comment by archibate** [comment]
But anyway, I still want to merge this since it adds very useful `check_opengl_error`.

**Comment by yuanming-hu** [comment]
> Sounds like torch also use GL as its backend?

That's unlikely... I don't think PyTorch will pick OpenGL by default.

**Comment by archibate** [comment]
> > Sounds like torch also use GL as its backend?
> 
> That's unlikely... I don't think PyTorch will pick OpenGL by default.

Fine, I'll give up that issue and just add check_opengl_error in this PR now.

**Pull request merged**
