### PR TITLE
[bug] Returning nan for ti.sym_eig on identity matrix

### PR DESCRIPTION
**Pull request by TachikakaMin**
Issue: #7092

### Brief Summary

Function [_sym_eig3x3](https://github.com/taichi-dev/taichi/blob/ae61418d66b79c4af2173acb00ba8a8b28b5dd54/python/taichi/_funcs.py#L284) is copied from https://www.mpi-hd.mpg.de/personalhomes/globes/3x3/, but the taichi function removed one key "if" statement from original code. 

Just add the full code into taichi.

### CODE REVIEW

**Comment by ailzhang** [comment]
@TachikakaMin I replied in the issue thread about cc test failures, feel free to ping me and @neozhaoliang for a review once pylint error is fixed and the cc skip is added. Thanks a lot for your contribution!

**Comment by TachikakaMin** [comment]
@ailzhang  @neozhaoliang  

Hi all, the pylint error is fixed.

**Comment by neozhaoliang** [comment]
@TachikakaMin Hi, I tested your PR with the following code:

```python
import taichi as ti
import numpy as np

ti.init()
@ti.kernel
def test():
    A = ti.Matrix([[1., 2., 3.], [2., 3., 4.], [3., 4., 8.]])
    I = ti.Matrix.identity(ti.f32,3)
    eig1, V1 = ti.sym_eig(A)
    print(eig1, V1)

test()


a = np.array([[1, 2, 3], [2, 3, 4], [3, 4, 8]])
e, v = np.linalg.eigh(a)
print(e)
print(v)
```

Below are your output and numpy's output:

```
[11.453261, -0.306859, 0.853597] 
[[0.325306, -0.916757, -0.231804],
 [0.466246, 0.368771, -0.804128],
 [0.822673, 0.153510, 0.547398]]

[-0.30685915  0.8535972  11.45326195]
[[-0.91675668 -0.23180398 -0.32530617]
 [ 0.36877068 -0.80412841 -0.46624638]
 [ 0.15351016  0.54739786 -0.8226726 ]]
```

It looks like the first entry of your eigenvectors corresponds to the last entry of that of numpy's, but with the sign changed. Could you please check if this is expected?

Also, it would be better to sort the eigenvalues in ascending order, and also return the eigenvectors according to this order.

Thanks!

**Comment by TachikakaMin** [comment]
@neozhaoliang 

Thanks. I will check the code.

**Comment by neozhaoliang** [comment]
@TachikakaMin May I ask if there has been any progress on this PR? And can you confirm if there is an error about the sign in the eigenvector?

**Comment by TachikakaMin** [comment]
@neozhaoliang 

Hi, I have checked the test. This is not caused by my code. For the original taichi version, it will have the same result.

The sign of eigenvector doesn't matter.  And I can also sort the eigenvalues in ascending order, and also return the eigenvectors according to this order.

**Comment by neozhaoliang** [comment]
@TachikakaMin ahha, I think your code is correct, I misunderstood the eigenvectors as row vectors, they should be column vectors.

Yes, it would be great to have the eigenvalues sorted in ascending order, and the sort the column vectors accordingly!

**Comment by TachikakaMin** [comment]
@neozhaoliang  I have changed the order.

**Comment by TachikakaMin** [comment]
For the bug. https://github.com/taichi-dev/taichi/issues/7092

```python
import taichi as ti

ti.init()
@ti.kernel
def test():
    A = ti.Matrix([[1., 2., 3.], [2., 3., 4.], [3., 4., 8.]])
    I = ti.Matrix.identity(ti.f32,3)
    eig, V = ti.sym_eig(I)
    print(V)
    eig1, V1 = ti.sym_eig(A)
    print(V1)

test()
```

```python
[[1.000000, 0.000000, 0.000000], [0.000000, 1.000000, 0.000000], [0.000000, 0.000000, 1.000000]]
[[-0.916757, -0.231804, 0.325306], [0.368771, -0.804128, 0.466246], [0.153510, 0.547398, 0.822673]]
```

**Pull request merged**
