### PR TITLE
add LineAppender for OpenGL too #643

### PR DESCRIPTION
**Pull request by archibate**
Related PR id = #643

[[Click here for the format server]](http://kun.csail.mit.edu:31415/)

### CODE REVIEW

**Comment by archibate** [comment]
I would appericiate it very much if you could install GLEW on at least one of two CIs so that we could test against GL on the cloud. (Cons: make build even slower, we'd better to install for the currently-slowest one, say Travis, so that the minimal time of seeing a ordinary error can remain unchanged)

**Comment by yuanming-hu** [comment]
> I would appericiate it very much if you could install GLEW on at least one of two CIs so that we could test against GL on the cloud. (Cons: make build even slower, we'd better to install for the currently-slowest one, say Travis, so that the minimal time of seeing a ordinary error can remain unchanged)

Yeah I agree that would be helpful but in my understanding the cloud buildbots basically have no GPUs. Running GLEW/GLFW can be a bit tricky. We can still test compilation though.

I'm actually considering installing GLEW/GLFW on the Linux buildbot, a machine which has a GPU and which I have control.

**Comment by archibate** [comment]
Btw, format server error: `AttributeError: module 'taichi_core' has no attribute 'adstack'`.
After seeing that error, it still executes the following command `git add --all`..
We may want to print `Sorry! Format Server Internal Error!`.
Or just add `set -e` to your bash script's head.

**Comment by yuanming-hu** [comment]
> Btw, format server error: `AttributeError: module 'taichi_core' has no attribute 'adstack'`.
> After seeing that error, it still executes the following command `git add --all`..
> We may want to print `Sorry! Format Server Internal Error!`.
> Or just add `set -e` to your bash script's head.

Yeah I agree. For now, I believe the issue will be resolved after https://github.com/taichi-dev/taichi/issues/647.

**Comment by archibate** [comment]
> Yeah I agree that would be helpful but in my understanding the cloud buildbots basically have no GPUs. Running GLEW/GLFW can be a bit tricky. We can still test compilation though.

Sorry to hear that... as a language related to parallel computaion, I think taichi will need GPU CI sooner or later..

> I'm actually considering installing GLEW/GLFW on the Linux buildbot, a machine which has a GPU and which I have control.

Great! Now we have buildbots of all OS三巨头s, definitely will make us more stronger! Also will this be a CUDA CI?

**Comment by yuanming-hu** [comment]
> Great! Now we have buildbots of all OS三巨头s, definitely will make us more stronger! Also will this be a CUDA CI?

Right, CUDA CI is actually already up for a while (but will only run if I manually click): http://f11.csail.mit.edu:8080/job/taichi/

**Comment by archibate** [comment]
> > Great! Now we have buildbots of all OS三巨头s, definitely will make us more stronger! Also will this be a CUDA CI?
> 
> Right, CUDA CI is actually already up for a while (but will only run if I manually click): http://f11.csail.mit.edu:8080/job/taichi/

Cool! Is that possible to intergrate GLEW into that now?

**Comment by archibate** [comment]
Both local and CI build passing, can merge now.

**Comment by yuanming-hu** [comment]
> > > Great! Now we have buildbots of all OS三巨头s, definitely will make us more stronger! Also will this be a CUDA CI?
> > 
> > 
> > Right, CUDA CI is actually already up for a while (but will only run if I manually click): http://f11.csail.mit.edu:8080/job/taichi/
> 
> Cool! Is that possible to intergrate GLEW into that now?

Of course - feel free to edit `.travis.yml` to add a Linux build with OpenGL. Btw, we should OS X with Python 3.6 and 3.8 on Travis, when building without `[release]`.

So I suggest we do the following:
 - on Travis, without `[release]`, build
   - `OS X + Python 3.7 + OpenGL`
   - `Ubuntu 18.04 + Python 3.7 + OpenGL`
 - on Travis, with `[release]`, build
   - `OS X + Python 3.6 + OpenGL`
   - `OS X + Python 3.7 + OpenGL`
   - `OS X + Python 3.8 + OpenGL`
   - `Ubuntu 18.04 + Python 3.6 + OpenGL`
   - `Ubuntu 18.04 + Python 3.7 + OpenGL`
   - `Ubuntu 18.04 + Python 3.8 + OpenGL`

Note that we only build but not test.

Meanwhile, I'll set up OpenGL testing on my end.

**Comment by k-ye** [comment]
Thanks!

**Comment by archibate** [comment]
> > > > Great! Now we have buildbots of all OS三巨头s, definitely will make us more stronger! Also will this be a CUDA CI?
> > > 
> > > 
> > > Right, CUDA CI is actually already up for a while (but will only run if I manually click): http://f11.csail.mit.edu:8080/job/taichi/
> > 
> > 
> > Cool! Is that possible to intergrate GLEW into that now?
> 
> Of course - feel free to edit `.travis.yml` to add a Linux build with OpenGL. Btw, we should OS X with Python 3.6 and 3.8 on Travis, when building without `[release]`.
> 
> So I suggest we do the following:
> 
>     * on Travis, without `[release]`, build
>       
>       * `OS X + Python 3.7 + OpenGL`
>       * `Ubuntu 18.04 + Python 3.7 + OpenGL`

Currently, OS X seems also build against 3.6&3.8 even if no `[release]` specified, was that right?
Also found https://docs.travis-ci.com/user/conditional-builds-stages-jobs/ can be useful.

> 
>     * on Travis, with `[release]`, build
>       
>       * `OS X + Python 3.6 + OpenGL`
>       * `OS X + Python 3.7 + OpenGL`
>       * `OS X + Python 3.8 + OpenGL`
>       * `Ubuntu 18.04 + Python 3.6 + OpenGL`
>       * `Ubuntu 18.04 + Python 3.7 + OpenGL`
>       * `Ubuntu 18.04 + Python 3.8 + OpenGL`
> 
> 
> Note that we only build but not test.

We can do that using `ti --arch x64 test`!

> 
> Meanwhile, I'll set up OpenGL testing on my end.

Thanks!

**Comment by yuanming-hu** [comment]
> Currently, OS X seems also build against 3.6&3.8 even if no `[release]` specified, was that right?
> Also found https://docs.travis-ci.com/user/conditional-builds-stages-jobs/ can be useful.

Right. If you can make Travis skip Python 3.6 and 3.8 on normal builds, we'll have more resources for building OpenGL on Linux. This will also help reduce false alarms from Travis, since we have observed that Travis fails for unknown reasons on OS X.

**Pull request merged**
