### PR TITLE
[perf] Fix Taichi CPU backend compile parameter to pair performance with Numba.

### PR DESCRIPTION
**Pull request by zxlbig**
Issue: #7442

### Brief Summary

In this issue, Numba is a magnitude faster than Taichi due to the absence of automatic vectorization. 
The root cause is the incorrect passage of the `fast_flag`.

To solve this problem, `fast_flag` is now added to the initialization of cpu codegen. Numba and Taichi now reveal comparable performance.
Here's perf comparison:
numba:            13052.542478MFlops
taichi(master): 6544.274409MFlops
taichi(this pr):  12778.240179MFlops

### CODE REVIEW

**Review by jim19930609 — COMMENTED** [review]
Per discussion offline, one of the major concern is that these changes on FastMath might induce performance regression on CPU backends, which have not been actively monitored by our perf bot yet. 

Can we add some descriptions or profiling results (with demos from `python/taichi/examples`) to demonstrate the influence on CPU performance?

**Comment by turbo0628** [comment]
@feisuzhu This PR changes CPU performance so it might not be observable with /benchmark.

**Review by turbo0628 — APPROVED** [review]
LGTM!

**Comment by zxlbig** [comment]
> Per discussion offline, one of the major concern is that these changes on FastMath might induce performance regression on CPU backends, which have not been actively monitored by our perf bot yet.
> 
> Can we add some descriptions or profiling results (with demos under `python/taichi/examples`) to demonstrate the influence on CPU performance?
Based on your test, it seems that the performance of "mpm88" has not been affected by the PR (pull request). This is because I only added some "fast_math" flags during codegen, which can currently only solve the issue of why "pi" cannot be automatically vectorized.

I hope this helps clarify the situation for you! Let me know if you have any other question

**Comment by zxlbig** [comment]
> > Per discussion offline, one of the major concern is that these changes on FastMath might induce performance regression on CPU backends, which have not been actively monitored by our perf bot yet.
> > Can we add some descriptions or profiling results (with demos under `python/taichi/examples`) to demonstrate the influence on CPU performance?
> 
> Based on your test, it seems that the performance of "mpm88" has not been affected by the PR (pull request). This is because I only added some "fast_math" flags during codegen, which can currently only solve the issue of why "pi" cannot be automatically vectorized.
> 
> I hope this helps clarify the situation for you! Let me know if you have any other question
Here's this pr performance
```
========================================================================
Kernel Profiler(count, default) @ X64 
=========================================================================
[      %     total   count |      min       avg       max   ] Kernel name
-------------------------------------------------------------------------
[ 83.67%   0.046 s     50x |    0.884     0.915     0.982 ms] substep_c74_0_kernel_3_range_for
[ 10.62%   0.006 s     50x |    0.102     0.116     0.200 ms] substep_c74_0_kernel_2_range_for
[  3.21%   0.002 s     50x |    0.022     0.035     0.100 ms] substep_c74_0_kernel_1_range_for
[  2.30%   0.001 s     50x |    0.013     0.025     0.088 ms] substep_c74_0_kernel_0_range_for
[  0.20%   0.000 s      1x |    0.108     0.108     0.108 ms] init_c76_0_kernel_0_range_for
-------------------------------------------------------------------------
[100.00%] Total execution time:   0.055 s   number of results: 5
=========================================================================

```
Here's master performance:
```
=========================================================================
Kernel Profiler(count, default) @ X64 
=========================================================================
[      %     total   count |      min       avg       max   ] Kernel name
-------------------------------------------------------------------------
[ 83.88%   0.045 s     50x |    0.884     0.907     0.958 ms] substep_c74_0_kernel_3_range_for
[ 10.39%   0.006 s     50x |    0.101     0.112     0.176 ms] substep_c74_0_kernel_2_range_for
[  3.17%   0.002 s     50x |    0.022     0.034     0.083 ms] substep_c74_0_kernel_1_range_for
[  2.42%   0.001 s     50x |    0.013     0.026     0.069 ms] substep_c74_0_kernel_0_range_for
[  0.14%   0.000 s      1x |    0.076     0.076     0.076 ms] init_c76_0_kernel_0_range_for
-------------------------------------------------------------------------
[100.00%] Total execution time:   0.054 s   number of results: 5
=========================================================================
```

**Review by jim19930609 — APPROVED** [review]

**Pull request merged**
