### PR TITLE
[Lang] Fix pylint rule W0201

### PR DESCRIPTION
**Pull request by Dustyposa**
Related issue = #3151

### CODE REVIEW

**Comment by sjwsl** [comment]
Could you also add this pylint rule in CI to verify your work? See [here](https://github.com/taichi-dev/taichi/issues/3151#issuecomment-965944567) for more details. Thanks!

**Comment by Dustyposa** [comment]
> Could you also add this pylint rule in CI to verify your work? See [here](https://github.com/taichi-dev/taichi/issues/3151#issuecomment-965944567) for more details. Thanks!

forget it. Had fixed

**Comment by sjwsl** [comment]
Ah, please do not remove existing rules and just append the new one :)

**Comment by Dustyposa** [comment]
> Ah, please do not remove existing rules and just append the new one :)

FIxed....

**Comment by ailzhang** [comment]
@Dustyposa Would you mind signing our CLA above and this PR should be good to go! Thanks a lot!

**Comment by Dustyposa** [comment]
> @Dustyposa Would you mind signing our CLA above and this PR should be good to go! Thanks a lot!

I had sign it. Thanks.

**Review by sjwsl — APPROVED** [review]
Great job! Thanks for your contribution.

**Comment by sjwsl** [comment]
Great job! Thanks for your contribution.

**Pull request merged**
