### PR TITLE
[build] Fix build on arm64

### PR DESCRIPTION
**Pull request by oliver-batchelor**
Issue: #7916

### Brief Summary

This was a suggested fix for building taichi on arm64 on a jetson.

### CODE REVIEW

**Comment by houkensjtu** [comment]
Hi @oliver-batchelor ! Thank you for the PR!
Looks like this change caused several failures in the CI test. I'll try to investigate the reason for that and get back to you.

**Comment by houkensjtu** [comment]
Hi @oliver-batchelor ! Just some tips to share with you about the PR(pull request) process:
1. Please include a type label in the PR title, such as the one I added for you "[build]", otherwise it will fail the "Presubmit Title Check" in our CI 
2. Sometimes CI tests might fail for random reason: it's not always your fault! If you see a failure in the CI section, try to read the error log and see if it's related to your PR. If it's not, try "rerun" the CI test ( you can find the rerun button in the "Details" page of the CI action)
3. A PR needs at least one reviewer's approval to get merged. You can select the reviewer on the right side of the PR page.

**Review by ailzhang — APPROVED** [review]
Thanks!

**Comment by feisuzhu** [comment]
@oliver-batchelor This modification breaks some existing tests, reverting for now.

2023-05-19-143241_797x1029_scrot

**Comment by houkensjtu** [comment]
Are the failed tests part of our CI procedure? I wonder why the PR passed all CI with green checks..

**Comment by feisuzhu** [comment]
> Are the failed tests part of our CI procedure? I wonder why the PR passed all CI with green checks..

Yes, and it is yet to be investigated.

**Pull request merged**
