### PR TITLE
[ci] Add taichiCourse01 & marching_squares release tests

### PR DESCRIPTION
**Pull request by L2ncE**
Issue: #5741 

### <samp>🤖 Generated by Copilot at bc9de83</samp>

This pull request adds tests for more taichi examples and features from external repositories in `taichiCourse01`. It updates the test scripts for both Unix and Windows platforms to clone and install the necessary dependencies and run the tests.

### <samp>🤖 Generated by Copilot at bc9de83</samp>

*  Add six git clone commands to download additional repositories from taichiCourse01 in both `unix_test.sh` and `win_test.ps1` scripts ([link](https://github.com/taichi-dev/taichi/pull/8157/files?diff=unified&w=0#diff-34fa2bad51121dca1ec0d22993a5d102611b68b6466589d40a651b955ea67ca3R56-R61), [link](https://github.com/taichi-dev/taichi/pull/8157/files?diff=unified&w=0#diff-1e56d5e9fca9a2bd938d65c6735714636f8d236462ae1167ca97e3c1a166cf54L98-R125))
*  Add six pairs of pushd and popd commands to install the requirements for each of the cloned repositories using pip in both `unix_test.sh` and `win_test.ps1` scripts ([link](https://github.com/taichi-dev/taichi/pull/8157/files?diff=unified&w=0#diff-34fa2bad51121dca1ec0d22993a5d102611b68b6466589d40a651b955ea67ca3R68-R91), [link](https://github.com/taichi-dev/taichi/pull/8157/files?diff=unified&w=0#diff-1e56d5e9fca9a2bd938d65c6735714636f8d236462ae1167ca97e3c1a166cf54L98-R125))
*  Modify the existing code in `win_test.ps1` to match the changes in `unix_test.sh` for running the tests on different platforms ([link](https://github.com/taichi-dev/taichi/pull/8157/files?diff=unified&w=0#diff-1e56d5e9fca9a2bd938d65c6735714636f8d236462ae1167ca97e3c1a166cf54L98-R125))

### CODE REVIEW

**Review by feisuzhu — APPROVED** [review]
LGTM!

**Comment by L2ncE** [comment]
> LGTM!

After fixing the failure caused by taichi_sph/demo.py, I will change the Draft status to Ready for review

**Comment by L2ncE** [comment]
waiting for https://github.com/taichiCourse01/taichi_sph/pull/2

**Comment by L2ncE** [comment]
Ignore taichi_sph for now and add marching squares

**Pull request merged**
