### PR TITLE
[refactor] Improve CUDA kernel launch logic for external arrays and ndarrays

### PR DESCRIPTION
**Pull request by ailzhang**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #7869

### CODE REVIEW

**Review by lin-hitonami — APPROVED** [review]
LGTM. Reminder: We should refactor on AMDGPU backend as well.

**Comment by ailzhang** [comment]
@lin-hitonami agreed! But amd backend is not on my critical path to get in ndarray ad atm so it's relatively lower pri for me, @GaleSeLee would you mind helping on porting this change to amd kernel_launcher.cpp as well? Thanks a ton!

**Comment by GaleSeLee** [comment]
Sure! I'll update soon

**Pull request merged**
