### PR TITLE
[Metal] Add Runtime shaders to support sparse SNode

### PR DESCRIPTION
**Pull request by k-ye**
Related issue id = #593 

This should look familiar, but not exactly identical to LLVM's runtime. Like `helpers.metal.h`, these are mostly used to generate Metal code, so there's not much documentation. I can add more when implementing the host side..

### CODE REVIEW

**Comment by k-ye** [comment]
> One thing that may worth considering: currently refine_coordinates needs to load information about the extractors. However, this prevents the compiler from generating immediate numbers for the bit operations. 

+1, i think the LLVM approach requires some metadata to store a function pointer. Not sure how easy that can be done in Metal... Will update #593  to mention this.

**Comment by yuanming-hu** [comment]
> ore a function pointer. Not sure how easy that can be done in Metal... Will update #593 to mention this.

Yeah, I checked the LLVM IR carefully to make sure the function pointers are getting inlined... In Metal maybe you have to emit `refine_coordinates` functions for each SNode and pass in a function pointer. At least this avoids global memory access to extractors...

**Comment by k-ye** [comment]
> Yeah, I checked the LLVM IR carefully to make sure the function pointers are getting inlined...

Hmm, does that mean you also have a unique listgen function for every SNode? Otherwise how will it work if `refine_coords` is inlined?

**Comment by yuanming-hu** [comment]
> > Yeah, I checked the LLVM IR carefully to make sure the function pointers are getting inlined...
> 
> Hmm, does that mean you also have a unique listgen function for every SNode? Otherwise how will it work if `refine_coords` is inlined?

You can still have a single listgen yet `refine_coordinates` should be passed in as a function pointer. Not sure if Metal supports function pointers. There's no guarentee that the Metal compiler will inline it, but LLVM does inline function pointers according to my experiments.

**Comment by yuanming-hu** [comment]
and yes, as you said one way to make sure you get inlining is having a unique listgen for every SNode...

**Comment by archibate** [comment]
Just passing by, how about to use `#define`?

**Comment by k-ye** [comment]
> Just passing by, how about to use #define?

Yeah, i think that's definitely one of the ways to generate these functions. For now I'd not worry about optimization too much, so we can decide the details later.

**Pull request merged**
