### PR TITLE
[Doc] Update Type system

### PR DESCRIPTION
**Pull request by ltt1598**
Related issue = #

### CODE REVIEW

**Comment by ltt1598** [comment]
Noticed that the code highlight was wrong. I couldn't see the highlight in my local MD editor. 
They should be fixed now.

**Comment by strongoier** [comment]
> Noticed that the code highlight was wrong. I couldn't see the highlight in my local MD editor. They should be fixed now.

You could use https://deploy-preview-3043--jovial-fermat-aa59dc.netlify.app/docs/lang/articles/basic/type to see the preview :-)

A few nits:
- In the `Implicit casts` subsection, what about highlighting the lines actually doing implicit type casting instead of `print`?
- Would you try to rebase your repo from the latest Taichi repo? It seems that the commits shown here are mixed with your last PR.

**Comment by ltt1598** [comment]
Updated.

Is there a way to find the preview link?

**Comment by strongoier** [comment]
> Updated.
> 
> Is there a way to find the preview link?

There is a `netlify` bot in this PR. Search `Browse the preview` in this webpage and you'll find it :-)

**Review by strongoier — APPROVED** [review]
Thanks!

**Pull request merged**
