### PR TITLE
[opengl] Tolerate all errors in with_opengl()

### PR DESCRIPTION
**Pull request by archibate**
Related PR = #864

[[Click here for the format server]](http://kun.csail.mit.edu:31415/)

### CODE REVIEW

**Comment by archibate** [comment]
Btw, why not just bump to v0.6 for OpenGL?

**Comment by yuanming-hu** [comment]
> Btw, why not just bump to v0.6 for OpenGL?

Once a version is released it's hard to erase. We'd better have v0.5.15 as a test. Maybe OpenGL will run into some issue when shipped as a PyPI package.

**Comment by archibate** [comment]
Let's also test the `stable` branch in `v0.6.0` too, wdyt? Btw, don't mind AppVeyor failure, it's not failure, it's cancelled due to PR closed.

**Comment by yuanming-hu** [comment]
Thanks for taking care of this! I mean, we should pretend we are the end-users and test the release mode.

**Pull request merged**
