### PR TITLE
Introduce a temporary boolean constant for benchmarking

### PR DESCRIPTION
**Pull request by xumingkuan**
Related issue id = #656

I'm now using `test_ad_if_mutable` in `test_ad_if.py` for benchmarking. It already reduced the number of statements from 96 to 92 :)

[[Click here for the format server]](http://kun.csail.mit.edu:31415/)

### CODE REVIEW

**Comment by xumingkuan** [comment]
Why does @taichi-gardener modify files I didn't change even if what I clicked is exactly this PR?

**Comment by yuanming-hu** [comment]
> I'm now using `test_ad_if_mutable` in `test_ad_if.py` for benchmarking. It already reduced the number of statements from 96 to 92 :)

Cool! Thanks.

> Why does @taichi-gardener modify files I didn't change even if what I clicked is exactly this PR?

Probably not your fault. I'll take a look at this.

If this PR ready for review? Please simply request a review from me when you are ready. Thanks.

**Comment by xumingkuan** [comment]
It's ready for review.

I googled how to request a review on GitHub, and GitHub Help showed
> In the list of pull requests, click the pull request that you'd like to ask a specific person or a team to review.
> 
> Navigate to Reviewers in the right sidebar.
> 
> To request a review from a suggested person under Reviewers, next to their username, click Request.

However, my right sidebar only shows
> **Reviewers**
> No reviews

without a button to click. Why is that?

**Comment by yuanming-hu** [comment]
> It's ready for review.
> 
> I googled how to request a review on GitHub, and GitHub Help showed
> 
> > In the list of pull requests, click the pull request that you'd like to ask a specific person or a team to review.
> > Navigate to Reviewers in the right sidebar.
> > To request a review from a suggested person under Reviewers, next to their username, click Request.
> 
> However, my right sidebar only shows
> 
> > **Reviewers**
> > No reviews
> 
> without a button to click. Why is that?

interesting... Do you see a gear there? 
Screenshot from 2020-03-25 19-04-06

**Comment by xumingkuan** [comment]
> > It's ready for review.
> > I googled how to request a review on GitHub, and GitHub Help showed
> > > In the list of pull requests, click the pull request that you'd like to ask a specific person or a team to review.
> > > Navigate to Reviewers in the right sidebar.
> > > To request a review from a suggested person under Reviewers, next to their username, click Request.
> > 
> > 
> > However, my right sidebar only shows
> > > **Reviewers**
> > > No reviews
> > 
> > 
> > without a button to click. Why is that?
> 
> interesting... Do you see a gear there?
> Screenshot from 2020-03-25 19-04-06

No, I don't. However, I can re-request a review from you after you self-requested the review and before approving.

**Comment by yuanming-hu** [comment]
I'm reading https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/requesting-a-pull-request-review

**Comment by xumingkuan** [comment]
Oh, I saw this on the website above:

> Pull request authors can't request reviews unless they are either a repository owner or collaborator with write access to the repository.

**Comment by yuanming-hu** [comment]
I'll assume non-Draft PRs are ready for review next time. Thanks for the info.

**Comment by archibate** [comment]
> Oh, I saw this on the website above:
> 
> > Pull request authors can't request reviews unless they are either a repository owner or collaborator with write access to the repository.

I see a little gear on the right of `Reviewers`... was that expected? I think I don't have a write access?

**Comment by yuanming-hu** [comment]
> > Oh, I saw this on the website above:
> > > Pull request authors can't request reviews unless they are either a repository owner or collaborator with write access to the repository.
> 
> I see a little gear on the right of `Reviewers`... was that expected? I think I don't have a write access?

Since you have made significant contributions, your role has been promoted from `Read` to `Triage`, which means you have the right to manage issues and pull requests :-) That's why you can request reviewers.

Ultimately I think you will get `Write` access to the repo. But please keep in mind that with great power comes great responsibilities, and please lead by example :-)

**Pull request merged**
