### PR TITLE
[Opt] [bug] Improve the whole kernel CSE pass (stage 1) and fix a bug

### LINKED ISSUE #793: Strange x86 codegen exception
**Describe the bug**
I was attempting to compute utilization of different arrays in my code and I ran into a weird compilation issue.
Trying to assign to multiple single-element buffers from a scalar variable modified in multiple loops causes a codegen exception.

**To Reproduce**
```python
import taichi as ti
ti.init(arch=ti.x64)

v = ti.var(ti.i32, 100)

a_count = ti.var(ti.i32, ())
b_count = ti.var(ti.i32, ())

@ti.kernel
def test():
    count = 0
    for i in v:
        count += 1
    a_count[None] = count
    
    # without the following lines, this program works.
    # with them, however, compilation fails.
    count = 0
    for i in v:
        count += 1
    b_count[None] = count

test()
```

The error is:
```
[I 04/15/20 14:08:33.701] [llvm_context.cpp:get_data_type@90] generic
[E 04/15/20 14:08:33.701] [llvm_context.cpp:get_data_type@91] Not supported.
```
followed by a stacktrace that ends with `taichi::lang::TaichiLLVMContext::get_data_type(taichi::lang::DataType)`.

### PR DESCRIPTION
**Pull request by xumingkuan**
Related issue = #1178

Also fixes #793 

benchmark20200610

[[Click here for the format server]](http://kun.csail.mit.edu:31415/)

### CODE REVIEW

**Comment by xumingkuan** [comment]
Breaking tests... Will debug after dinner.

**Comment by yuanming-hu** [comment]
No rush. I decided to not talk about `dynamic` tomorrow anyway :-) As long as we fix before the v0.6.9 we are good.

**Comment by xumingkuan** [comment]
Test case:
```python
@ti.all_archs
def test_atomic_xor_expr_evaled():
    ti.init(print_ir=True)
    c = ti.var(ti.i32)
    step = 42

    ti.root.place(c)

    @ti.kernel
    def func():
        c[None] = 1023
        for i in range(10):
            # this is an expr with side effect, make sure it's not optimized out.
            ti.atomic_xor(c[None], 2**i)

    func()

    assert c[None] == 0
```

Log:
```
before CSE:
kernel {
  <i32 x1> $0 = const [2]
  <i32 x1> $1 = const [1023]
  <i32*x1> $2 = global ptr [S2place_i32], index [] activate=true
  <gen*x1> $3 = get root
  <i32 x1> $4 = linearized(ind {}, stride {})
  <gen*x1> $5 = [S0root][root]::lookup($3, $4) activate = false
  <gen*x1> $6 = get child [S0root->S1dense] $5
  <i32 x1> $7 = linearized(ind {}, stride {})
  <gen*x1> $8 = [S1dense][dense]::lookup($6, $7) activate = false
  <i32*x1> $9 = get child [S1dense->S2place_i32] $8
  <i32 x1> $10 = shuffle $9[0]
  <i32 x1> $11 : global store [$10 <- $1]
  <i32 x1> $12 = const [0]
  <i32 x1> $13 = const [10]
  $14 : for in range($12, $13, step 1) {
    <i32 x1> $15 = loop $14 index 0
    <i32 x1> $16 = pow $0 $15
    <i32*x1> $17 = global ptr [S2place_i32], index [] activate=true
    <gen*x1> $18 = get root
    <i32 x1> $19 = linearized(ind {}, stride {})
    <gen*x1> $20 = [S0root][root]::lookup($18, $19) activate = false
    <gen*x1> $21 = get child [S0root->S1dense] $20
    <i32 x1> $22 = linearized(ind {}, stride {})
    <gen*x1> $23 = [S1dense][dense]::lookup($21, $22) activate = false
    <i32*x1> $24 = get child [S1dense->S2place_i32] $23
    <i32 x1> $25 = shuffle $24[0]
    <i32 x1> $26 = atomic bit_xor($25, $16)
  }
}
after CSE:
kernel {
  <i32 x1> $0 = const [2]
  <i32 x1> $1 = const [1023]
  <i32*x1> $2 = global ptr [S2place_i32], index [] activate=true
  <gen*x1> $3 = get root
  <i32 x1> $4 = linearized(ind {}, stride {})
  <gen*x1> $5 = [S0root][root]::lookup($3, $4) activate = false
  <gen*x1> $6 = get child [S0root->S1dense] $5
  <gen*x1> $8 = [S1dense][dense]::lookup($6, $4) activate = false
  <i32*x1> $9 = get child [S1dense->S2place_i32] $8
  <i32 x1> $10 = shuffle $9[0]
  <i32 x1> $11 : global store [$10 <- $1]
  <i32 x1> $12 = const [0]
  <i32 x1> $13 = const [10]
  $14 : for in range($12, $13, step 1) {
    <i32 x1> $15 = loop $14 index 0
    <i32 x1> $16 = pow $0 $15
    <i32*x1> $17 = global ptr [S2place_i32], index [] activate=true
    <i32 x1> $26 = atomic bit_xor($10, $16)
  }
}
[I 06/07/20 20:48:09.511] [compile_to_offloads.cpp:taichi::lang::irpass::co
mpile_to_offloads::<lambda_44aeda62b30289419801af51381ceafc>::operator ()@2
1] Simplified II:
kernel {
  <i32 x1> $0 = const [2]
  <i32 x1> $1 = const [1023]
  <i32*x1> $2 = global ptr [S2place_i32], index [] activate=true
  <gen*x1> $3 = get root
  <i32 x1> $4 = const [0]
  <gen*x1> $5 = [S0root][root]::lookup($3, $4) activate = false
  <gen*x1> $6 = get child [S0root->S1dense] $5
  <gen*x1> $7 = [S1dense][dense]::lookup($6, $4) activate = false
  <i32*x1> $8 = get child [S1dense->S2place_i32] $7
  <i32 x1> $9 : global store [$8 <- $1]
  <i32 x1> $10 = const [10]
  $11 : for in range($4, $10, step 1) {
    <i32 x1> $12 = loop $11 index 0
    <i32 x1> $13 = pow $0 $12
    <i32*x1> $14 = global ptr [S2place_i32], index [] activate=true
    <i32 x1> $15 = atomic bit_xor($8, $13)
  }
}
[I 06/07/20 20:48:09.512] [compile_to_offloads.cpp:taichi::lang::irpass::co
mpile_to_offloads::<lambda_44aeda62b30289419801af51381ceafc>::operator ()@2
1] Access flagged II:
kernel {
  <i32 x1> $0 = const [2]
  <i32 x1> $1 = const [1023]
  <i32*x1> $2 = global ptr [S2place_i32], index [] activate=false
  <gen*x1> $3 = get root
  <i32 x1> $4 = const [0]
  <gen*x1> $5 = [S0root][root]::lookup($3, $4) activate = false
  <gen*x1> $6 = get child [S0root->S1dense] $5
  <gen*x1> $7 = [S1dense][dense]::lookup($6, $4) activate = false
  <i32*x1> $8 = get child [S1dense->S2place_i32] $7
  <i32 x1> $9 : global store [$8 <- $1]
  <i32 x1> $10 = const [10]
  $11 : for in range($4, $10, step 1) {
    <i32 x1> $12 = loop $11 index 0
    <i32 x1> $13 = pow $0 $12
    <i32*x1> $14 = global ptr [S2place_i32], index [] activate=false
    <i32 x1> $15 = atomic bit_xor($8, $13)
  }
}
[I 06/07/20 20:48:09.513] [compile_to_offloads.cpp:taichi::lang::irpass::co
mpile_to_offloads::<lambda_44aeda62b30289419801af51381ceafc>::operator ()@2
1] Constant folded:
kernel {
  <i32 x1> $0 = const [2]
  <i32 x1> $1 = const [1023]
  <i32*x1> $2 = global ptr [S2place_i32], index [] activate=false
  <gen*x1> $3 = get root
  <i32 x1> $4 = const [0]
  <gen*x1> $5 = [S0root][root]::lookup($3, $4) activate = false
  <gen*x1> $6 = get child [S0root->S1dense] $5
  <gen*x1> $7 = [S1dense][dense]::lookup($6, $4) activate = false
  <i32*x1> $8 = get child [S1dense->S2place_i32] $7
  <i32 x1> $9 : global store [$8 <- $1]
  <i32 x1> $10 = const [10]
  $11 : for in range($4, $10, step 1) {
    <i32 x1> $12 = loop $11 index 0
    <i32 x1> $13 = pow $0 $12
    <i32*x1> $14 = global ptr [S2place_i32], index [] activate=false
    <i32 x1> $15 = atomic bit_xor($8, $13)
  }
}
[I 06/07/20 20:48:09.515] [compile_to_offloads.cpp:taichi::lang::irpass::co
mpile_to_offloads::<lambda_44aeda62b30289419801af51381ceafc>::operator ()@2
1] Offloaded:
kernel {
  $0 = offloaded  {
    <i32 x1> $1 = const [2]
    <i32 x1> $2 = const [1023]
    <i32*x1> $3 = global ptr [S2place_i32], index [] activate=false
    <gen*x1> $4 = get root
    <i32 x1> $5 = const [0]
    <gen*x1> $6 = [S0root][root]::lookup($4, $5) activate = false
    <gen*x1> $7 = get child [S0root->S1dense] $6
    <gen*x1> $8 = [S1dense][dense]::lookup($7, $5) activate = false
    <i32*x1> $9 = get child [S1dense->S2place_i32] $8
    <i32*x1> $10 : global store [$9 <- $2]
    <i32 x1> $11 = const [10]
  }
  $12 = offloaded range_for(0, 10) block_dim=adaptive {
    <i32 x1> $13 = loop $12 index 0
    <i32 x1> $14 = const [2]
    <i32 x1> $15 = pow $14 $13
    <i32*x1> $16 = global ptr [S2place_i32], index [] activate=false
    <i32 x1> $17 = atomic bit_xor($9, $15)
  }
}
[E 06/07/20 20:48:09.516] [verify.cpp:taichi::lang::IRVerifier::basic_verif
y@39] stmt 17 cannot have operand 9.
```

I think this issue should be fixed in `offload` rather than avoid doing CSE here. WDYT?

**Comment by xumingkuan** [comment]
> Thank you! LGTM. Maybe this also fixes #793?

Yes. I think the only case we store a pointer is storing `GlobalPtrStmt` in `offload`.

**Pull request merged**
