### PR TITLE
[doc] Document TaichiCon

### PR DESCRIPTION
**Pull request by yuanming-hu**
@JusperLee As promised here I briefly document how TaichiCon 0 was organized... I'll update it with more details tomorrow.

[[Click here for the format server]](http://kun.csail.mit.edu:31415/)

### CODE REVIEW

**Comment by k-ye** [comment]
> I don't know if we have a unified slide template for talk? I think that every speaker using TaiChi's unified template may look better.

Fun fact: at least three slide tools were used in the last TaichiCon, namely, Microsoft PPT, Keynotes and Google Slides...

**Comment by archibate** [comment]
> > I don't know if we have a unified slide template for talk? I think that every speaker using TaiChi's unified template may look better.
> 
> Fun fact: at least three slide tools were used in the last TaichiCon, namely, Microsoft PPT, Keynotes and Google Slides...

In fact, I'm using LibreOffice... and `.ppt` is not it's native format therefore seems doesn't render correctly in MS PPT... So, as you see, it's hard to unify, I guess it's hard to install MSPPT on OS X... The best way to help user get unified format is to convert our slides into `png`/`pdf` for each slide after the TaichiCon ends, wdyt?

**Comment by k-ye** [comment]
> The best way to help user get unified format is to convert our slides into png/pdf for each slide after the TaichiCon ends, wdyt?

I think @JusperLee was talking more on the theme, not the file format.. But i agree on the PDF format.

<s>We probably should all just use LaTex (but then very few speaking guests would sign up...)</s>

**Comment by JusperLee** [comment]
> > The best way to help user get unified format is to convert our slides into png/pdf for each slide after the TaichiCon ends, wdyt?
> 
> I think @JusperLee was talking more on the theme, not the file format.. But i agree on the PDF format.

Yes, I mainly talk about the unification of slide theme, just like the reports in some meetings.

**Comment by JusperLee** [comment]
I can design templates for different ppt formats (LibreOffice, MSPPT, etc.)

**Comment by yuanming-hu** [comment]
> I can design templates for different ppt formats (LibreOffice, MSPPT, etc.)

I actually think enforcing people to use a unified template might not be a good option. I never use templates provided by any conferences such as CVPR/SIGGRAPH. Speakers should have the freedom to use their own template that suits their contents. I think as long as people provide their final files in PDF, we are good.

We can, of course, suggest speakers adding `TaichiCon XX` to their first slide.

Contents are more important than formats :-)

**Comment by JusperLee** [comment]
Yes, I agree with you. I was made a little stubborn by the graduation design template recently. @yuanming-hu

**Comment by yuanming-hu** [comment]
Merging this initial draft for now. If there's any update we'll do in future PRs. Given that people are getting occupied recently due to GAMES 201, I'd suggest hosting TaichiCon 1 sometime in July.

**Pull request merged**
