### PR TITLE
[ci] Added vulkan release in linux

### PR DESCRIPTION
**Pull request by Leonz5288**
Related issue = #

### CODE REVIEW

**Review by ailzhang — APPROVED** [review]
LGTM, thanks! 
Btw have you tested this locally? ;) e.g. make sure the wheel built in this way passes all vulkan tests :D

**Comment by Leonz5288** [comment]
> LGTM, thanks!
> Btw have you tested this locally? ;) e.g. make sure the wheel built in this way passes all vulkan tests :D

Tested!

**Review by AmesingFlank — APPROVED** [review]
Thanks!

**Comment by Leonz5288** [comment]
@ailzhang Can you help me merge this please? GPU is timing out again while this PR only changes linux release.

**Comment by ailzhang** [comment]
aha sorry I just saw this - btw next time if you see an unrelated test failure/flaky test, please feel free to open a github issue so that we can keep track of them! :D 
cc: @qiao-bo , this might be an example of GPU flaky test but we unfortunately missed it :P

**Comment by qiao-bo** [comment]
> aha sorry I just saw this - btw next time if you see an unrelated test failure/flaky test, please feel free to open a github issue so that we can keep track of them! :D
> cc: @qiao-bo , this might be an example of GPU flaky test but we unfortunately missed it :P

@ailzhang, The GPU test looks good to me, which commit has the time out message?

**Pull request closed without merging**
