### PR TITLE
[aot] C-API opengl runtime interop

### PR DESCRIPTION
**Pull request by damnkk**

### CODE REVIEW

**Comment by bobcao3** [comment]
Please leave a bit more detail in the title or description of what's being changed

**Comment by bobcao3** [comment]
Is this a duplicate of #6984 ?

**Comment by damnkk** [comment]
> 

Sorry I didn't make that clear.  The hole thing is add the opengl interop for taichi-aot-demo, There were some unexpected errors in the whole PR in  #6984.   so I considered splitting #6984  and committing the modified part of taichi in this pr first.

**Comment by damnkk** [comment]
> Is this a duplicate of #6984 ?



> Is this a duplicate of #6984 ?

Sorry I didn't make that clear. The hole thing is add the opengl interop for taichi-aot-demo, There were some unexpected errors in the whole PR in #6984 . so I considered splitting #6984  and committing the modified part of taichi in this pr first.

**Review by PENGUINLIONG — APPROVED** [review]
Thank you!

**Pull request merged**
