### PR TITLE
Frontend kernel/function structure checking

### PR DESCRIPTION
**Pull request by xumingkuan**
Related issue id = #536 

- [x] Disallow return in ti.kernel
- [ ] Enforce exactly one return in ti.func
- [x] Disallow function definition in ti.kernel and ti.func

### CODE REVIEW

**Comment by archibate** [comment]
Oh no!

**Comment by archibate** [comment]
I think the second TODO entry is unnecessary now... See #543.

**Comment by archibate** [comment]
Sorry for the build fail, it's my fault. Please merge master after #546 merged to fix...

**Comment by archibate** [comment]
Looks generally good except some problem I commented, can you make a improve on this?

**Comment by archibate** [comment]
https://github.com/taichi-dev/taichi/blob/cb551f3c9b448176d83ae247ad6ddbe91365311a/python/taichi/lang/kernel.py#L272-L274

**Comment by xumingkuan** [comment]
Should we disallow them in a single file, i.e., in kernel.py or transformer.py?

**Pull request merged**
