### PR TITLE
修改 READM.md ,添加 llvm8.0.0 源码安装 命令以及 taichi cmake 构建命令,并在 mac 系统上成功编译,…

### PR DESCRIPTION
**Pull request by davidxiaozhi**
修改 READM.md ,添加 llvm8.0.0 源码安装 命令以及 taichi cmake 构建命令,并在 mac 系统上成功编译,…解决 master  mac 系统构建失败问题,方便在 mac 系统上基于源码构建 taichi

### CODE REVIEW

**Comment by davidxiaozhi** [comment]
Traceback (most recent call last):
  File "build.py", line 35, in <module>
    assert False, "Missing environment variable PYPI_PWD"
AssertionError: Missing environment variable PYPI_PWD
The command "ti test && cd python && $PYTHON build.py upload" exited with 1

**Comment by davidxiaozhi** [comment]
@yuanming-hu  构建失败,我查看了一下原因 是 构建环境没有设置环境变量 PYPI_PWD

**Comment by yuanming-hu** [comment]
Hi @davidxiaozhi , thanks for the PR! However, developer installation process on Mac OS X is already in the documentation: https://taichi.readthedocs.io/en/latest/dev_install.html#developer-installation. The README.md file is for end-users only, who are suggested to install Taichi with `pip`. So I'm sorry that this PR will not get merged into master.

However, we do need your help: as you reported, currently CI fails if the user does not set `PYPI_PWD`. The desired behavior is to report success as long as the tests passed. If you offer to help with this, that would be great!

**Comment by yuanming-hu** [comment]
Hi @davidxiaozhi , thanks for the PR! However, developer installation process on Mac OS X is already in the documentation: https://taichi.readthedocs.io/en/latest/dev_install.html#developer-installation. The README.md file is for end-users only, who are suggested to install Taichi with `pip`. So I'm sorry that this PR will not get merged into master.

However, we do need your help: as you reported, currently CI fails if the user does not set `PYPI_PWD`. The desired behavior is to report success as long as the tests passed. If you offer to help with this, that would be great!

**Pull request closed without merging**
