### PR TITLE
OpenGL external array access (stage 2.1.2)

### PR DESCRIPTION
**Pull request by archibate**
Related issue id = #492

### CODE REVIEW

**Comment by archibate** [comment]
Sleepy now Zzz... enjoy code reviewing :)

**Comment by archibate** [comment]
Hello?

**Comment by archibate** [comment]
I rebased this PR to #594. Please merge that before merge this.

**Comment by archibate** [comment]
Should we merge into taichi-dev:opengl instead of taichi-dev:master for not rushing the v6.0 release?

**Comment by yuanming-hu** [comment]
> Should we merge into taichi-dev:opengl instead of taichi-dev:master for not rushing the v6.0 release?

We have plenty of time before we release v0.6. Only merging into taichi-dev:opengl might lead to other issues when merging opengl into master. Let's directly make these parts of the master branch.

**Pull request merged**
