### PR TITLE
[opengl] Move OpenGL backend onto Gfx runtime

### PR DESCRIPTION
**Pull request by bobcao3**

### CODE REVIEW

**Review by qiao-bo — APPROVED** [review]
looks great! so much cleaner. So opengl_api is considered part of device code?

**Comment by bobcao3** [comment]
> looks great! so much cleaner. So opengl_api is considered part of device code?

Yes, after the removal of the runtime part of the code.

**Review by k-ye — APPROVED** [review]
LGTM!

**Comment by bobcao3** [comment]
Seems to be a driver bug for Nvidia OpenGL #5259, disabled the polar decomposition test for OpenGL

**Pull request merged**
