### PR TITLE
[release] v0.7.20

### PR DESCRIPTION
**Pull request by xumingkuan**
Full changelog:
   - [ir] Remove "kernel" when printing ReturnStmt (#2353) (by **xumingkuan**)
   - [misc] Support Python 3.9 (#2274) (by **Derived Cat**)
   - [opt] Simplify modulo POT (Stage 1) (#2352) (by **xumingkuan**)
   - [opt] Slightly simplify algebraic simplification (#2337) (by **xumingkuan**)
   - [Refactor] Add a class Callable to unify Kernel and Function (#2338) (by **xumingkuan**)
   - [ir] Rename KernelReturnStmt to ReturnStmt (#2349) (by **xumingkuan**)
   - [lang] Support std::optional and enum classes in the serializer (#2350) (by **Ye Kuang**)
   - [IR] Support DiffRange shl (#2346) (by **Kenneth Lozes**)
   - [Docker] Fix the docker build by bumping CMake version in Dockerfile (#2348) (by **Chengchen(Rex) Wang**)
   - [ir] [test] Add tests for make_block_local (#2343) (by **Ye Kuang**)
   - [ir] Add ArithmeticInterpretor to evaluate a subset of CHI IR (#2342) (by **Ye Kuang**)
   - [opt] Better encapsulate BLS bounds (#2341) (by **Ye Kuang**)
   - [Example] cornell_box: Remove unused sphere (#2334) (by **Aaryaman Vasishta**)
   - [opt] Simplify replace_statements and improve demote_dense_struct_fors (#2335) (by **xumingkuan**)
   - [refactor] [test] Reorganize tests' file structure (#2336) (by **xumingkuan**)

### CODE REVIEW

**Review by k-ye — APPROVED** [review]
LGTM!

**Comment by xumingkuan** [comment]
@k-ye Could you please re-trigger the CI? Looks like #828 is happening again...

**Comment by k-ye** [comment]
Fixed :-) let's merge it tmr

**Comment by xumingkuan** [comment]
Looks like the CI passed just now so I merged it :)

**Pull request merged**
