### PR TITLE
[refactor] Remove dependency on get_current_program() in lang::BinaryOpExpression

### PR DESCRIPTION
**Pull request by PGZXB**
Related issue = #3955

I think that the method of removing dependency on get_current_program() in lang::BinaryOpExpression is not best, which causes that the `expr_truediv` needs a additional `default_fp` param except `lhs` and `rhs`, but I cannot think of a better idea.

### CODE REVIEW

**Review by strongoier — COMMENTED** [review]
Can we add a parameter for `type_check()` instead?

**Comment by PGZXB** [comment]
> Can we add a parameter for `type_check()` instead?
This is a feasible solution. However, because `type_check()` is virtual function inherited from `Expression`, adding a parameter for`type_check()` causes that most of subclasses' implementation of this function have a unnecessary parameter. Will this cause confusion?

**Comment by strongoier** [comment]
> This is a feasible solution. However, because `type_check()` is virtual function inherited from `Expression`, adding a parameter for`type_check()` causes that most of subclasses' implementation of this function have a unnecessary parameter. Will this causes confusion?

This is OK for now because we will switch into an individual pass for typechecking (https://github.com/taichi-dev/taichi/issues/4146), where we will have easy access to the configurations.

**Comment by PGZXB** [comment]
See #4242

**Pull request closed without merging**
