### PR TITLE
[refactor] Remove legacy C++ frontend macros

### LINKED ISSUE #2036: [refactor] Remove legacy C++ frontend macros
**What to refactor**

The old C++ frontend is abandoned after we migrate to Python. A few related macros can be removed:  
https://github.com/taichi-dev/taichi/blob/414b0ebe790a4cd66d8635a6c391eb9a88ed99c4/taichi/ir/frontend.h#L64-L79

**Additional comments**
This issue can be done by completed by simply deleting the code above. Newcomer only :-)

### PR DESCRIPTION
**Pull request by Robslhc**
Related issue = close #2036 

[[Click here for the format server]](http://kun.csail.mit.edu:31415/)

----

### CODE REVIEW

**Comment by Robslhc** [comment]
It seems that my modification has failed the CI test. I open this PR to get myself familiar with the PR workflow. Since I'm not so familiar with the source code of taichi, I'm wondering if there is any suggestion on how to check and fix it. @yuanming-hu @k-ye @xumingkuan @archibate

**Comment by xumingkuan** [comment]
It seems that the CI test is being retriggered now. Welcome to the Taichi developer community!

**Comment by xumingkuan** [comment]
There's a mysterious bug that test_abs fails randomly on Windows: https://github.com/taichi-dev/taichi/issues/828#issuecomment-618089653

For now, we can just retrigger the CI again (by pushing an empty commit onto this branch, for example).

**Comment by Robslhc** [comment]
> There's a mysterious bug that test_abs fails randomly on Windows: [#828 (comment)](https://github.com/taichi-dev/taichi/issues/828#issuecomment-618089653)
> 
> For now, we can just retrigger the CI again (by pushing an empty commit onto this branch, for example).

Get it! Thanks!

**Review by xumingkuan — APPROVED** [review]
LGTM, thanks!

**Pull request merged**
