### PR TITLE
[Perf] Make Python-scope accessors 8x faster

### PR DESCRIPTION
**Pull request by archibate**
Related issue = #1715

[[Click here for the format server]](http://kun.csail.mit.edu:31415/)

----
@KLozes Does this fix the performance issue? My card doesn't support unified memory, so I can't obtain any difference before/after this PR, sorry :(

### CODE REVIEW

**Comment by KLozes** [comment]
Thanks @archibate. This is exactly what I was going to try. Sadly, I am not seeing any speed up though :/.

**Comment by archibate** [comment]
It seems that the main overhead of snode accessors is not `synchronize()` but something else.
I can confirm sync is avoided in this PR:
```py
import taichi as ti
import time
ti.init(arch=ti.cuda)

c = ti.field(float, ())

#@ti.kernel
def set_c():
    c[None] = 1

set_c()
t = time.time()
for i in range(100000):
    set_c()
print(time.time() - t)
```
this PR:
```
[Taichi] mode=development
[Taichi] preparing sandbox at /tmp/taichi-cr8hd7bx
[Taichi] <dev mode>, llvm 10.0.0, commit bed62d74, linux, python 3.8.3
[Taichi] Starting on arch=cuda
[Taichi] materializing...
[W 08/18/20 13:57:53.538] [program.cpp:synchronize@462] Program::synchronize() called
3.287529945373535
[W 08/18/20 13:57:56.993] [program.cpp:synchronize@462] Program::synchronize() called
[W 08/18/20 13:57:56.993] [program.cpp:synchronize@462] Program::synchronize() called
```

master:
```
... (tons of duplicate message)
[W 08/18/20 13:55:35.491] [program.cpp:synchronize@462] Program::synchronize() called
[W 08/18/20 13:55:35.491] [program.cpp:synchronize@462] Program::synchronize() called
[W 08/18/20 13:55:35.491] [program.cpp:synchronize@462] Program::synchronize() called
[W 08/18/20 13:55:35.491] [program.cpp:synchronize@462] Program::synchronize() called
[W 08/18/20 13:55:35.491] [program.cpp:synchronize@462] Program::synchronize() called
[W 08/18/20 13:55:35.491] [program.cpp:synchronize@462] Program::synchronize() called
[W 08/18/20 13:55:35.491] [program.cpp:synchronize@462] Program::synchronize() called
[W 08/18/20 13:55:35.491] [program.cpp:synchronize@462] Program::synchronize() called
[W 08/18/20 13:55:35.491] [program.cpp:synchronize@462] Program::synchronize() called
[W 08/18/20 13:55:35.491] [program.cpp:synchronize@462] Program::synchronize() called
[W 08/18/20 13:55:35.491] [program.cpp:synchronize@462] Program::synchronize() called
[W 08/18/20 13:55:35.491] [program.cpp:synchronize@462] Program::synchronize() called
[W 08/18/20 13:55:35.491] [program.cpp:synchronize@462] Program::synchronize() called
[W 08/18/20 13:55:35.491] [program.cpp:synchronize@462] Program::synchronize() called
[W 08/18/20 13:55:35.491] [program.cpp:synchronize@462] Program::synchronize() called
[W 08/18/20 13:55:35.492] [program.cpp:synchronize@462] Program::synchronize() called
[W 08/18/20 13:55:35.492] [program.cpp:synchronize@462] Program::synchronize() called
[W 08/18/20 13:55:35.492] [program.cpp:synchronize@462] Program::synchronize() called
[W 08/18/20 13:55:35.492] [program.cpp:synchronize@462] Program::synchronize() called
[W 08/18/20 13:55:35.492] [program.cpp:synchronize@462] Program::synchronize() called
^CTraceback (most recent call last):
  File "a.py", line 14, in <module>
    set_c()
  File "a.py", line 9, in set_c
    c[None] = 1
  File "/home/bate/Develop/taichi/python/taichi/lang/util.py", line 212, in wrapped
    return func(*args, **kwargs)
  File "/home/bate/Develop/taichi/python/taichi/lang/expr.py", line 52, in __setitem__
    self.setter(value, *key)
  File "/home/bate/Develop/taichi/python/taichi/lang/expr.py", line 90, in setter
    snode.write_float(key, value)
KeyboardInterrupt
[W 08/18/20 13:55:35.502] [program.cpp:synchronize@462] Program::synchronize() called
[W 08/18/20 13:55:35.502] [program.cpp:synchronize@462] Program::synchronize() called
```

**Comment by archibate** [comment]
I found the overhead is actually due to Python:
```py
@python_scope
def __setitem__(self, key, value):
        #impl.get_runtime().materialize()
        #self.initialize_accessor()
        #if key is None:
            #key = ()
        #if not isinstance(key, (tuple, list)):
            #key = (key, )
        #assert len(key) == len(self.shape)
        #key = key + (0, ) * (taichi_lang_core.get_max_num_indices() - len(key))
        key = (0, ) * taichi_lang_core.get_max_num_indices()
        self.setter(value, *key)
```
After commenting these lines and initialize them once outside, the performance of `c[None] = 1` gets close to the kernel `set_c`.

**Comment by archibate** [comment]
Hi @KLozes, I found that the bottleneck is at `assert len(key) == len(self.shape)`, while `self.shape` is relatively slow. So I cached the result of `self.shape` and it runs ~4x faster on my end! :rocket: See `misc/demo_accessor_overhead.py`.

**Comment by archibate** [comment]
What's more, it seems that if I remove the `@python_scope` decorator, it's becoming even faster! (3.1 us -> 1.75 us)

**Comment by KLozes** [comment]
Uh oh. My original example still hasn't sped up at all. In fact the problem is worse than I realized. With set_c using an snode accessor, the loop takes ~14 seconds. With set_c as a kernel it takes ~1.6 seconds. So the copy kernel is still taking ~3x longer, And theres a ton of host side overhead. Weird!

with accessor
```
[Taichi] mode=development
[Taichi] preparing sandbox at /tmp/taichi-r_umt416
[Taichi] <dev mode>, llvm 10.0.0, commit 82429d3a, linux, python 3.6.9
[Taichi] Starting on arch=cuda
[Taichi] materializing...
13.960518836975098
CUDA Profiler
=========================================================================
[      %     total   count |      min       avg       max   ] Kernel name
[ 79.91%   3.125 s  10001x |    0.114     0.312     1.683 ms] copy_c4_0_kernel_1_range_for
[ 20.09%   0.786 s  10001x |    0.074     0.079     0.225 ms] copy2_c6_0_kernel_2_range_for
-------------------------------------------------------------------------
[100.00%] Total kernel execution time:   3.911 s   number of records: 2
=========================================================================
```


with kernel
```
[Taichi] mode=development
[Taichi] preparing sandbox at /tmp/taichi-4vzll0kd
[Taichi] <dev mode>, llvm 10.0.0, commit 82429d3a, linux, python 3.6.9
[Taichi] Starting on arch=cuda
[Taichi] materializing...
1.6192858219146729
CUDA Profiler
=========================================================================
[      %     total   count |      min       avg       max   ] Kernel name
[ 49.21%   0.792 s  10001x |    0.077     0.079     0.783 ms] copy_c4_0_kernel_1_range_for
[ 49.14%   0.791 s  10001x |    0.077     0.079     0.705 ms] copy2_c6_0_kernel_2_range_for
[  1.65%   0.027 s  10001x |    0.002     0.003     0.273 ms] set_c_c8_0_kernel_0_serial
-------------------------------------------------------------------------
[100.00%] Total kernel execution time:   1.610 s   number of records: 3
=========================================================================
```


``` python 
import taichi as ti
import time

real = ti.f32
ti.init(arch=ti.cuda, default_fp=real, kernel_profiler=True)

N = 1024

a = ti.field(real)
b = ti.field(real)
c = ti.field(real, ())

ti.root.dense(ti.ij, N).place(a)
ti.root.dense(ti.ij, N).place(b)

@ti.kernel
def copy():
    for I in ti.grouped(a):
        b[I] = a[I]

@ti.kernel
def copy2():
    for I in ti.grouped(a):
        b[I] = a[I]

#@ti.kernel
def set_c(cin: float):
    c[None] = cin

set_c(1.0)
copy()
copy2()

t = time.time()
for i in range(10000):
    set_c(1.0)
    copy()
    copy2()

print(time.time()-t)

ti.kernel_profiler_print()
```

**Comment by archibate** [comment]
I see, so the issue is not on the Python side.. Will open another PR to figure out the reason.

**Pull request closed without merging**
