### PR TITLE
move test_pointer3 assert out of loop

### PR DESCRIPTION
**Pull request by KLozes**
test_pointer3 takes like 10 minutes if the assert is done every iteration, so I moved it outside the loop.

### CODE REVIEW

**Comment by yuanming-hu** [comment]
Interesting... I feel like this may need a bit more investigation: does a recent change make the accessor run much slower? I'm checking out old versions to confirm.

If not, maybe we should reduce the number 100 and `n=16` to make this case run faster - we still would like to test its behavior at each iteration...

**Comment by yuanming-hu** [comment]
In v0.5.13 it finishes within a few seconds. v0.6.0 takes forever...

**Comment by KLozes** [comment]
I agree, there must be something going on with the accessor. Though I think in this case checking the data only at the end is sufficient since we check against the initial condition instead of just the previous iteration. And a any bug in GC or something tends to corrupt data progressively with more iterations.

**Comment by yuanming-hu** [comment]
I did a binary search and finally spot what's wrong. Should be fixed in #965 ...

**Comment by KLozes** [comment]
Cool thanks! No need for this pr then

**Pull request closed without merging**
