### PR TITLE
[javascript] [cuda] Only spawn memory allocator daemon when CUDA is enabled (JS 8/n)

### PR DESCRIPTION
**Pull request by AmesingFlank**
Related issue = #3781

The daemon is only used for allocation memory in CUDA. (Actually, do we even use that in CUDA anymore, we have switched completely to pre-allocation right?)

### CODE REVIEW

**Comment by qiao-bo** [comment]
Memory allocation in CUDA/CPU has been switched to using preallocated. The memory pool is not used IIUC. ;/

**Comment by AmesingFlank** [comment]
> Memory allocation in CUDA/CPU has been switched to using preallocated. The memory pool is not used IIUC. ;/

Right! Thanks for confirming.
Actually I think this memory pool is still used for allocating things like host-side result buffer. But we should consider removing the daemon entirely.
Created #4135 to track this.

**Review by ailzhang — APPROVED** [review]
LGTM!

**Comment by AmesingFlank** [comment]
CI on macOS keeps failing.. interesting. Not sure why this change would affect macOS. Will investigate.

**Comment by feisuzhu** [comment]
Closing ancient PR

**Pull request closed without merging**
