### PR TITLE
[aot] Properly copy import library

### PR DESCRIPTION
**Pull request by PENGUINLIONG**
Issue: 

### <samp>🤖 Generated by Copilot at 830a529</samp>

Fix Windows import errors by including `.lib` files in Python package. Modify `setup.py` to copy `.lib` files from CMake output.

### <samp>🤖 Generated by Copilot at 830a529</samp>

*  Include `.lib` files in the Python package to fix Windows import errors ([link](https://github.com/taichi-dev/taichi/pull/8049/files?diff=unified&w=0#diff-60f61ab7a8d1910d86d9fda2261620314edcae5894d5aaa236b821c7256badd7L185-R185))

### CODE REVIEW

**Comment by ailzhang** [comment]
@PENGUINLIONG what static libraries do we need to copy over in this case?

**Comment by PENGUINLIONG** [comment]
@ailzhang The import library to the DLL. See https://learn.microsoft.com/en-us/cpp/build/reference/using-an-import-library-and-export-file?view=msvc-170.

**Review by ailzhang — APPROVED** [review]
LGTM!

**Pull request closed without merging**
