### PR TITLE
[mesh] Remove link hints from ti.Mesh

### PR DESCRIPTION
**Pull request by BillXu2000**
Related issue = #3608

All the necessary relation information will be detected in ast transformer.
Relations that has not been stored in fields will be fetched from patcher.

I am not sure whether it is appropriate to store mesh information in compile context and update mesh information in kernel_impl.py.

### CODE REVIEW

**Review by k-ye — COMMENTED** [review]
Hmm, could you make this a separate AST processing pass? The current one is purely for transforming that to C++ AST, which isn't very suitable for blending in Mesh logic

**Comment by BillXu2000** [comment]
Updated. There is now a separate AST processing pass to detect mesh relation visiting, though only some simple cases of detections are handled. For complicated situations, users need to manually tell compiler which relations are needed.

**Review by k-ye — APPROVED** [review]
Thanks for separating the AST pass. LGTM from my side!

**Review by g1n0st — APPROVED** [review]
LGTM!

**Pull request merged**
