### PR TITLE
[aot] AOT compat test

### PR DESCRIPTION
**Pull request by damnkk**

### CODE REVIEW

**Review by PENGUINLIONG — APPROVED** [review]
lgtm

**Review by PENGUINLIONG — APPROVED** [review]

**Review by ailzhang — COMMENTED** [review]
nit: in case that a known breakage happens, which script should we run to re-generate this tcm?

**Comment by PENGUINLIONG** [comment]
> nit: in case that a known breakage happens, which script should we run to re-generate this tcm? 

@ailzhang The TCM is currently manually unzipped, had the `required_caps` field removed and again packed up. I'm not quite sure if there is an expected pattern to break the thing. Or maybe we should automate the packing-edit-unpacking process in a python script?

**Comment by ailzhang** [comment]
@PENGUINLIONG yup it'll be nice to automate the process since anyone who fails this test in CI can have an idea what to do next ;)

**Pull request closed without merging**
