### PR TITLE
[example] Ti-example: instant ngp renderer

### PR DESCRIPTION
**Pull request by Linyou**
Add a file for ti-example: instant ngp renderer.
For more details, please visit [https://github.com/Linyou/taichi-ngp-renderer](https://github.com/Linyou/taichi-ngp-renderer).

### CODE REVIEW

**Comment by neozhaoliang** [comment]
This is the error when running on my laptop (ubuntu22.04 + intel(GT2) card), have no idea what it's about:

```
Loading model from ./npy_models/lego.npy
GridEncoding: base resolution: 16, log scale per level:1.31951 feature numbers per level: 2 maximum parameters per level: 524288 level: 16
[W 11/20/22 17:02:25.353 3632306] [type_check.cpp:visit@164] [$4178] Field index 0 not int32, casting into int32 implicitly
File "/home/zhao/China_R_Meeting/taichi_ngp.py", line 472, in raymarching_test_kernel:
                occ = self.density_bitfield[ti.u32(
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                    idx // 8)] & (1 << ti.u32(idx % 8))
                    ^^^^^^^^^^

[E 11/20/22 17:02:43.171 3632306] [vulkan_device.cpp:submit@1720] Vulkan Error : -4 : failed to submit command buffer


[E 11/20/22 17:02:43.171 3632306] [ir.cpp:~DelayedIRModifier@411] Assertion failure: to_insert_before_.empty()


terminate called after throwing an instance of 'std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >'
```

Changing `u32` to `int` does not work either.

**Comment by Linyou** [comment]
Hi @neozhaoliang.

The code is running fine on my machines (mac and PC laptop with Vulkan), so I am not sure what is happening here. However, I have fixed the type warning that line `472` produce, hope this change can fix the error. 

In my experience,  the **Vulkan** backend may crash when doing multiplication using types `float32` and `float16`, in which the types are mismatched. Maybe, the reason for this error is something similar.

**Comment by neozhaoliang** [comment]
It still crashes. 

Some nits:

1. this example has keyboard control interfaces, could you please add a helper docstring at the beginning of the file, so that users can know how to play with it?
2. our CI bot checks coding style via `pylint`, renaming built-in names like `input` would fail the test, could you please use other names to avoid this?

**Comment by Linyou** [comment]
> It still crashes.
> 
> Some nits:
> 
> 1. this example has keyboard control interfaces, could you please add a helper docstring at the beginning of the file, so that users can know how to play with it?
> 2. our CI bot uses `pylint` to check the coding style, renaming built-in names like `input` would fail the test, could you please choose other variable names to avoid this?

Dose intel(GT2) card support SharedArray?

Also, I have added the instruction of GUI to the beginning of the file and changed the variable names for `pylint` test.

**Review by neozhaoliang — APPROVED** [review]
LGTM!

**Pull request merged**
