### PR TITLE
[opencl] Setup basis of OpenCL backend

### PR DESCRIPTION
**Pull request by archibate**
Related issue = not yet

[[Click here for the format server]](http://kun.csail.mit.edu:31415/)

----
This PR only add infrastructures for the future of our OpenCL backend.
For now we uses the source-to-source approach as SPIR-V is still at its very early age.
Hopefully, OpenCL will be the first GPU backend that is portable to all win/osx/linux, thanks for the great job of @KhronosGroup!

### CODE REVIEW

**Comment by yuanming-hu** [comment]
Thanks for the PR! While I believe adding OpenCL support is helpful, it would be nice to finish a few pending PRs before opening new ones. They are very close to get merged after a few minor comments of the reviewers are addressed.

I'm happy to review this after #1807, #1795, #1991, #1931 are merged. It would be nice to finish what you started before starting new topics (see our [code of conduct](https://taichi.graphics/community/code_of_conduct.html#focused)). Thanks!

**Comment by archibate** [comment]
Update: all test passing (on my end)!

**Comment by archibate** [comment]
Hello? I fixed the prs you mentioned above, would you review this now? Its already passing all tests. 1 more pr may even make opencl ready to release.

**Comment by archibate** [comment]
hi? This is an important PR IMO.

**Comment by masahi** [comment]
Great! I can test this on my R9 Nano. (A good opportunity to look at taichi again, for the first time in a while!)

**Comment by archibate** [comment]
Amazing amount of conflict!

**Comment by bobcao3** [comment]
Can you try to use the SPIR-V backend from Vulkan? It should be possible to use basically identical code between these two.

**Comment by archibate** [comment]
but this pr uses codegen approach..











无法顺畅的大口呼吸，是活着的最好证明

---Original---
From: "Bob ***@***.***&gt;
Date: Thu, Aug 5, 2021 18:01 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [taichi-dev/taichi] [opencl] Setup basis of OpenCL backend (#2025)




 
Can you try to use the SPIR-V backend from Vulkan? It should be possible to use basically identical code between these two.
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by bobcao3** [comment]
Yes true, so I'm asking whether you think you can move this to a IR based,
SPIR-V or not, codegen instead. I personally think adding more independent
backends can quickly degrade maintainability of the entire project, and IR
is a way to enable code reuse potential.

**Comment by archibate** [comment]
Sorry, don't know much about SPIR-V.. Would you mind adapt it for me in this PR? I'd be happy to work with this if I'm a intern of taichi.graphics..

**Comment by feisuzhu** [comment]
Closing ancient PR.

**Pull request closed without merging**
