### PR TITLE
[Lang] Fix pylint rule C0209

### PR DESCRIPTION
**Pull request by zstone12**
Related issue = #3151

### CODE REVIEW

**Comment by yihong0618** [comment]
Some typo commit can be `rebase` to one ?

**Comment by zstone12** [comment]
> Some typo commit can be `rebase` to one ?

I will do it later.

**Comment by k-ye** [comment]
> Some typo commit can be `rebase` to one ?

This is actually fine. We do a `squash and merge` to master, so these intermediary commits won't show up in the master branch :-)

**Review by sjwsl — APPROVED** [review]
LGTM, thanks!

**Pull request merged**
