### PR TITLE
[LLVM] Remove the dependency of llvm-as

### PR DESCRIPTION
**Pull request by sjwsl**
Related issue = #

### CODE REVIEW

**Comment by sjwsl** [comment]
I'm not quite sure about the correctness of the modification in `source_builder.py`. It seems that that piece of code is not tested.

**Comment by strongoier** [comment]
I'm a little confused - if we remove the dependency of `llvm-as`, then we don't need our customized LLVM anymore. Am I missing anything?

**Comment by sjwsl** [comment]
> I'm a little confused - if we remove the dependency of `llvm-as`, then we don't need our customized LLVM anymore. Am I missing anything?

Probably we need the customized library? I'm not clear too, but I guess at least RTTI must be manually enabled unless we remove all the usages of `llvm::dyn_cast`.

**Comment by yuanming-hu** [comment]
Hello @sjwsl, do we still want to get this PR merged? I feel like removing the dependency on `llvm-as` would be very helpful, but I'd like to listen to your opinion at this point.

I'm happy to help review after the conflicts are resolved. Thanks!

------------

> > I'm a little confused - if we remove the dependency of `llvm-as`, then we don't need our customized LLVM anymore. Am I missing anything?
> 
> Probably we need the customized library? I'm not clear too, but I guess at least RTTI must be manually enabled unless we avoid `llvm::dyn_cast`.

I believe we still need a customized LLVM for the following flags:
```
cmake .. -DLLVM_ENABLE_RTTI:BOOL=ON -DBUILD_SHARED_LIBS:BOOL=OFF -DCMAKE_BUILD_TYPE=Release -DLLVM_TARGETS_TO_BUILD="X86;NVPTX" -DLLVM_ENABLE_ASSERTIONS=ON -DLLVM_ENABLE_TERMINFO=OFF
```
and I agree RTTI is likely the main reasons why we need customization.

**Comment by sjwsl** [comment]
> Hello @sjwsl, do we still want to get this PR merged? I feel like removing the dependency on `llvm-as` would be very helpful, but I'd like to listen to your opinion at this point.
> 
> I'm happy to help review after the conflicts are resolved. Thanks!
> 
> > > I'm a little confused - if we remove the dependency of `llvm-as`, then we don't need our customized LLVM anymore. Am I missing anything?
> > 
> > 
> > Probably we need the customized library? I'm not clear too, but I guess at least RTTI must be manually enabled unless we avoid `llvm::dyn_cast`.
> 
> I believe we still need a customized LLVM for the following flags:
> 
> ```
> cmake .. -DLLVM_ENABLE_RTTI:BOOL=ON -DBUILD_SHARED_LIBS:BOOL=OFF -DCMAKE_BUILD_TYPE=Release -DLLVM_TARGETS_TO_BUILD="X86;NVPTX" -DLLVM_ENABLE_ASSERTIONS=ON -DLLVM_ENABLE_TERMINFO=OFF
> ```
> 
> and I agree RTTI is likely the main reasons why we need customization.

Sorry for the delay on this PR. I'm working on other stuff recently.

I agree that a customized LLVM is still needed at this point. For this PR, I think it's ready to merge after resolving the conflicts. I'll do it soon and ask for your review then.

**Review by yuanming-hu — APPROVED** [review]
LGTM - let's see if CI passes :-) Thank you.

**Pull request merged**
