### PR TITLE
[bug] Fix device memory allocation for numpy array on CUDA backend

### LINKED ISSUE #6924: How much temporary memory is required by `.to_numpy()`?
I was under the impression that `to_numpy()` would consume at most 1x of the memory being copied. 
However, this code fails, which shows that it consumes even more than 2x 
```py
ti.init(ti.cuda, device_memory_GB=7)

# 0.5 GB * sizeof(ti.f32) = 0.5 GB * 4 = 2GB
x = ti.field(ti.f32, shape=int(0.5 * 10**9))

x.to_numpy()
```
error message:
```
Traceback (most recent call last):
  File "C:\Users\ldfra\Code\Taichi\taichi\test.py", line 8, in <module>
    x.to_numpy()
  File "c:\users\ldfra\code\taichi\taichi\python\taichi\lang\util.py", line 310, in wrapped
    return func(*args, **kwargs)
  File "c:\users\ldfra\code\taichi\taichi\python\taichi\lang\field.py", line 302, in to_numpy
    tensor_to_ext_arr(self, arr)
  File "c:\users\ldfra\code\taichi\taichi\python\taichi\lang\kernel_impl.py", line 953, in wrapped
    return primal(*args, **kwargs)
  File "c:\users\ldfra\code\taichi\taichi\python\taichi\lang\kernel_impl.py", line 880, in __call__
    return self.runtime.compiled_functions[key](*args)
  File "c:\users\ldfra\code\taichi\taichi\python\taichi\lang\kernel_impl.py", line 805, in func__
    raise e from None
  File "c:\users\ldfra\code\taichi\taichi\python\taichi\lang\kernel_impl.py", line 802, in func__
    t_kernel(launch_ctx)
RuntimeError: [taichi/rhi/cuda/cuda_driver.h:taichi::lang::CUDADriverFunction<void * *,unsigned __int64>::operator ()@88] CUDA Error CUDA_ERROR_OUT_OF_MEMORY: out of memory while calling malloc (cuMemAlloc_v2)
```
So I'm wondering just how much memory I need to reserve in order to use `to_numpy()`?

### PR DESCRIPTION
**Pull request by jim19930609**
Issue: fix #6924

### CODE REVIEW

**Comment by AmesingFlank** [comment]
CI seems to have failed hmm

**Comment by jim19930609** [comment]
> CI seems to have failed hmm

yup, working on it~

**Review by bobcao3 — APPROVED** [review]

**Pull request merged**
