### PR TITLE
[refactor] Avoid copying examples/ folder when building taichi.

### PR DESCRIPTION
**Pull request by ailzhang**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* **#3575**
* #3574

### CODE REVIEW

**Comment by strongoier** [comment]
Shall we leave `examples/chi_examples` unmoved? It is C++ example for using CHI IR builder.

**Comment by ailzhang** [comment]
> Shall we leave `examples/chi_examples` unmoved? It is C++ example for using CHI IR builder.

Sounds good!

**Comment by k-ye** [comment]
> Shall we leave `examples/chi_examples` unmoved? It is C++ example for using CHI IR builder.

Speaking of that, this is not covered by CI/CD...

**Comment by strongoier** [comment]
> > Shall we leave `examples/chi_examples` unmoved? It is C++ example for using CHI IR builder.
> 
> Speaking of that, this is not covered by CI/CD...

Speaking of that, all our examples are not covered by CI/CD?

**Comment by ailzhang** [comment]
> > > Shall we leave `examples/chi_examples` unmoved? It is C++ example for using CHI IR builder.
> > 
> > 
> > Speaking of that, this is not covered by CI/CD...
> 
> Speaking of that, all our examples are not covered by CI/CD?

We cover laplace in a few cases ;) 
My guess that these examples are not in CI/CD is that a lot of them require GUI show (they don't have a CI mode that verify correctness, but yea let's open an issue for that first :D

**Review by strongoier — APPROVED** [review]
LGTM!

**Pull request merged**
