### PR TITLE
[gui] GGUI 4/n: Vulkan GUI backend utils

### PR DESCRIPTION
**Pull request by AmesingFlank**
Related issue = #2646 

This is the 4th of a series of PRs that adds a GPU-based GUI to taichi. This PR adds the majority of the Vulkan implementation. This PR mainly utility functions, for creating vulkan objects and for interops.

### CODE REVIEW

**Comment by bobcao3** [comment]
wait isn't this the 5th

**Comment by AmesingFlank** [comment]
> wait isn't this the 5th

Nope lol. I deleted the previous one. I decided it was too big and thus difficult for you guys to review.

**Review by g1n0st — APPROVED** [review]
LGTM!

**Review by k-ye — APPROVED** [review]
LGTM, thank you!

**Pull request merged**
