### PR TITLE
[vulkan] More subgroup operations

### PR DESCRIPTION
**Pull request by bobcao3**
Support subgroup broadcast, shuffle, and relative shuffle

### CODE REVIEW

**Review by PENGUINLIONG — APPROVED** [review]
Didn't see in this PR tho. Is this guarded by a device capability check somewhere?

**Comment by bobcao3** [comment]
> Didn't see in this PR tho. Is this guarded by a device capability check somewhere?

not yet... the subgroups stuff is currently all just internal func call

**Review by strongoier — COMMENTED** [review]
Do we need some tests?

**Comment by bobcao3** [comment]
> Do we need some tests?

let's do that later and unblock nerf first

**Pull request merged**
