### PR TITLE
[bug] Fix extraction of field with offset to external array

### PR DESCRIPTION
**Pull request by dream189free**
Issue: #7775

### <samp>🤖 Generated by Copilot at 44074b9</samp>

This pull request adds support for offset tensors in Taichi, which are tensors with non-zero lower bounds for their index domains. It updates the `test_offset.py` file to add more tests, the `tensor_to_ext_arr` function to handle offset copying, and the `SNode` class to expose the offset attribute to Python.

### <samp>🤖 Generated by Copilot at 44074b9</samp>

* Add offset attribute to SNode class and expose it to Python interface ([link](https://github.com/taichi-dev/taichi/pull/7945/files?diff=unified&w=0#diff-af631a0c71978fe591e17005f01f7c06bc30ae36c65df306bbb3b08ade770167R471))
* Modify tensor_to_ext_arr function to account for offset attribute when copying data to external array ([link](https://github.com/taichi-dev/taichi/pull/7945/files?diff=unified&w=0#diff-09cd7b8194d05b7454b512d74fc5b442aed2319dcb763e182288b55753ce6feeL42-R48))
* Add test cases to check the correctness of offset tensor's data and conversion methods ([link](https://github.com/taichi-dev/taichi/pull/7945/files?diff=unified&w=0#diff-520d9ca52eed08ca617ef520e95d0d1778fb1943b9652f7a388b63abca00ddd1R148-R162), [link](https://github.com/taichi-dev/taichi/pull/7945/files?diff=unified&w=0#diff-520d9ca52eed08ca617ef520e95d0d1778fb1943b9652f7a388b63abca00ddd1R6))

### CODE REVIEW

**Review by jim19930609 — APPROVED** [review]
Thanks you!

**Review by ailzhang — COMMENTED** [review]
nit: btw there're many other built-in kernels that may require a similar fix ;)

**Review by jim19930609 — APPROVED** [review]
Thanks!

**Review by ailzhang — COMMENTED** [review]
nit: can we add a few more tests to make sure every touched kernel is tested? ;) Thanks!

**Pull request merged**
