### PR TITLE
[lang] Return None when parent() exceeds its maximum depth

### PR DESCRIPTION
**Pull request by k-ye**
Seems like https://github.com/taichi-dev/taichi/pull/1214/files#r440768343 wasn't addressed. I'd suggest us not to make root circular and keep the parent chain linear. Following parent until null is a fairly common op, e.g. https://github.com/taichi-dev/taichi/blob/37976e750e1579ff9328f3d25f1a63cb3b3292e2/taichi/transforms/offload.cpp#L87-L95

This PR also handles the case where `n` exceeds the hierarchy depth.

Related issue = #1214

[[Click here for the format server]](http://kun.csail.mit.edu:31415/)

----

### CODE REVIEW

**Comment by yuanming-hu** [comment]
Offtopic discussion: maybe we should make `ti.root` a real `SNode` instead of `ti.Root`?

**Comment by archibate** [comment]
> Offtopic discussion: maybe we should make `ti.root` a real `SNode` instead of `ti.Root`?

Agree.
If make `ti.root` a `SNode` too hard for you, you may at least make `SNode` a base class of `Root`.

**Comment by k-ye** [comment]
> Offtopic discussion: maybe we should make ti.root a real SNode instead of ti.Root?

Actually, probably not. I think `root` was implemented this way to do lazy-evaluation, see https://github.com/taichi-dev/taichi/blob/13462ff09560de75fc780de3ee6b0519086ee3b9/python/taichi/lang/impl.py#L251-L253

While we can say only accessing `ti.root` after `ti.init()`, we have to define `root` before `ti.init()`. This initialization requires one level of indirection.. OTOH, changing to `ti.root()` may solve the problem.

As a side effect, I found it useless to define `parent()` on `root`, because it's not called anyway.

**Comment by yuanming-hu** [comment]
> > Offtopic discussion: maybe we should make ti.root a real SNode instead of ti.Root?
> 
> Actually, probably not. I think `root` was implemented this way to do lazy-evaluation, see
> 
> https://github.com/taichi-dev/taichi/blob/13462ff09560de75fc780de3ee6b0519086ee3b9/python/taichi/lang/impl.py#L250-L253
> 
> While we can say one should only access `ti.root` after `ti.init()`, we have to define `root` before `ti.init()`. This initialization requires one level of indirection.. OTOH, changing to `ti.root()` may solve the problem.
> 
> As a side effect, I found it useless to define `parent()` on `root`, because it's not called anyway.

Good point. How about just setting `ti.root` in `ti.init()`? We are enforcing users to call `ti.init` in the very beginning of every taichi program anyway. It's fine to let `ti.root` be `attribute not found` before `ti.init`.

**Comment by k-ye** [comment]
Allow me to merge this one first. I've encountered some problems when modifying global `root` in the module level. Seems like I've encountered the same problem in https://stackoverflow.com/questions/3536620/how-to-change-a-module-variable-from-another-module.

**Comment by yuanming-hu** [comment]
> Allow me to merge this one first. I've encountered some problems when modifying global `root` in the module level. Seems like I've encountered the same problem in https://stackoverflow.com/questions/3536620/how-to-change-a-module-variable-from-another-module.

Ah you are right... I think that's the reason why I did a `Root` class a few months ago... (Sorry about my terrible memory...)

**Pull request merged**
