### PR TITLE
[Example] [bug] Fix constraint correction

### PR DESCRIPTION
**Pull request by FantasyVR**
Related issue = #

### CODE REVIEW

**Review by Hanke98 — APPROVED** [review]
LGTM! Thanks! And please fix the failed test case :-)

**Comment by FantasyVR** [comment]
> LGTM! Thanks! And please fix the failed test case :-)

Thanks, I'm working on it 😄 .

**Comment by FantasyVR** [comment]
@Hanke98 @strongoier I tried to build on Windows. But I couldn't reproduce the errors.
```
/home/dev/taichi/taichi/backends/vulkan/aot_module_builder_impl.cpp:103:5: error: use of undeclared identifier 'runtime_'
    runtime_->register_taichi_kernel(params);
```

I think the changed example code is not relevant to this error. Could we merge directly?

**Comment by strongoier** [comment]
> @Hanke98 @strongoier I tried to build on Windows. But I couldn't reproduce the errors.
> 
> ```
> /home/dev/taichi/taichi/backends/vulkan/aot_module_builder_impl.cpp:103:5: error: use of undeclared identifier 'runtime_'
>     runtime_->register_taichi_kernel(params);
> ```
> 
> I think the changed example code is not relevant to this error. Could we merge directly?

Could you merge with master and try again? This should be fixed now.

**Pull request merged**
