### PR TITLE
[Metal] Move Metal shader code to shaders/ folder

### PR DESCRIPTION
**Pull request by k-ye**
Related issue id = #593 

I created the prolog and epilog code snippet for Metal shaders. They will be more useful when I add the runtime shaders.

We can also use the shader code on both the host and device sides now. This somewhat reduces the necessity of #604 :)

### CODE REVIEW

**Comment by k-ye** [comment]
@yuanming-hu Just FYI, I will probably just merge this in after CI, because it's mostly refactoring..

**Comment by yuanming-hu** [comment]
(Sorry for spamming here but I don't want to send notifications to everyone.) Are you good with the new code style: https://github.com/taichi-dev/taichi/issues/592? If so I'll reformat everything in 12 hours.

**Comment by k-ye** [comment]
Sure, i'm fine with any coding style :)

**Comment by yuanming-hu** [comment]
Great, thanks!

**Pull request merged**
