### PR TITLE
[test] Exit on error during Paddle windows test

### PR DESCRIPTION
**Pull request by qiao-bo**
Powershell needs `if (-not $?) { exit 1 }` to exit on error immediately. Add this for paddle test.

### CODE REVIEW

**Review by 0xzhang — COMMENTED** [review]
Can we not test Paddle's GPU package in CI?  To avoid potential instability problems like excessive memory usage affecting other tests. Since third-party package isn't on stable branch, this feature is somewhat experimental.

**Comment by qiao-bo** [comment]
> Can we not test Paddle's GPU package in CI? To avoid potential instability problems like excessive memory usage affecting other tests. Since third-party package isn't on stable branch, this feature is somewhat experimental.

Do you mean this?
https://github.com/taichi-dev/taichi/blob/3d6fcb058f7a533c471d872e6e9c4cc85c940373/.github/workflows/scripts/win_test.ps1#L12

Strangely, CUDA tests seem OK, It is the x86 CPU tests that produce the failures.

**Comment by 0xzhang** [comment]
@qiao-bo  Yes, I think so. But if it's not the problem GPU. It still seems uncertain the root cause.

**Comment by 0xzhang** [comment]
It seems that tests always fail on `tests/python/test_runtime.py`. Actually these many RuntimeErrors that I haven't encountered before.

**Comment by qiao-bo** [comment]
> 

the opengl problem is an known issue ;/ it is because our runner is not properly started. That should be fixed now.

**Comment by 0xzhang** [comment]
I've encounter this problem sometimes, but this test doesn't fail every time.

```shell
2022-05-05T13:27:15.5867410Z tests/python/test_paddle_io.py::test_io_devices[arch=x64-0] PASSED       [ 20%]
2022-05-05T13:27:15.8888607Z tests/python/test_paddle_io.py::test_io_devices[arch=x64-1] PASSED       [ 21%]
2022-05-05T13:27:16.8579246Z tests/python/test_paddle_io.py::test_io_devices[arch=cuda-2] PASSED      [ 23%]
2022-05-05T13:27:17.8278227Z tests/python/test_paddle_io.py::test_io_devices[arch=cuda-3] RERUN       [ 25%]
2022-05-05T13:27:18.7718559Z tests/python/test_paddle_io.py::test_io_devices[arch=cuda-3] RERUN       [ 25%]
2022-05-05T13:27:19.7466547Z tests/python/test_paddle_io.py::test_io_devices[arch=cuda-3] FAILED      [ 25%]
```

And stuck again in CleanUp. 😢

**Comment by 0xzhang** [comment]
\rerun

**Comment by 0xzhang** [comment]
https://github.com/taichi-dev/taichi/blob/master/.github/workflows/testing.yml#L324

Should the "-force" be rewritten to "-Force" to ensure CleanUp work. I'm not familiar with PowerShell.

**Comment by qiao-bo** [comment]
> https://github.com/taichi-dev/taichi/blob/master/.github/workflows/testing.yml#L324
> 
> Should the "-force" be rewritten to "-Force" to ensure CleanUp work. I'm not familiar with PowerShell.

PS is mostly case-insensitive. I still think this is related to some mysterious permission issue.

**Comment by 0xzhang** [comment]
> > https://github.com/taichi-dev/taichi/blob/master/.github/workflows/testing.yml#L324
> > Should the "-force" be rewritten to "-Force" to ensure CleanUp work. I'm not familiar with PowerShell.
> 
> PS is mostly case-insensitive. I still think this is related to some mysterious permission issue.

Thanks for reminding. 😢

**Comment by qiao-bo** [comment]
@0xzhang @ailzhang  #4913 is a bit hackish and not quite portable (yep, we did see other files that cannot be removed ;/). This clean-up issue is not worth our ROI for now. Let's keep paddle related test to CPU backend only. We are planning to make a Windows CPU only job in our workflow that employs docker, hence no clean-up is needed. @0xzhang Can you help to remove/disable the paddle related GPU code? such as the paddlepaddle-gpu installation etc?

**Comment by 0xzhang** [comment]
> @0xzhang @ailzhang #4913 is a bit hackish and not quite portable (yep, we did see other files that cannot be removed ;/). This clean-up issue is not worth our ROI for now. Let's keep paddle related test to CPU backend only. We are planning to make a Windows CPU only job in our workflow that employs docker, hence no clean-up is needed. @0xzhang Can you help to remove/disable the paddle related GPU code? such as the paddlepaddle-gpu installation etc?

I submitted a new PR to disable the tests for Paddle on GPU.

**Review by ailzhang — APPROVED** [review]
Thanks!

**Pull request merged**
