### PR TITLE
[ci] Add slash benchmark command for performance monitoring

### PR DESCRIPTION
**Pull request by yolo2themoon**
Related issue = #948 #2601

### CODE REVIEW

**Review by Leonz5288 — APPROVED** [review]
Looks Good To Me!

**Review by k-ye — APPROVED** [review]
LGTM!

**Comment by taichi-gardener** [comment]
|Baseline.x64|||||||||||
|:--:|:--:|:--:|:--:|:--:|:--:|:--:|:--:|:--:|:--:|:--:|
|**data_size**|4.0KB|16.0KB|64.0KB|256.0KB|1.0MB|4.0MB|16.0MB|64.0MB|256.0MB|1.0GB|
|**repeat**|100|100|100|100|100|100|10|10|10|10|
|kernel elapsed time(ms)||||||||||
|fill.i32|0.01|0.0138|0.025|0.0629|0.21|0.819|3.341|13.181|52.9048|212.0519|
|fill.i64|0.011|0.0119|0.0179|0.0379|0.113|0.4299|1.744|6.916|27.575|110.388|
|fill.f32|0.011|0.0138|0.025|0.0629|0.2151|0.8128|3.3112|13.1571|52.433|210.2489|
|fill.f64|0.011|0.0119|0.0169|0.0389|0.113|0.416|1.735|6.881|27.5202|109.8719|
|kernel elapsed time(ms)||||||||||
|reduction.i32|0.011|0.0138|0.0281|0.071|0.2489|0.958|3.8338|15.384|61.069|245.991|
|reduction.i64|0.011|0.0119|0.0179|0.042|0.134|0.489|1.9732|7.9701|32.0139|128.0358|
|reduction.f32|0.0119|0.0169|0.0401|0.1271|0.505|1.884|8.286|32.707|72.9799|292.053|
|reduction.f64|0.011|0.0129|0.0269|0.071|0.2539|1.019|3.9179|16.6402|61.4591|264.473|

|Baseline.cuda|||||||||||
|:--:|:--:|:--:|:--:|:--:|:--:|:--:|:--:|:--:|:--:|:--:|
|**data_size**|4.0KB|16.0KB|64.0KB|256.0KB|1.0MB|4.0MB|16.0MB|64.0MB|256.0MB|1.0GB|
|**repeat**|1000|1000|1000|1000|1000|1000|100|100|100|100|
|kernel elapsed time(ms)||||||||||
|fill.i32|0.0084|0.0084|0.0084|0.0084|0.0086|0.0091|0.0257|0.0836|0.3389|1.4652|
|fill.i64|0.0075|0.0075|0.0075|0.0085|0.0087|0.009|0.0256|0.0831|0.3207|1.2686|
|fill.f32|0.0084|0.0084|0.0084|0.0085|0.0086|0.0091|0.0258|0.0838|0.3367|1.4897|
|fill.f64|0.0075|0.0076|0.0076|0.0085|0.0087|0.0091|0.0255|0.0829|0.318|1.2719|
|kernel elapsed time(ms)||||||||||
|reduction.i32|0.0135|0.0136|0.0135|0.0135|0.014|0.0154|0.029|0.0867|0.319|1.2508|
|reduction.i64|0.1883|0.1883|0.1883|0.1868|0.1872|0.1885|0.198|0.233|0.4466|1.2956|
|reduction.f32|0.0232|0.0267|0.0266|0.0266|0.0268|0.0273|0.0336|0.0897|0.3195|1.2518|
|reduction.f64|0.5477|0.5477|0.5478|0.5477|0.5481|0.5485|0.5531|0.5755|0.8035|1.5826|

**Comment by yolo2themoon** [comment]
> Looks Good To Me!

Thanks for your detailed explanation of CI workflow !

**Pull request merged**
