### PR TITLE
[misc] Headers dependency cleanup from RHI

### PR DESCRIPTION
**Pull request by bobcao3**
In this MR, LLVM and Eigen header dependencies have been removed from the RHI folder. In addition, `device.h` now uses cleaner and leaner includes so that we don't include `ir.h` and `program.h` unnecessarily.

### CODE REVIEW

**Review by k-ye — APPROVED** [review]
LGTM!

**Comment by k-ye** [comment]
PR nits: could you associate PR with issues, thanks!

**Review by ailzhang — APPROVED** [review]
Thanks!

**Pull request merged**
