### PR TITLE
Access out-of-bound checking on CPU backends (Stage 2)

### PR DESCRIPTION
**Pull request by xumingkuan**
Related issue id = #561

A continuation of #572

### CODE REVIEW

**Comment by xumingkuan** [comment]
It still gives me more than one assertion messages:
```
[E 03/11/20 01:47:54.008] [program.cpp:taichi::lang::assert_failed_host@24] Assertion failure: Accessing Tensor of Size [1200, 100] with indices (28, 100)


[E 03/11/20 01:47:54.008] [program.cpp:taichi::lang::assert_failed_host@24] Assertion failure: Accessing Tensor of Size [1200, 100] with indices (4, 100)
```
if I revert https://github.com/taichi-dev/taichi/commit/34987673c3db66b12e2252e9fdb8511975d0ca87 to test it.

I think it is not essential to lock `host_vsnprintf`. What we need is to lock the buffer from the beginning of the write (`host_vsnprintf`) to the end of the read (`call("taichi_assert", get_context(), stmt->cond->value, text);`). 

I tried `std::string` to obtain a copy of the string in the buffer (moving the code out of `extern "C"`) but failed for now.

Or we could allocate a buffer for each call of `get_assert_msg`. I don't know if it would be more efficient than the lock.

**Comment by yuanming-hu** [comment]
Since the kernels are multithreaded, it's normal if you are getting #messages that is <= #cores. As long as there're no false positives we are good.

**Comment by archibate** [comment]
How about to allocate a buffer for each core? eg.:
```cpp
struct PerCPU {
  ...
  char buffer[233];
};
```

**Comment by yuanming-hu** [comment]
> I think it is not essential to lock `host_vsnprintf`. What we need is to lock the buffer from the beginning of the write (`host_vsnprintf`) to the end of the read (`call("taichi_assert", get_context(), stmt->cond->value, text);`).

You can simply `new` a buffer in `get_assert_msg` and then `delete` the result after calling `taichi_assert`.

**Comment by yuanming-hu** [comment]
> How about to allocate a buffer for each core? eg.:
> 
> ```c++
> struct PerCPU {
>   ...
>   char buffer[233];
> };
> ```
> 
> Very common approach in milti-processor OS kernels.

Thread-local storage is a good idea but we need more infrastructure before we actually implement this.

**Comment by xumingkuan** [comment]
> > I think it is not essential to lock `host_vsnprintf`. What we need is to lock the buffer from the beginning of the write (`host_vsnprintf`) to the end of the read (`call("taichi_assert", get_context(), stmt->cond->value, text);`).
> 
> You can simply `new` a buffer in `get_assert_msg` and then `delete` the result after calling `taichi_assert`.

I think I'll choose this solution. As long as `get_assert_msg` is not used in other places, there would be no memory leak issues even if we use C-style `new`'s.

**Comment by xumingkuan** [comment]
Oh, it may be better to just implement another `taichi_assert` with arguments instead...

Then we can safely use a lock on a global buffer or `delete` the buffer inside the function.

**Comment by yuanming-hu** [comment]
> Oh, it may be better to just implement another `taichi_assert` with arguments instead...
> 
> Then we can safely use a lock on a global buffer or `delete` the buffer inside the function.

Let's just take the simplest solution `new`/`delete` for now. After this bound checking feature is effectively in use, we'll learn more about its behavior and practical need. Then we have enough information to engineer a more complex one.

**Comment by yuanming-hu** [comment]
Actually, I'm thinking even if we have multiple threads, we only need one error message. This can be done by having something like 
```
char error_message_buffer[2048];
i32 error_code;
i32 lock
```

The first thread with assertion error just set `error_code` to non-zero, and then exit. The other threads reads a non-zero `error

**Comment by xumingkuan** [comment]
By combining `get_assert_msg` and `taichi_assert` into `taichi_assert_format`, I get only one assertion message now. Maybe it's not good for modular programming though...

**Comment by yuanming-hu** [comment]
Looks good! There are many design choices here. Let's briefly skype chat if you are available.

**Comment by yuanming-hu** [comment]
After this line
https://github.com/taichi-dev/taichi/blob/master/taichi/program/kernel.cpp#L46

call `Program::check_runtime_error` if in debug mode and on CPU.

in `Program::check_runtime_error`, fetch the error code and error message ptr, just like https://github.com/taichi-dev/taichi/blob/master/taichi/program/kernel.cpp#L46 and https://github.com/taichi-dev/taichi/blob/master/taichi/program/program.cpp#L166

**Comment by yuanming-hu** [comment]
For `fetch_result`: https://github.com/taichi-dev/taichi/blob/a3df422765d45cbde61a178775522611e3a57f4b/taichi/runtime/llvm/runtime.cpp#L735

**Comment by yuanming-hu** [comment]
Hi @xumingkuan, do you want me to merge this in for now, and you open a new PR for the enhanced assertion failure treatment? (Just trying to avoid large changesets...)

**Comment by xumingkuan** [comment]
Let's merge this in for now. I found that shopping and cooking take some time, so it may take a longer time than I thought for me to finish the enhanced assertion failure treatment.

**Comment by yuanming-hu** [comment]
Sounds good.

**Pull request merged**
