### PR TITLE
[Doc] Update global data access rule checker in doc

### PR DESCRIPTION
**Pull request by erizmr**
Issue: #6240

### CODE REVIEW

**Review by Vissidarte-Herman — CHANGES_REQUESTED** [review]
Minor changes.

**Comment by Vissidarte-Herman** [comment]
@Olinaaaloompa Please update the release notes based on this PR.

**Review by Olinaaaloompa — APPROVED** [review]
Changes are well noted. Thanks! @Vissidarte-Herman

**Review by Vissidarte-Herman — APPROVED** [review]
LGTM!

**Pull request merged**
