### PR TITLE
[Lang] Fix pylint rule W0101

### PR DESCRIPTION
**Pull request by darkSheep404**
I noticed that one of the two codes that needed to be fixed has a  `TODO`,
so I just commented on the code after `return` instead of delete

### CODE REVIEW

**Comment by sjwsl** [comment]
Would you mind signing the CLA so that we can accept your contribution? Thanks!

**Comment by darkSheep404** [comment]
> Would you mind signing the CLA so that we can accept your contribution? Thanks!
Sorry, i signed with a different email with my github email before
I has been re-signed

**Comment by sjwsl** [comment]
Huh... It seems that #3494 introduces some new errors to your changes. Could you refer to the error message in CI and #3494 to fix it?

**Comment by darkSheep404** [comment]
ok,i  have fixed it and pushed now

**Review by sjwsl — APPROVED** [review]
LGTM, thanks!

**Pull request merged**
