### PR TITLE
[Build] Exit CI builds when download of prebuilt packages fails

### PR DESCRIPTION
**Pull request by PENGUINLIONG**
Improve log readability for [this case](https://github.com/taichi-dev/taichi/runs/6585423431?check_suite_focus=true).

### CODE REVIEW

**Comment by frostming** [comment]
I am not a Powershell genius but I thought it is handled by $ErrorActionPreference = "Stop"

**Comment by PENGUINLIONG** [comment]
> I am not a Powershell genius but I thought it is handled by
> 
> https://github.com/taichi-dev/taichi/blob/e346e9f87b1fcf1151a7135248fd1981d3f477f8/.github/workflows/scripts/win_build.ps1#L11-L12

It would if you didn't install the actual `curl` and `curl` is still an alias of `Invoke-WebRequest`; but it's `curl.exe` which wouldn't be triggering any powershell error. It only handles semantical powershell errors (exceptions).

**Comment by PENGUINLIONG** [comment]
BTW `Invoke-WebRequest` has a PowerShell version requirement so if you already have curl set up I'm somehow reluctant to shift to `Invoke-WebRequest`

**Comment by frostming** [comment]
> but it's curl.exe which wouldn't be triggering any powershell error. It only handles semantical powershell errors (exceptions).

Oh it makes sense, then it LGTM from my side.

**Pull request merged**
