### PR TITLE
[metal] Fix active() on dynamic SNode

### PR DESCRIPTION
**Pull request by k-ye**
This has been fixed in #1480. But given it's not ready yet, I will fix it here first.

Related issue = #1480

[[Click here for the format server]](http://kun.csail.mit.edu:31415/)

----

### CODE REVIEW

**Comment by k-ye** [comment]
BTW, i don't have OpenGL backend, but i think the GL impl is correct so it won't break..

**Comment by archibate** [comment]
I don't have the GL backend either... @xumingkuan Do you have it? Would you mind do me a favor by `ti test -a opengl` and see if OpenGL is still functional these days?

**Comment by xumingkuan** [comment]
I don't have it either...

**Comment by archibate** [comment]
> I don't have it either...

Oh sorry! @yuanming-hu Would you do me this favor? IIRC you have a NV card with compute shader support?

**Comment by k-ye** [comment]
Merging. I believe OpenGL has the correct implementation: https://github.com/taichi-dev/taichi/blob/d756cbd0c06d8f36ab67e0ad3a91c78192dc4b27/taichi/backends/opengl/codegen_opengl.cpp#L323-L325

**Pull request merged**
