### PR TITLE
[opengl] [Bug] Fix crash with old GLX

### PR DESCRIPTION
**Pull request by archibate**
Related issue = #958 #1106

<del>@TroyZhai do you have a taichi dev setup to help me test if the problem is gone? Many thanks!
Hope this could resolve your issue systematically :)</del> more tests required.

[[Click here for the format server]](http://kun.csail.mit.edu:31415/)

A similar issue: http://www.mujoco.org/forum/index.php?threads/segmentation-fault-when-running-bin-simulate-on-ubuntu-16-04.3512/ or https://github.com/glfw/glfw/issues/1096
Related pieces in GLFW: https://github.com/glfw/glfw/blob/e0c77f71f90e3bb8495c5c88fb0fb054d71cf7fc/src/glx_context.c#L62-L66

### CODE REVIEW

**Comment by TroyZhai** [comment]
@archibate Sure thing, hold on

**Comment by Eydcao** [comment]
Incredible speed @archibate ! I will also give it a try, just a sec.

**Comment by archibate** [comment]
Bad news: it makes OpenGL not work on my machine too.

**Comment by Eydcao** [comment]
> Bad news: it makes OpenGL not work on my machine too.

Still incredible speed :>, I could help test when you make another fix again

**Comment by archibate** [comment]
Thank for the patience! Given the address [traceback](https://user-images.githubusercontent.com/48085697/83482706-87b40c80-a4d3-11ea-87d6-9885e2ce999b.png). Could you run `objdump -D /lib/libGLX_mesa.so | grep 35bf.:` for me?

**Comment by Eydcao** [comment]
> Thank for the patience! Given the address [traceback](https://user-images.githubusercontent.com/48085697/83482706-87b40c80-a4d3-11ea-87d6-9885e2ce999b.png). Could you run `objdump -D /lib/libGLX_mesa.so | grep 35bf.:` for me?

objdump: '/lib/libGLX_mesa.so': No such file

It says

**Comment by archibate** [comment]
Oh, sorry! It's `/lib/x86_64-linux-gnu/libGLX_mesa.so`.

**Comment by Eydcao** [comment]
> Oh, sorry! It's `/lib/x86_64-linux-gnu/libGLX_mesa.so`.

This PC does not have it still, but in the same dir I found `libGLX_mesa.so.0` and `libGLX_mesa.so.0.0.0`. Attached screenshots here

image

image

**Comment by archibate** [comment]
The information is really helpful! I added some hooks in `_glfwInitGLX()`, could you retrieve the latest commit of this PR and run `git submodule update --init` and see what it prints? (should be `G0~G20`)

**Comment by Eydcao** [comment]
> What's your glx version?

1.4

**Comment by archibate** [comment]
That's strange... my glx is also 1.4..

**Comment by Eydcao** [comment]
> The information is really helpful! I added some hooks in `_glfwInitGLX()`, could you retrieve the latest commit of this PR and run `git submodule update --init` then build + `import taichi` to see what message it prints? (should be `G0~G20`, of course, no rush at all :)

image

**Pull request closed without merging**
