### PR TITLE
[misc] Fix upload release error handling

### PR DESCRIPTION
**Pull request by Leonz5288**
Related issue = #

### CODE REVIEW

**Review by ailzhang — APPROVED** [review]
LGTM!
shall we add a test for upload_artifact as well? ;)

**Comment by Leonz5288** [comment]
> 

Sounds good, but I'm not sure how to do test this... With another account?
To me, this looks more like a one-time thing.

**Comment by ailzhang** [comment]
@Leonz5288 ohh I was mostly thinking of testpypi, but yea it's super minor :D

**Pull request merged**
