### PR TITLE
 Skip non-essential builds on AppVeyor #485

### PR DESCRIPTION
**Pull request by archibate**

### CODE REVIEW

**Comment by archibate** [comment]
Please check `https://www.appveyor.com/docs/appveyor-yml/` for more usages.

**Comment by archibate** [comment]
> NOTE: Similarly to custom skip commit message, AppVeyor searches for [skip ci] / [ci skip] / [skip appveyor] in the commit message title only. This avoids confusion when squashing commits, in particular with the GitHub squash-and-merge feature.

**Comment by archibate** [comment]
TODO: use cache to speed up build: [https://www.appveyor.com/docs/build-cache/](url)
```yml
cache:
- C:\taichi\build -> C:\taichi\CMakeLists.txt
```
Also, clang.zip & llvm.zip.

**Comment by archibate** [comment]
TODO: use if cond in yaml to change matrix: [https://www.cnblogs.com/xiyin/p/10434247.html](url)

**Comment by archibate** [comment]
TODO: typo in 19603c3, fix with next commit.

**Comment by yuanming-hu** [comment]
WOW, this is awesome!! Finally, we have systematically addressed the long build time issue. I'll merge in the multithreaded testing PR after this.

> How about cp examples/laplace.py tests/python/test_0_laplace.py

Let's leave it in `examples` just indicating if any program still runs without pytest :-)

> llvm & clang: 31s - save by cache ../taichi_llvm & ../taichi_clang

This can probably be cached, since it's just downloading

>ci_setup.py: 28s - don't know, can we save this by cache?
>cmake: 39s - save by cache build
>msbuild: 374s - save by cache build, or compile by timestamp order
>laplace & ti test: 364s - save by #483

Although it might be a good idea to cache them for efficiency, caching can also lead to unexpected behavior and bugs with sources deeply hidden (since people will assume nothing is cached). For now let's just not cache these steps until AppVeyor starts queuing again  sometime in the future.

>By the way, is there anything like MATRIX_EVAL (in .travis.yml) in AppVeyor?

To he honest I don't know, but there might be functionality like this somewhere hidden in the AppVeyor documentation.

**Comment by yuanming-hu** [comment]
I removed `cache` to make this PR focus on build skipping. I think caching the download of `clang` and `llvm` would be great. We can have an independent PR for this. Thanks so much!!

**Pull request merged**
