### PR TITLE
[workflow] Build OpenGL on GHCI zhen server

### PR DESCRIPTION
**Pull request by archibate**
Related issue = #1863

[[Click here for the format server]](http://kun.csail.mit.edu:31415/)

----

### CODE REVIEW

**Comment by yuanming-hu** [comment]
Thanks! I had to cancel the latest commit with `sudo` commands. Using `sudo` on `zhen` is not allowed for security reasons. Let me know if you need `sudo` privileges to install something,

**Comment by archibate** [comment]
So how can I install the apt-packages in 08a75d6? GLFW can't be built without these dependencies.

**Comment by yuanming-hu** [comment]
> So how can I install the apt-packages in [08a75d6](https://github.com/taichi-dev/taichi/commit/08a75d661549eb95afff745187bf0d4258db3b2c)? GLFW can't be built without these dependencies.

I believe these are actually already installed.

**Comment by archibate** [comment]
> > So how can I install the apt-packages in [08a75d6](https://github.com/taichi-dev/taichi/commit/08a75d661549eb95afff745187bf0d4258db3b2c)? GLFW can't be built without these dependencies.
> 
> I believe these are actually already installed.

No they aren't, see https://github.com/taichi-dev/taichi/runs/1107367832.

**Comment by yuanming-hu** [comment]
> > > So how can I install the apt-packages in [08a75d6](https://github.com/taichi-dev/taichi/commit/08a75d661549eb95afff745187bf0d4258db3b2c)? GLFW can't be built without these dependencies.
> > 
> > 
> > I believe these are actually already installed.
> 
> No they aren't, see https://github.com/taichi-dev/taichi/runs/1107367832:
> 
> ```
> CMake Error at external/glfw/CMakeLists.txt:206 (message):
>   RandR headers not found; install libxrandr development package
> ```

I believe these packages are already installed by the time of my last comment. Let me know if they aren't.

**Review by yuanming-hu — COMMENTED** [review]
> ~It passed! Please have a look.~
> Not really:
> 
> ```
> cc: True
> cpu: True
> metal: False
> opengl: False
> cuda: True
> 
> `glewinfo` not available: [Errno 2] No such file or directory: 'glewinfo': 'glewinfo'
> ```

Thanks. I just now installed `glewinfo`. 

It seems that many workflow scripts are deleted in this PR, is there a good reason for that? If that's just for making test commits build faster, please revert before requesting reviews.

**Comment by archibate** [comment]
```
---------------------------
    GLEW Extension Info
---------------------------

GLEW version 2.0.0
Reporting capabilities of display , visual 0x18e
Running on a llvmpipe (LLVM 10.0.0, 256 bits) from VMware, Inc.
OpenGL version 3.1 Mesa 20.0.8 is supported
```
VMwave, OpenGL 3.1... This hardware can't support OpenGL compute shader at all.. Virtual machines are always poor at OpenGL version. I thought this is a physical machine?

**Comment by yuanming-hu** [comment]
> ```
> ---------------------------
>     GLEW Extension Info
> ---------------------------
> 
> GLEW version 2.0.0
> Reporting capabilities of display , visual 0x18e
> Running on a llvmpipe (LLVM 10.0.0, 256 bits) from VMware, Inc.
> OpenGL version 3.1 Mesa 20.0.8 is supported
> ```
> 
> VMwave, OpenGL 3.1... This hardware can't support OpenGL compute shader at all.. Virtual machines are always poor at OpenGL version. I thought this is a physical machine?

Sorry about the delayed reply. It's actually a physical machine with two NVIDIA GTX 1080 GPUs. Maybe we just need to update the OpenGL version there?

**Comment by archibate** [comment]
> > ```
> > ---------------------------
> >     GLEW Extension Info
> > ---------------------------
> > 
> > GLEW version 2.0.0
> > Reporting capabilities of display , visual 0x18e
> > Running on a llvmpipe (LLVM 10.0.0, 256 bits) from VMware, Inc.
> > OpenGL version 3.1 Mesa 20.0.8 is supported
> > ```
> > 
> > 
> > VMwave, OpenGL 3.1... This hardware can't support OpenGL compute shader at all.. Virtual machines are always poor at OpenGL version. I thought this is a physical machine?
> 
> Sorry about the delayed reply. It's actually a physical machine with two NVIDIA GTX 1080 GPUs. Maybe we just need to update the OpenGL version there?

yeah, possible apt update libglvnd?

**Comment by yuanming-hu** [comment]
Thanks! I probably need to travel to MIT so that I can have physical access to the machine. Before that, I need to get COVID-tested. It may take a few days before I can check the OpenGL issue, but I'll try this week.

Before that, could you take a look at https://github.com/taichi-dev/taichi/issues/1931 when you get a chance? This may cause the OpenGL tests to fail after we set up OpenGL testing.

A related thread: https://forums.developer.nvidia.com/t/opengl-doesnt-use-nvidia-drivers-on-ubuntu-18-04-uses-llvmpipe/126084

**Comment by yuanming-hu** [comment]
Update: I get myself COVID tested and will soon have physical access to `zhen`. Will try to do it during the weekend.

**Comment by yuanming-hu** [comment]
Finally I have physical access to `zhen`. `glewinfo` outputs:
[glewinfo.txt](https://github.com/taichi-dev/taichi/files/5469800/glewinfo.txt)

A related thread: https://arrayfire.com/remote-off-screen-rendering-with-opengl/

**Comment by yuanming-hu** [comment]
After fixing a bunch of random stuff on `zhen`, we can make OpenGL testing work by simply `export DISPLAY=:2`. Since this PR modifies a lot more files, I opened another PR #2014 with a much smaller change. Let's move there :-)

**Pull request closed without merging**
