### PR TITLE
Simplify init in mgpcg_advanced.py

### PR DESCRIPTION
**Pull request by xumingkuan**
Related issue id = #615

[[Click here for the format server]](http://kun.csail.mit.edu:31415/)

### CODE REVIEW

**Comment by xumingkuan** [comment]
Oh, I shouldn't have determined the dimension in compile time in `transformer.py`. Fixing.

**Comment by yuanming-hu** [comment]
I think we are very close to making this script fully dimensionality-independent! You may also want to change `6.0` into `2.0 * self.dim`, and upgrade the `paint` kernel (you can use a `if ti.static(self.dim == 2)` at the top level of that kernel to distinguish 2/3D cases. Let me know if you run into any issues. Thanks!

**Comment by xumingkuan** [comment]
In cases like `for I in ti.grouped(ti.ndrange(*(((0, n),) * dim))):`, the dimension of `ti.ndrange` cannot be determined in compile time. Therefore,
https://github.com/taichi-dev/taichi/blob/311990ca181c56faa0028a066a4f18049562b3d0/python/taichi/lang/transformer.py#L365
should be replaced by a runtime for loop, and the code here
https://github.com/taichi-dev/taichi/blob/311990ca181c56faa0028a066a4f18049562b3d0/python/taichi/lang/transformer.py#L370
cannot be reused. I think it better to fix them while refactoring `visit_For`, and merge this for now.

**Comment by yuanming-hu** [comment]
> In cases like `for I in ti.grouped(ti.ndrange(*(((0, n),) * dim))):`, the dimension of `ti.ndrange` cannot be determined in compile time. Therefore,
> https://github.com/taichi-dev/taichi/blob/311990ca181c56faa0028a066a4f18049562b3d0/python/taichi/lang/transformer.py#L365
> 
> 
> should be replaced by a runtime for loop, and the code here
> https://github.com/taichi-dev/taichi/blob/311990ca181c56faa0028a066a4f18049562b3d0/python/taichi/lang/transformer.py#L370
> 
> 
> cannot be reused. I think it better to fix them while refactoring `visit_For`, and merge this for now.


Do you mean something like `for I in ti.grouped(ti.ndrange(*(((0, x[0]),) * dim))):`? I'm assuming that `n` is a compile-time constant.

**Comment by xumingkuan** [comment]
I mean `dim` is not a compile-time constant. The bounds like `(0, x[0])` is already not required to be compile-time constants in the code.

**Comment by xumingkuan** [comment]
In a `ti.ndrange` for loop that is not `ti.grouped`, the dimension is determined by the number of variables, i.e., `i, j, k` in `for i, j, k in ti.ndrange(*(((0, n),) * dim)):`.

**Comment by yuanming-hu** [comment]
> I mean `dim` is not a compile-time constant.

I think `self.dim` is indeed a compile-time constant. Note that the compile time of a class kernel is the first time it is created, after its `__init__`.

**Comment by xumingkuan** [comment]
I think it's not easy to calculate the dimension in compile-time. Even if I test if the argument of `ti.ndrange` is a starred expression and get the value of `dim`, users may write arbitrary expressions instead (for example, `for I in ti.grouped(ti.ndrange(*(((0, n),) * dim1 * (dim2 + dim3)))):`). And we may want to support `for I in ti.grouped(ti.ndrange(*(((0, n),) * x[0]))):`.

**Comment by xumingkuan** [comment]
All tests passed on my laptop just now.

**Comment by yuanming-hu** [comment]
Cool! Let me know if MGPCG works in 2D.

**Comment by xumingkuan** [comment]
@yuanming-hu Let's merge this in for now and I'll open another PR for refactoring.

**Comment by yuanming-hu** [comment]
Sounds good. Thanks.

**Pull request merged**
