### PR TITLE
[Misc] Fix the path in conda_env.yaml

### PR DESCRIPTION
**Pull request by gaocegege**
Related issue = null

When I follow the comment to create conda env, there's an error like this:

```
EnvironmentFileNotFound: 'taichi/conda/conda-env.yaml' file not found
```

This PR is to fix the typo in conda_env.yaml

### CODE REVIEW

**Review by ailzhang — APPROVED** [review]
Nice catch! Thank you!

**Comment by gaocegege** [comment]
Thanks for your help, should I re-push the commit to trigger a new presubmit CI build?

**Comment by ailzhang** [comment]
@gaocegege As long as other tests pass this is fine :D No need to push another commit for now ;)

**Comment by yuanming-hu** [comment]
Btw, welcome to the Taichi developer community! @gaocegege :-)

**Comment by gaocegege** [comment]
Thanks for the awesome work.

This PR is just to get familiar with the contribution process. Glad to dive deeper into some of the system's features.

**Pull request merged**
