### PR TITLE
[bug] Fix bug that building with gcc9.4 will fail

### PR DESCRIPTION
**Pull request by PGZXB**
Related issue = #

### CODE REVIEW

**Review by g1n0st — APPROVED** [review]
Works for me! Thanks!

**Comment by k-ye** [comment]
What's your original purpose for using TI_FORCE_INLINE?

**Comment by PGZXB** [comment]
I used `TI_FORCE_INLINE` at https://github.com/taichi-dev/taichi/blob/ed478046754caf3cd3524e1f7b275dddb4843b8a/taichi/llvm/llvm_offline_cache.cpp#L15
which is only a internal util function. And this don't cause failed building.

Then I used it at https://github.com/taichi-dev/taichi/blob/ed478046754caf3cd3524e1f7b275dddb4843b8a/taichi/llvm/llvm_offline_cache.cpp#L69
**without thinking**, for similar purpose.

**I'm so sorry, my bad**

**Comment by k-ye** [comment]
OK I see... Let's trust the compilers for now, which should be very good at figuring out what to inline these days. We can manually inline when the profiling results indicate this is a bottleneck :-)

**Pull request merged**
