### PR TITLE
Fix dev_setup.py due to missing repo_dir

### PR DESCRIPTION
**Pull request by k-ye**

### CODE REVIEW

**Comment by yuanming-hu** [comment]
Actually `dev_setup.py` hasn't been used for a long time. I'm updating the documentation for developer setup now. Please hold on a bit. I'll update you in 10 minutes. Thanks!

**Comment by k-ye** [comment]
Ah I see, thanks!

**Comment by k-ye** [comment]
Nit: I think we need a `cd build` after this line: https://github.com/taichi-dev/taichi/blame/master/docs/dev_install.rst#L35 ?

**Comment by yuanming-hu** [comment]
You are right - I'm fixing that. Please keep me updated! Thanks.

**Pull request merged**
