### PR TITLE
[ci] Llvm15 clang10 ci

### PR DESCRIPTION
**Pull request by python3kgae**
Test for add ci for llvm 15.

TODO:
Make llvm15 an option for win_build_test_cpu.ps1 instead of add win_build_test_cpu_llvm_15.ps1.
Move  https://github.com/python3kgae/taichi_assets/releases/download/llvm15_vs2019_clang/taichi-x64-Release.zip to official repo.

Related issue = #5276

### CODE REVIEW

**Review by ailzhang — COMMENTED** [review]
I'm a little bit worried about us having one more win_build_test ps1 file (we already have 5 `.ps1` files doing similar stuff with slight difference... 
@feisuzhu @PENGUINLIONG could you help suggesting on this?

**Comment by PENGUINLIONG** [comment]
It seems the only difference between `win_build_test_cpu.ps1` and `win_build_test_cpu_llvm_15.ps1` is LLVM prebuilt URL, zip extraction dst and the flag `-TI_WITH_LLVM15`. Could you use an extra param like: `[string]$llvmVer = "10"` to switch between them?

**Comment by python3kgae** [comment]
> It seems the only difference between `win_build_test_cpu.ps1` and `win_build_test_cpu_llvm_15.ps1` is LLVM prebuilt URL, zip extraction dst and the flag `-TI_WITH_LLVM15`. Could you use an extra param like: `[string]$llvmVer = "10"` to switch between them?

Fixed.

**Comment by PENGUINLIONG** [comment]
lgtm :)

**Review by PENGUINLIONG — APPROVED** [review]

**Comment by ailzhang** [comment]
@python3kgae It was from the branch protection rule of master branch, I've removed that temporarily to allow this change and will update them once it's merged ;)

**Comment by python3kgae** [comment]
> @python3kgae It was from the branch protection rule of master branch, I've removed that temporarily to allow this change and will update them once it's merged ;)

Thanks, merged into master.

**Pull request merged**
