### PR TITLE
Add more integer types: {u,i}{8,16,32,64} #504 (Stage 1)

### PR DESCRIPTION
**Pull request by archibate**
Related issue id = #504

### CODE REVIEW

**Comment by archibate** [comment]
```
import taichi as ti

x = ti.var(ti.i16, shape=())

@ti.kernel
def func():
  x[None] = x[None] + 233

x[None] = 433
func()
print(x[None])
```
Try this and have fun!

**Comment by archibate** [comment]
Known bug for my test case:
```python
import taichi as ti

def all_data_types(foo):
  def wrapped():
    for dt in [ti.i32, ti.i64, ti.i8, ti.i16, ti.u8, ti.u16, ti.u32, ti.u64, ti.f32, ti.f64]:
      print(f'testing for {dt}')
      foo(dt)
  return wrapped

@ti.all_archs
@all_data_types
def test_type_assign(dt):
  x = ti.var(dt, shape=())

  for value in range(-4, 4):
    x[None] = value
    print(x[None], value)
    assert x[None] == value

@ti.all_archs
@all_data_types
def test_type_operator(dt):
  x = ti.var(dt, shape=())

  @ti.kernel
  def func(value: dt):
    x[None] = value + 3

  for value in range(-4, 4):
    func(value)
    assert x[None] == value + 3

test_type_assign()
test_type_operator()
```
Output:
```
[Taichi version 0.5.1, cpu only, commit 2b32b7b0]
testing for DataType.int32
-4
-3
-2
-1
0
1
2
3
testing for DataType.int64
[E 02/20/20 14:27:59.948] Received signal 11 (Segmentation fault)
***********************************
* Taichi Compiler Stack Traceback *                                                                            
***********************************                                                                            
/home/bate/Develop/taichi/build/taichi_core.so: taichi::signal_handler(int)                                    
/usr/lib/libc.so.6(+0x3bfb0) [0x7f81a5245fb0]                                                                  
/home/bate/Develop/taichi/build/taichi_core.so: taichi::Tlang::TypeCheck::visit(taichi::Tlang::GlobalPtrStmt*) 
/home/bate/Develop/taichi/build/taichi_core.so: taichi::Tlang::TypeCheck::visit(taichi::Tlang::Block*)         
/home/bate/Develop/taichi/build/taichi_core.so: taichi::Tlang::irpass::typecheck(taichi::Tlang::IRNode*)       
/home/bate/Develop/taichi/build/taichi_core.so: taichi::Tlang::CPUCodeGen::lower_llvm()                        
/home/bate/Develop/taichi/build/taichi_core.so: taichi::Tlang::CPUCodeGen::lower()                             
/home/bate/Develop/taichi/build/taichi_core.so: taichi::Tlang::KernelCodeGen::compile(taichi::Tlang::Program&, taichi::Tlang::Kernel&)                                                                                        
/home/bate/Develop/taichi/build/taichi_core.so: taichi::Tlang::Program::compile(taichi::Tlang::Kernel&)        
/home/bate/Develop/taichi/build/taichi_core.so: taichi::Tlang::Kernel::compile()                               
/home/bate/Develop/taichi/build/taichi_core.so: taichi::Tlang::Kernel::operator()()                            
/home/bate/Develop/taichi/build/taichi_core.so(+0x743244) [0x7f819586f244]                                     
/home/bate/Develop/taichi/build/taichi_core.so(+0x639f07) [0x7f8195765f07]                                     
/usr/lib/libpython3.8.so.1.0: PyCFunction_Call                                                                 
/usr/lib/libpython3.8.so.1.0: _PyObject_MakeTpCall                                                             
/usr/lib/libpython3.8.so.1.0(+0xbd23d) [0x7f81a4f4f23d]                                                        
/usr/lib/libpython3.8.so.1.0: PyVectorcall_Call                                                                
/usr/lib/libpython3.8.so.1.0(+0xbd3f1) [0x7f81a4f4f3f1]                                                        
/usr/lib/libpython3.8.so.1.0: _PyObject_MakeTpCall                                                             
/usr/lib/libpython3.8.so.1.0: _PyEval_EvalFrameDefault                                                         
/usr/lib/libpython3.8.so.1.0: _PyEval_EvalCodeWithName                                                         
/usr/lib/libpython3.8.so.1.0: _PyFunction_Vectorcall                                                           
/usr/lib/libpython3.8.so.1.0: PyVectorcall_Call                                                                
/usr/lib/libpython3.8.so.1.0: _PyEval_EvalFrameDefault                                                         
/usr/lib/libpython3.8.so.1.0: _PyEval_EvalCodeWithName                                                         
/usr/lib/libpython3.8.so.1.0: _PyObject_FastCallDict                                                           
/usr/lib/libpython3.8.so.1.0: _PyObject_Call_Prepend                                                           
/usr/lib/libpython3.8.so.1.0(+0x1ed87a) [0x7f81a507f87a]                                                       
/usr/lib/libpython3.8.so.1.0: _PyObject_MakeTpCall                                                             
/usr/lib/libpython3.8.so.1.0: _PyEval_EvalFrameDefault                                                         
/usr/lib/libpython3.8.so.1.0: _PyEval_EvalCodeWithName                                                         
/usr/lib/libpython3.8.so.1.0: _PyFunction_Vectorcall                                                           
/usr/lib/libpython3.8.so.1.0: _PyEval_EvalFrameDefault                                                         
/usr/lib/libpython3.8.so.1.0: _PyEval_EvalCodeWithName                                                         
/usr/lib/libpython3.8.so.1.0: _PyFunction_Vectorcall                                                           
/usr/lib/libpython3.8.so.1.0: _PyEval_EvalFrameDefault                                                         
/usr/lib/libpython3.8.so.1.0: _PyEval_EvalCodeWithName                                                         
/usr/lib/libpython3.8.so.1.0: PyEval_EvalCodeEx                                                                
/usr/lib/libpython3.8.so.1.0: PyEval_EvalCode                                                                  
/usr/lib/libpython3.8.so.1.0(+0x1ed7ea) [0x7f81a507f7ea]                                                       
/usr/lib/libpython3.8.so.1.0(+0x229325) [0x7f81a50bb325]                                                       
/usr/lib/libpython3.8.so.1.0: PyRun_FileExFlags                                                                
/usr/lib/libpython3.8.so.1.0: PyRun_SimpleFileExFlags                                                          
/usr/lib/libpython3.8.so.1.0: Py_RunMain                                                                       
/usr/lib/libpython3.8.so.1.0: Py_BytesMain                                                                     
/usr/lib/libc.so.6: __libc_start_main                                                                          
python(_start+0x2e) [0x55886a28705e]
```

**Comment by archibate** [comment]
https://github.com/taichi-dev/taichi/blob/a3a56ae9987c5f7465c2e9eabc88c4dcbd7914f3/taichi/transforms/type_check.cpp#L102
Found `parent == nullptr` here.

**Comment by archibate** [comment]
NOTE: This problem is also found in master branch.

**Comment by archibate** [comment]
Sloved, the segfault is due to __we can't define var after called any kernel__, maybe we can make it better informed next time.

**Comment by archibate** [comment]
Build passing, now thinking about how to tensor.

**Comment by yuanming-hu** [comment]
> Sloved, the segfault is due to we can't define var after calling to any kernel, maybe we can make it informed in a better way next time.

Oh sorry about that! Yeah, I guess the implicit data structure materialization (after which you can no longer define new vars) can be sometimes confusing.

Your implementation looks good to me. There is one more thing we can further test:

```
num_bits = 8
data_type = ti.u8 # or i8

a, b, c = 0D tensors of type data_type

@ti.kernel
def overflow():
  ret[None] = a + b

a[None] = 2 ** 8 // 3 * 2
b[None] = 2 ** 8 // 3 * 2
overflow()
assert ret[None] == 2 ** 8 // 3 * 2 * 2 % (2 ** 8) # or something else for signed operations
```

Thanks!!

**Comment by archibate** [comment]
Added to test_overflow(), test on u8, i8, u16, i16.

**Comment by yuanming-hu** [comment]
Enhanced the tests. Now it fails at `i64`. It seems to me that
```
a[None] = 2 ** n // 3
assert a[None] == 2 ** n // 3
```
magically fails for i64. Seems to be some kind of "float point errors"...

**Comment by yuanming-hu** [comment]
@xumingkuan When you are available could you help to debug this? You'll gain a lot of experience on the Taichi frontend by looking into this issue.

**Comment by archibate** [comment]
Good luck! Good night!

**Comment by xumingkuan** [comment]
It seems that https://github.com/taichi-dev/taichi/blob/master/python/taichi/lang/impl.py#L147 causes the number `2 ** 64 // 3` to be represented in `i32`.

The good news is that after fixing it by checking if `val` can be represented by `i32`, if we write `a[None] = 6148914691236517205`, we will have `a[None] == 6148914691236517205`. However, if we write `a[None] = 2 ** 64 // 3`, we still have `a[None] == 6148914691236516864`.

BTW, what about the floating numbers in `impl.py`? I think directly checking if `val` can be represented by `f32` is not a good solution.

**Comment by yuanming-hu** [comment]
Hi @xumingkuan, thanks for the inputs. Could you share with us the test case you used? My feeling is that https://github.com/taichi-dev/taichi/pull/505/files#diff-be88dac67b9254f5c23cf375e8883be8R71 does not actually involve `make_constant_expr`.

**Comment by yuanming-hu** [comment]
I have to sleep now. Tomorrow day time I'll be mostly AFK. Good night!

**Comment by xumingkuan** [comment]
Oh sure. Following is my test case (written in `def _test_overflow(dt, n):`):
```python
  @ti.kernel
  def func2():
    a[None] = 6148914691236517205  # 2 ** 64 // 3

  if n == 64:
    func2()
    print(a[None])
```
Good night :)

**Comment by yuanming-hu** [comment]
You probably need to initialize taichi with `default_ip=ti.i64` if you are using int64 constants in a Taichi kernel :-)

While I was struggling to fall asleep, I realized where the bug might be. Now the i64 case is fixed.

**Comment by yuanming-hu** [comment]
Also fixed u64. Now all tests passed on x64/cuda. Btw, @k-ye do you anticipate any Metal issue about this?

**Comment by k-ye** [comment]
> Btw, @k-ye do you anticipate any Metal issue about this?

Hmm, very likely because the Metal backend doesn't support 64-bit data. I think it's fine to submit this, and I can patch the tests... TBH that `ti.require` decorator is a bit confusing to use and I need some time to think about it 😂

**Comment by xumingkuan** [comment]
Still fails when the number is not representable by `int64`. Test case:
```python
@ti.all_archs
def test_uint64():
  ti.init(default_ip=ti.i64)
  b = ti.var(ti.u64, shape=())

  b[None] = 2 ** 64 // 3 * 2
  assert b[None] == 2 ** 64 // 3 * 2

  @ti.kernel
  def func():
    b[None] = 2 ** 64 // 3 * 2

  func()
  assert b[None] == 2 ** 64 // 3 * 2
```
Shall we add support of `default_ip=ti.u64` and `default_ip=ti.u32`?

**Comment by xumingkuan** [comment]
Oh, `uint64` and `uint32` are not valid `DataType`'s of `TypedConstant`. I wonder if there is demand adding support of them...

**Comment by yuanming-hu** [comment]
yes, please add support to TypedConstant. Thx.

**Comment by yuanming-hu** [comment]
Merging this in for now. More tests should be added later.

**Pull request merged**
