### PR TITLE
[doc] meta: s/alone/along/

### PR DESCRIPTION
**Pull request by EricCousineau-TRI**
Minor doc fix; I believe intent here was "Size along dimension"

### CODE REVIEW

**Comment by k-ye** [comment]
Thanks! Would you sign the CLA so that we can merge this :-)

**Review by ljcc0930 — APPROVED** [review]
LGTM!

**Comment by EricCousineau-TRI** [comment]
> Thanks! Would you sign the CLA so that we can merge this :-)

Will let you know once I have the go-ahead - thanks!
(if that's too slow, please feel free to re-author the commit!)

**Comment by EricCousineau-TRI** [comment]
Signed! Just reformatted my commit to match PR title; hopefully that fixes the CI check?

**Comment by k-ye** [comment]
>  match PR title; hopefully that fixes the CI check?

Thanks! Don't worry too much about the title check :-)

**Review by k-ye — APPROVED** [review]

**Pull request merged**
