### PR TITLE
[example] Add real func version of marching_square

### PR DESCRIPTION
**Pull request by lin-hitonami**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #8195
* #8194

### CODE REVIEW

**Comment by neozhaoliang** [comment]
It reports error on my machine:

```
 line 63, in noise:
        tm.dot(hash22(ip), p),
               ^^^^^^^^^^
Unsupported return type: <taichi.lang.matrix.VectorType object at 0x7f43ea6eaf50>
```

Am I missing something?

**Comment by lin-hitonami** [comment]
@neozhaoliang have you checked out to the branch of this PR? I've made some changes to the codebase in the previous PR of this stack.

**Review by jim19930609 — APPROVED** [review]

**Comment by neozhaoliang** [comment]
I tested it again and it works!

**Comment by lin-hitonami** [comment]
ah ghstack PRs shouldn't be merged directly on the PR page...

**Pull request merged**
