### PR TITLE
[test] `ti test -na opengl` to exclude tests on some archs

### PR DESCRIPTION
**Pull request by archibate**
Related issue = #... (if any)

[[Click here for the format server]](http://kun.csail.mit.edu:31415/)

### CODE REVIEW

**Comment by archibate** [comment]
> What happens if someone uses `-a ^opengl,cuda`?

This is the same as `-a cuda`.

> At a high level, I think using `--no-arch/-na` to specify excluded archs would be semantically clearer.

So we have TI_INCLUDED_ARCHS and TI_EXCLUDED_ARCHS? Sounds overkill.

**Comment by yuanming-hu** [comment]
> > What happens if someone uses `-a ^opengl,cuda`?
> 
> This is the same as `-a cuda`.
> 
> > At a high level, I think using `--no-arch/-na` to specify excluded archs would be semantically clearer.
> 
> So we have TI_INCLUDED_ARCHS and TI_EXCLUDED_ARCHS? Sounds overkill.

Thanks for the answer.

Right, I think there's no perfect design here.

 - We should at least forbid the ambiguous `-a ^opengl,cuda` case by throwing a `ValueError`.
 - Please add the `^opengl` usage to the documentation

Please request my review again once these are done.

**Comment by archibate** [comment]
I got an better idea: let's only allow ^ to appear at thr first char. i.e. we pop(0) before split(',')

**Comment by archibate** [comment]
Now `-a ^opengl,cuda` will exclude both opengl and cuda.

**Comment by yuanming-hu** [comment]
> Now `-a ^opengl,cuda` will exclude both opengl and cuda.

Right, but I would still say `-na opengl,cuda` is clearer than `-a ^opengl,cuda`. I need to read the documentation to learn what the latter means. Also note that `^` seems a dangerous symbol for CLI design...

**Comment by archibate** [comment]
^

> > Now `-a ^opengl,cuda` will exclude both opengl and cuda.
> 
> Right, but I would still say `-na opengl,cuda` is clearer than `-a ^opengl,cuda`. I need to read the documentation to learn what the latter means. Also note that `^` seems a dangerous symbol for CLI design...

Actually it's only dangerous for win cmd... Anyway I done with `-na`, `-n` is a extra argument, still pass `^xxx` in `TI_WANTED_ARCHS`. See d595a80.

**Comment by archibate** [comment]
Travis failed due to network reason again: https://travis-ci.com/github/taichi-dev/taichi/jobs/322430345#L1739 (install take too much time)

**Comment by archibate** [comment]
Wait... on my own? Cool!

**Pull request merged**
