### PR TITLE
[bug] [opt] Treat PtrOffsetStmt as random-initialized

### LINKED ISSUE #3954: Dynamic index has a strange behavior in ti.func
**Describe the bug**
It seems that #3942 cause the problem.
See code and results below.

**To Reproduce**
```py
import taichi as ti

ti.init(dynamic_index=True)

vertices = ti.Vector.field(2, dtype=ti.i32, shape=1)

@ti.func
def fun(verts):
    for u in range(2):
        print(verts[u])

@ti.kernel
def ker():
    for c in vertices:
        fun(vertices[c])

vertices.fill(1)
ker()

```

**Log/Screenshots**
Before #3942:
```
[Taichi] version 0.8.10, llvm 10.0.0, commit 0da9d6c0, linux, python 3.8.5
[Taichi] Starting on arch=x64
1
1
```
After #3942:
```
[Taichi] version 0.8.10, llvm 10.0.0, commit 910a4e12, linux, python 3.8.5
[Taichi] Starting on arch=x64
0
0
```

### PR DESCRIPTION
**Pull request by strongoier**
Related issue = fixes #3954

We should treat any `PtrOffsetStmt` (previously local tensors are excluded) as if it has already been stored with random values to prevent invalid optimization.

### CODE REVIEW

**Review by ailzhang — APPROVED** [review]
LGTM！

**Comment by BillXu2000** [comment]
I reran the code in #3954 and got log below:
```
{13:12}~/Desktop ➭ p test.py
[Taichi] version 0.8.10, llvm 10.0.0, commit 8fcbba32, linux, python 3.8.10
[Taichi] Starting on arch=x64
[W 01/12/22 13:12:02.151 64665] [control_flow_graph.cpp:get_store_forwarding_data@222] stmt 13 loaded in stmt 14 before storing.
[W 01/12/22 13:12:02.151 64665] [control_flow_graph.cpp:get_store_forwarding_data@222] stmt 18 loaded in stmt 19 before storing.
[W 01/12/22 13:12:02.151 64665] [control_flow_graph.cpp:get_store_forwarding_data@222] stmt 23 loaded in stmt 24 before storing.
[W 01/12/22 13:12:02.152 64665] [control_flow_graph.cpp:get_store_forwarding_data@222] stmt 13 loaded in stmt 14 before storing.
[W 01/12/22 13:12:02.152 64665] [control_flow_graph.cpp:get_store_forwarding_data@222] stmt 18 loaded in stmt 19 before storing.
[W 01/12/22 13:12:02.152 64665] [control_flow_graph.cpp:get_store_forwarding_data@222] stmt 23 loaded in stmt 24 before storing.
1
1
```
The result is correct, but are these warnings an expected behavior?

**Comment by strongoier** [comment]
> The result is correct, but are these warnings an expected behavior?

Fixed.

**Pull request merged**
