### PR TITLE
Dense Pointer snode to speed up listgen

### PR DESCRIPTION
**Pull request by KLozes**
Hi Yuanming, 

I wanted to get your feedback on this. I changed the pointer snode type to be hold an array of pointers, so that it doesn't have to be a child of dense snodes. I think this should give some good speed up for listgen. My code right now appears to work fine for activating sparse grids, but deactivation causes a seg fault. 

also, maybe we should rename pointer to dense_pointer

Thanks,
Kenneth

### CODE REVIEW

**Comment by yuanming-hu** [comment]
Oh so sorry about the delayed reply on my end. I've got too many things to do recently - Let me come back to you after finishing a paper submission deadline tonight!

**Comment by KLozes** [comment]
No problem, good luck!

**Comment by yuanming-hu** [comment]
Hi @KLozes 

I think this is a great idea! `pointer` has always been used together with `dense` so it makes sense to squash them into something like `dense_pointer`. This design will also make the tree shallower, alleviating annoying code such as `a.parent().parent().parent()...`.

I'm taking a look at the segfault now.

**Comment by KLozes** [comment]
Thanks! I found the segfault. It is in visit(SNodeOpStmt *stmt) in codgen_llvm.h, where I added the stmt->val->value to the arguments of call. This value isnt defined like it is for is_active op type. I think we need to make deactivate and SNodeOpExpression like is_active.

**Comment by yuanming-hu** [comment]
Yeah, working on fixing that...

**Comment by yuanming-hu** [comment]
(A quick way to pinpoint segfaults I usually use that might (or not) be useful to you: when taichi crashes, gdb will be triggered. I just enter the sudo passwd and then check statck backtrace with command `bt`, then find the line number of the crash...)

**Comment by yuanming-hu** [comment]
Actually, maybe we should keep the name `pointer`, because 
 - it's shorter than `dense_pointer`
 - feeding something `(ti.ij, [8, 8])` already hints that it's dense array

What do you think? Sorry about the delayed notice...

**Comment by yuanming-hu** [comment]
I'm stopping here to prevent our commits from conflicting :-)

Now the only failing sparse tests among `test_sparse_basics.py, test_sparse_deactivate.py, test_sparse_parallel.py` is `test_pointer2()`, where it seems that only one pointer gets deactivated instead of all. `test_sparse_deactivate::test_dynamic` was fixed in  60bb07e2 yet broken at head after merging for some reason.

I have to run now for a meeting...

**Comment by KLozes** [comment]
Thanks for the tip about gdb. Yes, actually I agree. I regretted the name change as soon as I did it.

**Comment by yuanming-hu** [comment]
If you don't mind, I'll continue fixing the final test case tomorrow and merge this PR. Let me know if you are still working on it.

**Comment by KLozes** [comment]
Sure! You can go ahead and finish up this PR if you would like. Thanks for all the help!

**Comment by yuanming-hu** [comment]
Done! (There are still some refactoring to do, but at least all tests passed.)

**Comment by KLozes** [comment]
Great! I'm seeing a huge improvement in listgen speed too.

**Pull request merged**
