### PR TITLE
[type] Fix struct-for on bit_struct

### PR DESCRIPTION
**Pull request by TH3CHARLie**
Related issue = #1905

[[Click here for the format server]](http://kun.csail.mit.edu:31415/)

----

### CODE REVIEW

**Review by xumingkuan — APPROVED** [review]
LGTM!

**Comment by TH3CHARLie** [comment]
The new added test passed locally while failed in CI, investigating...

**Comment by xumingkuan** [comment]
> The new added test passed locally while failed in CI, investigating...

This PR seems not based on the latest master branch -- try merging master into this branch?

**Review by Hanke98 — APPROVED** [review]
Cool! Thanks!

**Review by yuanming-hu — APPROVED** [review]
Cool, thanks!

**Pull request merged**
