### PR TITLE
[Doc] Developer installation update

### PR DESCRIPTION
**Pull request by qiao-bo**
Related issue = #2719

### CODE REVIEW

**Review by ailzhang — COMMENTED** [review]
btw would you mind adding a small section about `python setup.py clean` since it's now supported? ;) https://github.com/taichi-dev/taichi/pull/2962 Thanks a lot!

**Comment by qiao-bo** [comment]
> btw would you mind adding a small section about `python setup.py clean` since it's now supported? ;) #2962 Thanks a lot!

good point, will do

**Review by ljcc0930 — APPROVED** [review]
LGTM!

**Pull request merged**
