### PR TITLE
[Lang] Better type error messages

### PR DESCRIPTION
**Pull request by strongoier**
Related issue = #3301

This PR aims at setting up a mechanism to give better type error messages to users. To enable this, this PR also separates `type_check` from `Expression` constructors.

Let's look at a simple example:
```python
import taichi as ti

ti.init()

@ti.kernel
def func():
    a = 1
    b = 3.1
    c = a & b

func()
```

Before this PR, the error message is: (in fact, this is the simplest one I can get in Taichi - others usually involve very long purple stuff)
```
[Taichi] version 0.8.3, llvm 10.0.0, commit 5c1cf297, linux, python 3.8.10
[Taichi] Starting on arch=x64
[W 11/01/21 16:41:23.253 3711558] [type_check.cpp:operator()@308] [$15] Error: bitwise operations can only apply to integral types. at
[W 11/01/21 16:41:23.253 3711558] [type_check.cpp:operator()@310] 
  File "type_test.py", line 9, in func
    c = a & b
  File "/home/xuyi15/taichi/python/taichi/lang/common_ops.py", line 96, in __and__
    return ti.bit_and(self, other)
  File "/home/xuyi15/taichi/python/taichi/lang/ops.py", line 78, in wrapped
    return imp_foo(a, b)
  File "/home/xuyi15/taichi/python/taichi/lang/ops.py", line 63, in imp_foo
    return foo(x, y)

[W 11/01/21 16:41:23.253 3711558] [type_check.cpp:operator()@311] Compilation stopped due to type mismatch.
Traceback (most recent call last):
  File "type_test.py", line 11, in <module>
    func()
  File "/home/xuyi15/taichi/python/taichi/lang/kernel_impl.py", line 796, in wrapped
    return primal(*args, **kwargs)
  File "/home/xuyi15/taichi/python/taichi/lang/kernel_impl.py", line 724, in __call__
    return self.compiled_functions[key](*args)
  File "/home/xuyi15/taichi/python/taichi/lang/kernel_impl.py", line 682, in func__
    t_kernel(launch_ctx)
RuntimeError: Binary operator type mismatch
```

After this PR, the error message is:
```
[Taichi] version 0.8.4, llvm 10.0.0, commit 8d947831, linux, python 3.8.10
[Taichi] Starting on arch=x64
[Taichi] Compilation failed
  File "type_test.py", line 9, in func
    c = a & b
TaichiTypeError: unsupported operand type(s) for &: 'i32' and 'f32'
```

### CODE REVIEW

**Review by k-ye — COMMENTED** [review]
Very cool! One suggestion: do not use assertions for user errors, let's change to TI_ERROR macros

**Comment by strongoier** [comment]
> Very cool! One suggestion: do not use assertions for user errors, let's change to TI_ERROR macros

We are on our way to give better user error messages, and the new way is to throw `std::runtime_error` in C++ and catch it in Python for re-formatting. However, we should only do these for definite user-errors. For other cases, we stick to assertions to maintain invariants.

**Review by k-ye — APPROVED** [review]
LGTM!

**Pull request merged**
