### PR TITLE
[vulkan] More capabilities detection and enabling

### PR DESCRIPTION
**Pull request by bobcao3**
Enable float 16, int 8, and a bunch of other capabilities / device extension / device property related fixes

### CODE REVIEW

**Review by g1n0st — APPROVED** [review]

**Comment by AmesingFlank** [comment]
Have you tried using taichi fields with `u8` after this? Does it work?

**Comment by bobcao3** [comment]
> 
> 
> Have you tried using taichi fields with `u8` after this? Does it work?

That may not. Those will require separate extensions that adds support for uint8 in storage buffers (VK_KHR_8bit_storage). I have not added that yet. This only adds support for computations using int8 or int16 or float16

**Review by AmesingFlank — APPROVED** [review]

**Review by k-ye — APPROVED** [review]
LGTM!

**Pull request merged**
