### PR TITLE
[refactor] [lang] Restore ODOP support

### PR DESCRIPTION
**Pull request by archibate**
Related issue = #1827

[[Click here for the format server]](http://kun.csail.mit.edu:31415/)

----
The remove + restore, refactored away the `self.classfunc` and `self.classkernel` property completely.

### CODE REVIEW

**Comment by k-ye** [comment]
Again, please feel free to merge to experimental branches, as they impose no risk to `master`...

**Comment by archibate** [comment]
No, I will only merge after your approvement.
The point of such workflow is:
each PR into experimental branch is reviewed, so that we don't need review when merging experimental branch into master.
If you don't review this carefully, you'll have to review the final PR that merge into master, with a huge changeset.

**Comment by archibate** [comment]
Hello? My point for *experimental branches* is break PRs down. If you don't review the sub-PRs, then the workflow has no difference than a traditional monothonic PR.

**Comment by archibate** [comment]
Hello? I'm not using this workflow for fun. It requires you to review it, otherwise it's nothing different from traditional PRs.

**Comment by bobcao3** [comment]
Closing stale PR

**Pull request closed without merging**
