### PR TITLE
[Test] Migrate all cpp tests to googletest

### LINKED ISSUE #2221: Migrate existing C++ tests to googletest
This is a followup of #2195 . The goal is to migrate everything under `taichi/cpp` to use googletest (which aren't that many).

### PR DESCRIPTION
**Pull request by BillXu2000**
Related issue = close #2221 

[[Click here for the format server]](http://kun.csail.mit.edu:31415/)

----

This PR is supposed to migrate all cpp tests to google test.
Most of the original ti tests have been migrated, while three test files are kept unchanged.

test_exception_handling.cpp  test_gui.cpp, these two files do not contain any ti tests, but have three ti tasks in total.
I simply put these two in tests/cpp/task folder.

benchmark_sfg_edges.cpp, this file do have a ti test, but it does not work any more.
I do not change it and put it in tests/cpp/lagacy folder.

### CODE REVIEW

**Comment by xumingkuan** [comment]
Interestingly, the Tab size changed from 2 to 4 in some files, and @taichi-gardener doesn't complain about that?

**Review by k-ye — APPROVED** [review]
Looks great, thanks

**Review by xumingkuan — APPROVED** [review]
LGTM!

**Comment by k-ye** [comment]
Please resolve the conflict

**Comment by xumingkuan** [comment]
Sorry for merging a conflicting PR recently... @BillXu2000 feel free to reach out to me if you need any help about resolving conflicts.

**Pull request merged**
