### PR TITLE
[vulkan] FP16 support, fix a few bugs & warnings

### PR DESCRIPTION
**Pull request by bobcao3**
Related issue = #2992

1. FP16 is added to SPIR-V generator
2. Fixed a few bugs with setting capabilities (using `else` when it shouldn't)
3. Fixed a few warnings around this part of the code

Not sure whether we have FP16 tests on the master branch yet, so no actual testing have been done

### CODE REVIEW

**Comment by bobcao3** [comment]
Ran a few tests from #3373, seems okay

**Review by AmesingFlank — APPROVED** [review]
lgtm!

**Pull request merged**
