### PR TITLE
[cuda] Remove unified memory allocator

### PR DESCRIPTION
**Pull request by AmesingFlank**
Removing unified memory as per [this duscussion](https://docs.google.com/document/d/189sxKj7F0lVJ6E95DcrwWqmrh1K-JqLnKLKL7e_AknY/edit#heading=h.m4d4vb8qwq0g)

### CODE REVIEW

**Comment by AmesingFlank** [comment]
> Just one quick note: we should make sure programs initialized with `ti.init(use_unified_memory=True/False)` does not crash. Throw a warning instead :-) Thanks.

Good point.

**Comment by AmesingFlank** [comment]
I'm seeing a few "Deploy Failed" errors in CI, which I presume has something to do with the fact that I changed a `.md` file in my previous commit. Any idea how to fix this? @strongoier @k-ye

**Comment by k-ye** [comment]
@rexwangcc shall we just turn off these netlify deployment jobs now?

**Comment by AmesingFlank** [comment]
> > @rexwangcc shall we just turn off these netlify deployment jobs now?
> 
> Weird, those paths should have been fixed already on the lastest `master` 🤔 , @AmesingFlank would you mind rebasing onto lastet `master` (or updating them according to what're on `master`) for files under `docs/`?

sure, lemme try.

**Comment by rexwangcc** [comment]
> > > @rexwangcc shall we just turn off these netlify deployment jobs now?
> > 
> > 
> > Weird, those paths should have been fixed already on the lastest `master` 🤔 , @AmesingFlank would you mind rebasing onto lastet `master` (or updating them according to what're on `master`) for files under `docs/`?
> 
> Tried rebasing, still failing :((

😢 Lemme take a closer look! Sorry for the inconvenience!

**Pull request merged**
