### PR TITLE
[refactor] Make Expr constrctor explicit

### PR DESCRIPTION
**Pull request by Retrospection**
Related issue = #4271

### CODE REVIEW

**Review by k-ye — APPROVED** [review]
LGTM, thank you!

**Comment by k-ye** [comment]
Hmm, I believe this has broken the build. Could you help take a look?  https://github.com/taichi-dev/taichi/runs/5181090562?check_suite_focus=true

**Comment by Retrospection** [comment]
> Hmm, I believe this would break the build. Could you help take a look? https://github.com/taichi-dev/taichi/runs/5181090562?check_suite_focus=true

okay，I'll check and fix this~

**Comment by Retrospection** [comment]
I may have fixed the build error~

**Comment by bobcao3** [comment]
It seems there is still a tiny issue left, maybe a header that is not included?

**Pull request merged**
