### PR TITLE
[example] Create inital_value_problem.py

### PR DESCRIPTION
**Pull request by SuchtyTV**
Example of gradients. Added an example

Related issue = #

### CODE REVIEW

**Comment by SuchtyTV** [comment]
Anything you'd like to change?  🙂

**Review by k-ye — APPROVED** [review]
LGTM, welcome to the community!

**Comment by SuchtyTV** [comment]
> LGTM

Thank you! Hope I can help. Looking for some open source project and this one looks cool 🙂 Still have to learn many things 🙂

**Pull request merged**
