### PR TITLE
[ci] Auto generate manylinux dockerfile

### PR DESCRIPTION
**Pull request by qiao-bo**
Add an option in the script to generate our CentOS based dockerfile: `python Dockerfile_generator.py -o manylinux2014 -t cpu`. Locally tested.

### CODE REVIEW

**Review by rexwangcc — APPROVED** [review]
LGTM, thanks! Btw, the generated Dockerfile using the cli is slightly different from the existing manylinux one, shall we overwrite the existing one?

**Review by ailzhang — COMMENTED** [review]
Can we also add "#generated by python bla.. config" on top of the generated Dockerfile? ;)

**Pull request merged**
