### PR TITLE
[Lang] [IR] Add coordinate offset argument for ti.var and ti.Vector/Matrix

### PR DESCRIPTION
**Pull request by Rullec**
Related issue = #938 

[[Click here for the format server]](http://kun.csail.mit.edu:31415/)

### CODE REVIEW

**Comment by Rullec** [comment]
Hi all,
  First of all I felt quite sorry that it seems something goes wrong with this PR.:( It seems I forget the sync the upstream repo with my origin repo. I tried to rebase and merge on my local repo, but failed :(

  If there is any error in this first naive PR, please let me know! I will try to fix any possible error as soon as possible!

Best,
Xudong

**Comment by Rullec** [comment]
Thanks alot for your generous advice! They are really really professional.I will fix them tonight in my spare time.

**Comment by yuanming-hu** [comment]
> Thanks alot for your generous advice! They are really really professional.I will fix them tonight in my spare time.

Thank you very much, and no rush! 

Also note that most patches can be directly committed online on GitHub: https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/incorporating-feedback-in-your-pull-request#applying-suggested-changes

**Comment by archibate** [comment]
> First of all I felt quite sorry that it seems something goes wrong with this PR.:( It seems I forget the sync the upstream repo with my origin repo. I tried to rebase and merge on my local repo, but failed :(

I see, feel free to ask me about git operations, I used to suck these stuffs too, so I understand how you feel and willing to help.

**Comment by Rullec** [comment]
Hi Yubin,
  Thank you for your kindness! :D
  Would you please help me to check this annoying problem? So Here is my
workflow:

  step 1: I fork upstream taichi to my own github account (
https://github.com/Rullec/taichi) which is called origin repo
  step 2: git clone this fork to my own PC (local repo), and set the
upstream repo by (git remote add upstream git@github.com:
taichi-dev/taichi.git)
  step 3: 2 days later I finished my code on local repo (git commit -m "my
own comiit")
  step 4: *I push my local repo to my own forked Taichi(git push origin
master), without noticing that my fork of Taichi has behind the upstream
repo.*

[image: image.png]
  step 5: Get STUCK. now th origin repo diverged from the upstream one.

  step 6: Give up and simply click the Pull request button, I don't what I
can do at this moment.

What should I do now? What should I take care next time? Why does it
doesn't work? These 3Ws drive me crazy after googling.

Some more details for debug between step5 and step6:
btw, In step5 I tried a lot of possible solution, such as fetch the
upstream and merge it to my own repo. After solving the conflicts, it
produced 2 commits which I hate (In the guideline it shows that a PR should
contain ONLY one commit, no more than that) like this:

[image: image.png]

Then I try rebasing these 2 commits to a single one by "git rebase -i
53ac614", but It behaved strange, quite strange. It shows a lot of commits
from the upstream repo like this:
[image: image.png]

I change these "picks" to "s" as usual, but after that the git let me
solving conflicts again! Now I realized that something MUST happen but I
don't what the hell it was...

Git is a complex stuff, and work together is even harder. If my statement
above still makes you feel confused, please let me know at once!

Thank you for the help again in advance! Any suggestion is appreciated.

Bests,
Xudong




彭于斌 <notifications@github.com> 于2020年5月30日周六 下午10:02写道：

**Comment by archibate** [comment]
Thank for the infomation. The step 3 is wrong. You should **switch to a non-master branch** before you begin your work.

The suggested workflow for making a PR is:

step 1, 2: you were doing right!

step 3: **Before you decide to go work**, please pull the master of taichi-dev/taichi:
```bash
git checkout master
git pull --set-upstream upstream master  # pull from taichi-dev:master
```

step 4: Then, **switch to a separate branch for development**, never work directly in master branch:
```bash
git checkout master
git checkout -b offset # create and switch to a branch named `offset`
```
The name `offset` should be a brief description of your work, e.g., I use `matshape` for #1086.

step 5: When your work is done, make a commit (recall that we are in the branch `offset`):
```bash
git commit -m "[Lang] [IR] Add coordinate offset argument for ti.var and ti.Vector/Matrix"
git push --set-upstream origin offset # push to Rullec:offset
```
step 6. Create an pull request on GitHub.

step 7. Delete `Rullec:offset` after PR gets merged:
```bash
git branch -d offset
```

**Comment by archibate** [comment]
Sorry for the confuse! Git is a powerful tool yet unfriendly to beginners. Don't worry, I will try to help you resolve the mess here.

**Comment by archibate** [comment]
Oh no! I didn't meant to close your PR... why... could you run `git push -f` to make this PR open again?

**Comment by Rullec** [comment]
Hi Yubin,

  :-D Thanks a lot, I will reconsider my workflow under the help of your
guidence kindly!
  Also, About the unexpected closing of this PR: Should I simple run `git
push -f`? Don't I need to open a new PR?

Bests,
Xudong

彭于斌 <notifications@github.com> 于2020年6月1日周一 下午3:39写道：

**Comment by archibate** [comment]
> Don't I need to open a new PR?

Oh, it would be great! Please follow the suggested workflow and open a brand-new PR (from a non-master branch) so that the problems could gone. But in case that you lose your commits about this issue, please run `git push -f`.

**Pull request closed without merging**
