### PR TITLE
[ir] Basic function definition/call instructions

### PR DESCRIPTION
**Pull request by archibate**
Related issue id = #602

### CODE REVIEW

**Comment by archibate** [comment]
好累啊…`taichi/ir/ir.h`的修改总是导致很长时间的编译，能否将其拆分成不同部分？如`taichi/ir/ir_frontend.h`。

**Comment by archibate** [comment]
当前我们只有一个kernel offload，如何插入新的offload为了FrontendFuncDefStmt？

**Comment by yuanming-hu** [comment]
> 好累啊…`taichi/ir/ir.h`的修改总是导致很长时间的编译，能否将其拆分成不同部分？如`taichi/ir/ir_frontend.h`。

"Modifying a low-level header causes a recompilation of every cpp file that depends on it" is something notorious about C++. Maybe a more fundamental solution is to improve compilation speed in general. Currently, we have too many stuff in the headers (which gets recompiled over and over again) - maybe we should move these to the cpp files.

Btw do you use WeChat? Do you mind emailing me (yuanmhu@gmail.com) your WeChat id?

**Comment by yuanming-hu** [comment]
> 当前我们只有一个kernel offload，如何插入新的offload为了FrontendFuncDefStmt？

I guess it's better to store `FrontendFuncDefStmt` at the top level - I.e., the same level as `OffloadedStmt`.

**Comment by archibate** [comment]
> > 当前我们只有一个kernel offload，如何插入新的offload为了FrontendFuncDefStmt？
> 
> I guess it's better to store `FrontendFuncDefStmt` at the top level - I.e., the same level as `OffloadedStmt`.

Sounds reasonable, but where is OffloadedStmt stored? Can't find OffloadedStmt creation anywhere in export_lang. Isn't it done until lowering AST?

**Comment by yuanming-hu** [comment]
> > > 当前我们只有一个kernel offload，如何插入新的offload为了FrontendFuncDefStmt？
> > 
> > 
> > I guess it's better to store `FrontendFuncDefStmt` at the top level - I.e., the same level as `OffloadedStmt`.
> 
> Sounds reasonable, but where is OffloadedStmt stored? Can't find OffloadedStmt creation anywhere in export_lang. Isn't it done until lowering AST?

It's stored at the root level. Note that `OffloadedStmt` is created only after the `offload` pass, so in the frontend, it's not visible...

**Comment by archibate** [comment]
> Currently, we have too many stuff in the headers (which gets recompiled over and over again) - maybe we should move these to the cpp files.

Move some into cpp means no longer keep sync with defs in h? I still want to make `ir_xxx.h`'s..

> Btw do you use WeChat? Do you mind emailing me (yuanmhu@gmail.com) your WeChat id?

Email sent, hopefully gmail won't be forbidden by tianchao GFW.

**Comment by archibate** [comment]
> > > > 当前我们只有一个kernel offload，如何插入新的offload为了FrontendFuncDefStmt？
> > > 
> > > 
> > > I guess it's better to store `FrontendFuncDefStmt` at the top level - I.e., the same level as `OffloadedStmt`.
> > 
> > 
> > Sounds reasonable, but where is OffloadedStmt stored? Can't find OffloadedStmt creation anywhere in export_lang. Isn't it done until lowering AST?
> 
> It's stored at the root level. Note that `OffloadedStmt` is created only after the `offload` pass, so in the frontend, it's not visible...

So I should modify `offload.cpp`?

**Comment by yuanming-hu** [comment]
Just a minute. I'm updating https://github.com/taichi-dev/taichi/issues/602 to make things clear...

**Comment by yuanming-hu** [comment]
I'll merge this in for now, but I suggest that we **first come up with a detailed implementation plan before we start coding on this issue again**.

**Pull request merged**
