### PR TITLE
[gui] GGUI Tests

### PR DESCRIPTION
**Pull request by AmesingFlank**
I stored a few ground truth images in the `tests/python/images` folder. I'm not sure if this is the best thing to do. Lmk if you have any suggestions.

### CODE REVIEW

**Review by ailzhang — APPROVED** [review]
Thanks!! I'm happy with this as a temporary solution as long as we don't change it often. Later we might consider either only asserts on a few values in the images? 

Nit: maybe rename the folder to `expected`?

**Comment by ailzhang** [comment]
ohhhh @AmesingFlank the error here comes from we don't ship these image files in our wheel. 
Tbh we should use pytest instead of `ti test`  in CI (`ti test` isn't supposed to be user facing)

**Comment by AmesingFlank** [comment]
> ohhhh @AmesingFlank the error here comes from we don't ship these image files in our wheel. Tbh we should use pytest instead of `ti test` in CI (`ti test` isn't supposed to be user facing)

Hmm, how do I include these images into the wheel?

https://github.com/taichi-dev/taichi/blob/bc8eaa6be60798a8f09523ac02e2111eedbda323/setup.py#L85

Feels like the entire `tests` directly is being copied.

**Comment by AmesingFlank** [comment]
Ah nevermind. Figured it out. Needed to update `MANIFEST.IN`.

**Review by bobcao3 — APPROVED** [review]
Great work!

**Pull request merged**
