### PR TITLE
[CPU][Vulkan] Add missing ifdef macros if CPU is disabled

### PR DESCRIPTION
**Pull request by ghuau-innopeak**
Related issue = #3679

### CODE REVIEW

**Comment by AmesingFlank** [comment]
hmm, can't we just use `TI_WITH_LLVM` as guards?

**Comment by ghuau-innopeak** [comment]
> hmm, can't we just use `TI_WITH_LLVM` as guards?

Correct... :) I completely missed that the CPU source code was only added when LLVM was enabled. I will update the changes, the question now is... should I close this PR and push the changes in the other PR related to missing TI_WITH_LLVM? (#3702) Or should I still keep this one with the updated changes?

**Comment by AmesingFlank** [comment]
> > hmm, can't we just use `TI_WITH_LLVM` as guards?
> 
> @AmesingFlank Correct... :) I completely missed that the CPU source code was only added when LLVM was enabled. I will update the changes, the question now is... should I close this PR and push the changes in the other PR related to missing TI_WITH_LLVM? (#3702) Or should I still keep this one with the updated changes?

I think either is fine. Up to u really. I just approved #3702 btw.

**Comment by ghuau-innopeak** [comment]
Closing, PR merged with #3702 as all the changes are now related to LLVM.

**Pull request closed without merging**
