### PR TITLE
[Example] Refactor example library

### PR DESCRIPTION
**Pull request by victoriacity**
A substantial amount of example programs have been added into Taichi since the past year. With a well-organized `examples/` directory and adequate documentation for the example programs, not only can users have a clearer idea of Taichi's capabilities by navigating through and playing with the examples, but also will adding and reviewing new examples become more standardized.

This PR will introduce the following changes to the `examples/` directory and documentation:

- [x] Make all example run without dependencies: currently all but `mass_spring_3d` ~~and `tree_gravity`~~ run without dependencies while these two exceptions require `taichi_three` and `taichi_glsl` packages.
- [x] Categorize examples: examples are now categorized as below:
- `examples/algorithms`: Fundamental algorithms and data structures (MGPCG, spatial data structures, etc)
- `examples/chi_examples`: Examples of CHI IR
- `examples/features`: Features of Taichi compiler and frontend, including sparse computing, IO and GUI . 
- `examples/ml`: Machine learning and differentiable computing
- `examples/rendering`: Rendering methods
- `examples/simulation`: Physical simulations
- [x] Make categorized examples accessible to the `ti` executable
- [x] ~~Documentation for examples and adding new examples~~ (per #2492, this will be addressed separately due to ongoing documentation updates)

This PR is in draft stage and should not change anything out of the `ti` executable script, `examples/` and `docs/` directories. Inputs are welcome!

### CODE REVIEW

**Comment by victoriacity** [comment]
> aha, why not ask user to install taichi_glsl and put utils there? Just ask me in wechat for pypi token!

@yuanming-hu and I agreed that all examples in the Taichi main repo should be self-contained. The goal of examples is to provide high-quality reference code snippets for new users to learn Taichi, so ideally examples would aim to be as concise and clear as possible. 

Of course, introducing libraries will make the code even clearer (`tree_gravity` becomes evidently less intuitive after making it self-contained), so these examples will be eventually moved to the [Advanced Examples repository](https://github.com/taichi-dev/advanced_examples) where we can feel free to let users to install `taichi_glsl` and other libraries so that users can enjoy the contributions from Taichi extensions.

**Comment by yuanming-hu** [comment]
> With a well-organized `examples/` directory and adequate documentation for the example programs, not only can users have a clearer idea of Taichi's capabilities by navigating through and playing with the examples, but also will adding and reviewing new examples become more standardized.

I strongly agree that examples serve as the facade of a programming language, and they should 

 1. Represent code of the *highest quality*;
 2. Be *simple and concise*.

Many of the current examples do not satisfy these criteria and need to be removed (or moved to advanced examples after polishment). For example, I believe `laplace.py` (which I wrote 2 years ago) should be (sadly) removed - the demonstrated kernel leads to memory access out of bound, and may mislead readers. Note that `laplace.py` is used in some other files so we need to be careful. There are many other examples that are too complex for a newcomer (e.g., `renderer.py`, not really well written/documented).

@victoriacity and I will schedule a meeting to walk through all the examples.

**Review by yuanming-hu — APPROVED** [review]
LGTM! Just one nit :-)

**Comment by rexwangcc** [comment]
> (per [Doc] Remove all .rst docs #2492, this will be addressed in the docs repo)

Just a reminder that once https://github.com/taichi-dev/taichi/pull/2494 is merged we should (and also make it clear to developers of the main repo) use this repo, **not** the docs repo as the source of truth of the documentation. docs repo will become a mirrorred-content hosting repo + translations hub and only be updated if there are functional changes to the docsite itself.

**Pull request merged**
