### PR TITLE
[Doc] Fix typos in doc_writing.

### PR DESCRIPTION
**Pull request by ailzhang**

### CODE REVIEW

**Comment by ailzhang** [comment]
cc: @rexwangcc Do you happen to know why the inline footnote doesn't work? :P

**Comment by strongoier** [comment]
It seems that your modifications are included in my draft #2987 :-) And I removed the inline footnote since it is not included in the documentation https://www.markdownguide.org/extended-syntax/#footnotes.

**Comment by ailzhang** [comment]
@strongoier oh nice, I'm happy to close this one ;) Btw we mentioned supporting markdown-it syntax in the doc but it didn't work. markdown-it does support inline footnote :P

**Comment by rexwangcc** [comment]
> @strongoier oh nice, I'm happy to close this one ;) Btw we mentioned supporting markdown-it syntax in the doc but it didn't work. markdown-it does support inline footnote :P

Yea, sorry for pointing it out! I didn't realize it when writing the initial version of doc guide but it seems MDX only supports a portion of the markdown-it feature set and inline footnote is not in one of them :( https://github.com/mdx-js/mdx/issues/545. I guess we should remove it from the doc writing guide!

**Pull request closed without merging**
