### PR TITLE
[Metal] Use managed storage mode to improve performance

### PR DESCRIPTION
**Pull request by k-ye**
It turned out the current `.shared` storage mode has made things pretty slow. This PR switched to use the `.managed` storage mode for `MTLBuffer`s, see https://developer.apple.com/documentation/metal/setting_resource_storage_modes/choosing_a_resource_storage_mode_in_macos.

Benchmark result:

| example       | old FPS (.shared) | new FPS (.managed) |
|---------------|-------------------|--------------------|
| mpm88         | 21-22             | 25-28              |
| mpm_lag_force | 11                | 13                 |
| stable_fluid  | 23                | 50                 |
| vortex*        | 1.2               | 6                  |

* I shamelessly copied the vortex example from here https://forum.taichi.graphics/t/vortex-method-demo/775. Note that the original example's `fix_streamfunc` had a global reduction to a kernel temporary variable. This wasn't supported in TLS yet, so I changed that to use a `ti.var` to store the global sum result. Also note that the global reduction here hurt the performance so much that, if I reduce the #threads from 262144 to 65536 (i.e. grid-stride loop), because of TLS and the reduced number of fatomic add, the FPS went to 12.
* The main bottleneck of mpm_lag_force is now GUI (30% of the time on GUI, only 12% on Metal. 4.4% out of that 12% was spent on `Snode::write_float` )

Related issue = #935

[[Click here for the format server]](http://kun.csail.mit.edu:31415/)

----

### CODE REVIEW

**Comment by k-ye** [comment]
@yuanming-hu not related to this PR. I found that just by enabling fast math, `sdf_render.py` went from 25fps to 41fps. 

* Do you know if fast math is always on on CUDA?
* If not, shall we add this to the compile config, e.g. `ti.init(..., use_fast_math=True)`?

**Comment by archibate** [comment]
> ti.init(..., fast_math=True)

#1396, should I add this option to that examp?

**Comment by k-ye** [comment]
> #1396, should I add this option to that examp?

Sure! Sorry i'll have to take a look tmr. But i see that you've already added `fast_math`..?

**Comment by yuanming-hu** [comment]
By default, `CompileConfig::fast_math` is on:

https://github.com/taichi-dev/taichi/blob/571ff554d752300bc2a0b756b5e4b18b3df16e4e/taichi/program/compile_config.cpp#L35

> * Do you know if fast math is always on on CUDA?

It follows ``CompileConfig::fast_math`:

https://github.com/taichi-dev/taichi/blob/571ff554d752300bc2a0b756b5e4b18b3df16e4e/taichi/backends/cuda/jit_cuda.cpp#L174

> * If not, shall we add this to the compile config, e.g. `ti.init(..., use_fast_math=True)`? (fast math broke some examples on Metal, so I don't think it can be always on..)

I believe `ti.init(fast_math=True/False)` is already supported - which Metal example does it break?

**Pull request merged**
