### PR TITLE
[refactor] Move ti.lib to ti._lib and move ti.core to ti._lib.core

### PR DESCRIPTION
**Pull request by lin-hitonami**
Related issue = #

### CODE REVIEW

**Comment by lin-hitonami** [comment]
Since the vulkan support for M1 without installing molten-vk or vulkan sdk seems broken even in the master branch, I cannot test whether my change broke it or not.

**Review by strongoier — CHANGES_REQUESTED** [review]
There are some conflicts to be handled as #3774 is in :-)

**Review by ailzhang — APPROVED** [review]
LGTM! Thanks!

**Pull request merged**
