### PR TITLE
[Bug] Disable vkCmdWriteTimestamp with MacOS to enable tests on Vulkan

### LINKED ISSUE #5888: Investigate vulkan support on macos 10.15
Currently vulkan backend is not working properly on macos 10.15 (with molten-vk installed) so we actually skipped testing ti.vulkan on macos 10.15. We need to investigate the root cause there.

### PR DESCRIPTION
**Pull request by jim19930609**
Related issue = fix #5888

### CODE REVIEW

**Review by ailzhang — COMMENTED** [review]
NIce!! would you mind also enabling macOS 15 Vulkan build and test along with this PR so that we have some tests? (feel free to turn off the ones are still broken ;) https://github.com/taichi-dev/taichi/blob/master/.github/workflows/testing.yml#L222

**Comment by jim19930609** [comment]
Looks like most Vulkan tests are passed, but failed a few ones with precision issue: 

image

Any idea how we can blacklist these tests on MacOS 10.15 with x86_64 arch, or shall I implement a blacklist? @ailzhang @feisuzhu

**Comment by PENGUINLIONG** [comment]
Feel free to disable timestamps on macOS entirely. I found it not working with M1 also.

**Review by PENGUINLIONG — APPROVED** [review]
lgtm

**Review by ailzhang — APPROVED** [review]
Thanks!!

**Pull request merged**
