### PR TITLE
[cuda] Increase saturating grid dim to reduce tail effect

### PR DESCRIPTION
**Pull request by qiao-bo**

### CODE REVIEW

**Comment by taichi-gardener** [comment]
current commit hash: 42ca7938f15493c0184fb0d51c7d0a4dadf1b9dc

master commit hash: 458c31cd69f1e93065cbffa153d0cd4d2fe8e521

| Examples(CUDA) | ad_gravity | comet | cornell_box | fem128 | fem99 | fractal | game_of_life | inital_value_problem | mpm128 | mpm3d | mpm88 | mpm99 | mpm_lagrangian_forces | nbody | odop_solar | pbf2d | sdf_renderer | simple_uv | taichi_logo | vortex_rings |
|:--:|:--:|:--:|:--:|:--:|:--:|:--:|:--:|:--:|:--:|:--:|:--:|:--:|:--:|:--:|:--:|:--:|:--:|:--:|:--:|:--:|
| kernel_elapsed_time ( current/master ) | -3.4365% | **+9.8757%** | -5.0983% | +0.4333% | -2.1352% | -11.5228% | -1.1146% | +1.9194% | +0.6978% | +1.8387% | +0.2289% | +1.3405% | -1.3974% | -0.51% | **+6.0634%** | +0.504% | -8.5499% | -2.2892% | -2.0721% | -2.8943% |
| end2end_time ( current/master ) | -1.4379% | **+12.6328%** | -5.0642% | +0.4747% | -1.061% | -7.9667% | +0.8952% | +0.4456% | +4.1094% | -0.1824% | -0.0174% | +1.1857% | -1.8798% | -0.6215% | +1.051% | -9.6163% | -9.2236% | -2.4718% | -2.1161% | -2.8469% |


| benchmarks fluctuation threshold | 5.0% |
|:--:|:--:|
| kernel improvement |fractal(-11.5228%), sdf_renderer(-8.5499%), cornell_box(-5.0983%), |
| kernel regression |odop_solar(**+6.0634%**), comet(**+9.8757%**), |
| end2end improvement |pbf2d(-9.6163%), sdf_renderer(-9.2236%), fractal(-7.9667%), cornell_box(-5.0642%), |
| end2end regression |comet(**+12.6328%**), |

**Comment by taichi-gardener** [comment]
current commit hash: 42ca7938f15493c0184fb0d51c7d0a4dadf1b9dc

master commit hash: 458c31cd69f1e93065cbffa153d0cd4d2fe8e521

| Examples(CUDA) | ad_gravity | comet | cornell_box | fem128 | fem99 | fractal | game_of_life | inital_value_problem | mpm128 | mpm3d | mpm88 | mpm99 | mpm_lagrangian_forces | nbody | odop_solar | pbf2d | sdf_renderer | simple_uv | taichi_logo | vortex_rings |
|:--:|:--:|:--:|:--:|:--:|:--:|:--:|:--:|:--:|:--:|:--:|:--:|:--:|:--:|:--:|:--:|:--:|:--:|:--:|:--:|:--:|
| kernel_elapsed_time ( current/master ) | +1.3656% | **+8.9605%** | -5.1514% | -8.0505% | +1.4528% | -11.934% | -2.3504% | +2.4223% | +0.0633% | +1.1796% | -0.0175% | +0.5006% | -1.7619% | +0.279% | +0.6209% | +0.5614% | -8.3778% | -2.3596% | -2.087% | -1.7952% |
| end2end_time ( current/master ) | -0.4902% | **+13.2715%** | -5.0107% | +0.762% | -0.2866% | -13.3237% | -0.0228% | -0.9676% | +3.3919% | -0.5772% | -0.3317% | +0.6671% | -1.5507% | +0.1324% | -0.4612% | -8.5869% | -8.5928% | -2.3973% | -2.1216% | -2.7184% |


| benchmarks fluctuation threshold | 5.0% |
|:--:|:--:|
| kernel improvement |fractal(-11.934%), sdf_renderer(-8.3778%), fem128(-8.0505%), cornell_box(-5.1514%), |
| kernel regression |comet(**+8.9605%**), |
| end2end improvement |fractal(-13.3237%), sdf_renderer(-8.5928%), pbf2d(-8.5869%), cornell_box(-5.0107%), |
| end2end regression |comet(**+13.2715%**), |

**Comment by taichi-gardener** [comment]
current commit hash: 174642c9908c6d8f7dcda362549b642c43e4d520

master commit hash: 0a7a7c4cf25cbfc969bd93811945069b61cce6d1

| Examples(CUDA) | ad_gravity | comet | cornell_box | fem128 | fem99 | fractal | game_of_life | inital_value_problem | mpm128 | mpm3d | mpm88 | mpm99 | mpm_lagrangian_forces | nbody | odop_solar | pbf2d | sdf_renderer | simple_uv | taichi_logo | vortex_rings |
|:--:|:--:|:--:|:--:|:--:|:--:|:--:|:--:|:--:|:--:|:--:|:--:|:--:|:--:|:--:|:--:|:--:|:--:|:--:|:--:|:--:|
| kernel_elapsed_time ( current/master ) | -0.3494% | -0.0366% | -5.1516% | -2.3172% | -3.259% | -11.647% | +1.6122% | +0.223% | +1.2191% | +0.7595% | -0.2654% | -0.6772% | -0.4187% | -0.2619% | -1.3044% | +1.1407% | -8.429% | -2.3275% | -2.3937% | -1.747% |
| end2end_time ( current/master ) | +0.3232% | -0.0908% | -5.1971% | -0.566% | -0.6248% | -10.8139% | +2.5804% | -0.3957% | -2.0696% | -0.5666% | -0.4857% | -0.3937% | -1.2715% | -0.8707% | +3.3797% | +3.2929% | -9.4857% | -2.4261% | -2.0732% | -3.2515% |


| benchmarks fluctuation threshold | 5.0% |
|:--:|:--:|
| kernel improvement |fractal(-11.647%), sdf_renderer(-8.429%), cornell_box(-5.1516%), |
| kernel regression | None |
| end2end improvement |fractal(-10.8139%), sdf_renderer(-9.4857%), cornell_box(-5.1971%), |
| end2end regression | None |

**Comment by qiao-bo** [comment]
For coment:

1. `config_.saturating_grid_dim = num_SMs * query_max_block_per_sm * 2`

```
=========================================================================
Kernel Profiler(count) @ CUDA on NVIDIA GeForce RTX 3080
=========================================================================
[      %     total   count |      min       avg       max   ] Kernel name
-------------------------------------------------------------------------
[ 46.60%   1.046 s  70000x |    0.013     0.015     0.022 ms] substep_c44_0_kernel_13_listgen_S1bitmasked
[ 24.13%   0.542 s  70000x |    0.004     0.008     0.016 ms] substep_c44_0_kernel_14_struct_for
[  9.85%   0.221 s  70000x |    0.002     0.003     0.676 ms] substep_c44_0_kernel_12_serial
[  7.65%   0.172 s  10000x |    0.015     0.017     0.027 ms] render_c48_0_kernel_17_listgen_S1bitmasked
[  4.23%   0.095 s  10000x |    0.005     0.009     0.012 ms] render_c48_0_kernel_18_struct_for
[  2.37%   0.053 s  10000x |    0.004     0.005     0.011 ms] render_c48_0_kernel_15_range_for
[  2.31%   0.052 s  10000x |    0.004     0.005     4.659 ms] generate_c46_0_kernel_11_range_for
[  1.46%   0.033 s  10000x |    0.002     0.003     0.005 ms] generate_c46_0_kernel_10_serial
[  1.40%   0.031 s  10000x |    0.002     0.003     0.004 ms] render_c48_0_kernel_16_serial
-------------------------------------------------------------------------
[100.00%] Total execution time:   2.246 s   number of results: 9
=========================================================================
{'case_name': 'example_comet', 'repeat_times': 10000, 'kernel_elapsed_time_ms': 2245.73632550356}
```

2. `config_.saturating_grid_dim = num_SMs * query_max_block_per_sm` 

```
=========================================================================
Kernel Profiler(count) @ CUDA on NVIDIA GeForce RTX 3080
=========================================================================
[      %     total   count |      min       avg       max   ] Kernel name
-------------------------------------------------------------------------
[ 37.38%   0.655 s  70000x |    0.008     0.009     0.016 ms] substep_c44_0_kernel_13_listgen_S1bitmasked
[ 29.89%   0.523 s  70000x |    0.004     0.007     0.016 ms] substep_c44_0_kernel_14_struct_for
[ 11.84%   0.207 s  70000x |    0.002     0.003     1.258 ms] substep_c44_0_kernel_12_serial
[  6.15%   0.108 s  10000x |    0.009     0.011     0.013 ms] render_c48_0_kernel_17_listgen_S1bitmasked
[  5.37%   0.094 s  10000x |    0.005     0.009     0.014 ms] render_c48_0_kernel_18_struct_for
[  2.98%   0.052 s  10000x |    0.004     0.005     0.011 ms] render_c48_0_kernel_15_range_for
[  2.95%   0.052 s  10000x |    0.004     0.005     5.277 ms] generate_c46_0_kernel_11_range_for
[  1.76%   0.031 s  10000x |    0.002     0.003     0.006 ms] generate_c46_0_kernel_10_serial
[  1.67%   0.029 s  10000x |    0.002     0.003     0.004 ms] render_c48_0_kernel_16_serial
-------------------------------------------------------------------------
[100.00%] Total execution time:   1.751 s   number of results: 9
=========================================================================
{'case_name': 'example_comet', 'repeat_times': 10000, 'kernel_elapsed_time_ms': 1751.2888554437086}
```

Observation: The listgen kernel should be optimized with smaller grid_dim

**Review by yolo2themoon — APPROVED** [review]
LGTM! Thanks!

**Review by bobcao3 — APPROVED** [review]
LGTM

**Pull request merged**
