### PR TITLE
[CI] Recheck the title format when user updates the title

### PR DESCRIPTION
**Pull request by Zheaoli**
Related issue = #

### CODE REVIEW

**Review by ailzhang — APPROVED** [review]
nice! now we can add title check to be merge blocking as well :D

**Review by ailzhang — CHANGES_REQUESTED** [review]
@Zheaoli hmmm somehow presubmit.yml no longer runs here?

**Comment by Zheaoli** [comment]
@ailzhang Already fixed

**Review by ailzhang — APPROVED** [review]
Nice thanks!

**Pull request merged**
